-- --------------------------------------------------
-- FRED 2018 - R4 - OCTOBRE 2018 
-- INJECTION DES DONNES RAZEL BEC - NOUVEAU PLAN DE RESSOURCES
-- --------------------------------------------------


EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='10-100',@Code='LIT-ENCA',@Libelle='LITIGE MO ENCADREMENT',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='11-100',@Code='LIT-MO',@Libelle='LITIGE MO PRODUCTION ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='12-200',@Code='LIT-PERSO',@Libelle='LITIGE MAIN D''OEUVRE DIVERS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='12-300',@Code='LIT-FORM',@Libelle='LITIGE FORMATION CONTINUE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='21-100',@Code='LIT-INSTAL',@Libelle='LITIGE MATERIEL INSTALLATION',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='22-100',@Code='LIT-TERR',@Libelle='LITIGE MATERIEL TERRASSEMENT',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='22-200',@Code='LIT-CAMIO',@Libelle='LITIGE CAMION',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='22-500',@Code='LIT-LEV',@Libelle='LITIGE MATERIEL LEVAGE ET MANUTENTION',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='22-700',@Code='LIT-CONCA',@Libelle='LITIGE MATERIEL CONCASSAGE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='23-100',@Code='LIT-ENERG',@Libelle='LITIGE MATERIEL ENERGIE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='23-200',@Code='LIT-POMPE',@Libelle='LITIGE MATERIEL POMPAGE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='23-300',@Code='LIT-LOCMAT',@Libelle='LITIGE LOCATION MATERIEL ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='24-100',@Code='LIT-TOPO',@Libelle='LITIGE MATERIEL TOPO',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='26-100',@Code='LIT-VUVL',@Libelle='LITIGE VUVL',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-100',@Code='LIT-CARBU',@Libelle='LITIGE CARBURANT',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-200',@Code='LIT-PNEU',@Libelle='LITIGE PNEUMATIQUES ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-210',@Code='LIT-USUR',@Libelle='LITIGE OUTILS ATTAQUE AU SOL',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-220',@Code='LIT-PCR',@Libelle='LITIGE PIECES DE RECHANGE ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-230',@Code='LIT-TR',@Libelle='LITIGE TRAINS DE ROULEMENT',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-240',@Code='LIT-FOATE',@Libelle='LITIGE FOURNITURES ATELIER',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-250',@Code='LIT-GAZ',@Libelle='LITIGE GAZ OXYGENE ACETYLENE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-260',@Code='LIT-OUATE',@Libelle='LITIGE PETIT OUTILLAGE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-270',@Code='LIT-FOMAT',@Libelle='LITIGE FOURNIT.DIVERSES MATERIEL',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='29-300',@Code='LIT-ENTMAT',@Libelle='LITIGE ENTRETIEN MATERIEL',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-100',@Code='LIT-EAU',@Libelle='LITIGE EAU',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-120',@Code='LIT-REDE',@Libelle='LITIGE MATERIAUX DE CARRIERE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-140',@Code='LIT-TVE',@Libelle='LITIGE TERRE VEGETALE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-160',@Code='LIT-LIANT',@Libelle='LITIGE CHAUX - LIANTS ',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-180',@Code='LIT-EXPL',@Libelle='LITIGE EXPLOSIFS ET ACCESSOIRES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-200',@Code='LIT-BETON',@Libelle='LITIGE BETON PRET À LEMPLOI',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-240',@Code='LIT-CIMEN',@Libelle='LITIGE CIMENT',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-260',@Code='LIT-ARMA',@Libelle='LITIGE ARMATURES BA ET BP',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-280',@Code='LIT-COFFR',@Libelle='LITIGE COFFRAGE ',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-300',@Code='LIT-PRECO',@Libelle='LITIGE PRECONTRAINTE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-320',@Code='LIT-BOIS',@Libelle='LITIGE BOIS-CONTREPLAQUES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-380',@Code='LIT-PALPL',@Libelle='LITIGE PALPLANCHES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-400',@Code='LIT-PREFA',@Libelle='LITIGE PREFA ',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-440',@Code='LIT-MOBU',@Libelle='LITIGE MOBILIER URBAIN, MUR ET',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-460',@Code='LIT-PAVE',@Libelle='LITIGE PIERRES PAVES DALLES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-480',@Code='LIT-PVC',@Libelle='LITIGE PRODUITS SYNTHETIQUES -PVC',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-500',@Code='LIT-METAL',@Libelle='LITIGE PRODUITS METALLURGIQUES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-520',@Code='LIT-ASPH',@Libelle='LITIGE ASPHALTE BITUME EMULSION',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-540',@Code='LIT-GEO',@Libelle='LITIGE FOURNITURES ETANCHEITE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-560',@Code='LIT-SERR',@Libelle='LITIGE SERRURERIE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-580',@Code='LIT-CHIM',@Libelle='LITIGE PRODUITS CHIMIQUES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-600',@Code='LIT-VEGE',@Libelle='LITIGE VEGETAUX',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-610',@Code='LIT-PHYTO',@Libelle='LITIGE PRODUITS PHYTO SANITAIRES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-620',@Code='LIT-FOURNI',@Libelle='LITIGE FOURNITURES E CHANTIER',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-630',@Code='LIT-FOURLABO',@Libelle='LITIGE FOURNITURE LABO ET QUALITE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-640',@Code='LIT-FOURTOPO',@Libelle='LITIGE FOURNITURE TOPOGRAPHIE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-650',@Code='LIT-SECUR',@Libelle='LITIGE DEPENSES ET FOURNITURES SECURITE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-670',@Code='LIT-REDEV',@Libelle='LITIGE REDEVANCE SUR DECHARGE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='30-680',@Code='LIT-TRSV',@Libelle='LITIGE TRANSPORT SUR VENTES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='40-100',@Code='LIT-STPD',@Libelle='LITIGE SOUS-TRAITANTS ',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='40-500',@Code='LIT-STPE',@Libelle='LITIGE SOUS-TRAITANTS ',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-110',@Code='LIT-ETUD',@Libelle='LITIGE FRAIS D ETUDES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-210',@Code='LIT-CTRL',@Libelle='LITIGE BUREAUX DE CONTRÖLES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-310',@Code='LIT-ESSAI',@Libelle='LITIGE PREST.LABO.-CONTR/ESSAIS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-510',@Code='LIT-GARDIEN',@Libelle='LITIGE GARDIENNAGE-SURVEILLANCE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-515',@Code='LIT-TRANS',@Libelle='LITIGE TRANSPORT',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-520',@Code='LIT-PREST',@Libelle='LITIGE AUTRES PRESTATIONS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-620',@Code='LIT-HON',@Libelle='LITIGE CONSEILS ET HONORAIRES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-810',@Code='LIT-NDD',@Libelle='LITIGE PRESTATIONS INTERNES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-910',@Code='LIT-ACTE',@Libelle='LITIGE CONSEILS ET HONORAIRES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='50-950',@Code='LIT-PIL',@Libelle='LITIGE PILOTAGE/MANDAT/GERANCE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-100',@Code='LIT-MISS',@Libelle='LITIGE MISSIONS ET RECEPTIONS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-110',@Code='LIT-VOY',@Libelle='LITIGE FRAIS DE VOYAGE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-120',@Code='LIT-RECRT',@Libelle='LITIGE FRAIS RECRUTEMENT PERSONNEL',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-200',@Code='LIT-TERRAIN',@Libelle='LITIGE LOCATION DE TERRAIN',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-210',@Code='LIT-CBAIL',@Libelle='LITIGE CREDIT BAIL IMMOBILIER',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-230',@Code='LIT-ENTC',@Libelle='LITIGE ENTRETIEN CONSTRUCTION',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-300',@Code='LIT-LOCBUR',@Libelle='LITIGE LOC.DE MATERIEL DE BUREAU',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-310',@Code='LIT-ENTBUR',@Libelle='LITIGE ENTRET.MATL.DE BUR.&INFO.',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-320',@Code='LIT-COURS',@Libelle='LITIGE COURSIERS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-410',@Code='LIT-POST',@Libelle='LITIGE AFFRANCH, FRAIS POSTAUX',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-420',@Code='LIT-PHON',@Libelle='LITIGE TELECOMMUNICATIONS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-500',@Code='LIT-FINFO',@Libelle='LITIGE FOURN.INFORMATIQUE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-510',@Code='LIT-FOURBUR',@Libelle='LITIGE FOURN.DE BUREAU',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-520',@Code='LIT-DOCU',@Libelle='LITIGE DOC.GENERALE ABONNEMENTS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-530',@Code='LIT-REPRO',@Libelle='LITIGE REPROGRAPHIE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-600',@Code='LIT-KDO',@Libelle='LITIGE CADEAUX A LA CLIENTELE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-610',@Code='LIT-DON',@Libelle='LITIGE DIVERS, DONS, POURBOIRES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-700',@Code='LIT-SEMI',@Libelle='LITIGE COLLOQUES ET SEMINAIRES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-710',@Code='LIT-PUB',@Libelle='LITIGE PUBLICITÉS ET PUBLICATIONS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-750',@Code='LIT-COTIS',@Libelle='LITIGE COTISATIONS SYNDICATS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-760',@Code='LIT-TRAD',@Libelle='LITIGE FRAIS DE TRADUCTION',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-765',@Code='LIT-ARCH',@Libelle='LITIGE FRAIS D''ARCHIVAGE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-770',@Code='LIT-BREVET',@Libelle='LITIGE REDEVANCE /BREVETS',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-780',@Code='LIT-DROIT',@Libelle='LITIGE DROITS DENREG,TIMB.FISC.',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-800',@Code='LIT-TAXE',@Libelle='LITIGE AUTRES IMPOTS & TAXES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-810',@Code='LIT-PENAL',@Libelle='LITIGE PENALITES AMENDES FISCALE',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-860',@Code='LIT-ASSU',@Libelle='LITIGE ASSURANCES',@Type='Autre'
EXEC Fred_ToolBox_Ressources @GroupeCode='GRZB',@SousChapitreCode='60-900',@Code='LIT-SUBV',@Libelle='LITIGE SUBVENTIONS EXPLOITATIONS',@Type='Autre'



-- -----------------------------------------
-- INJECTION ASSOCIATION NATURE & RESSOURCES
-- -----------------------------------------

EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ENCA',@NatureCode='105100'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-MO',@NatureCode='105250'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PERSO',@NatureCode='160000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-FORM',@NatureCode='101202'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-INSTAL',@NatureCode='212420'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TERR',@NatureCode='211540'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-CAMIO',@NatureCode='211520'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-LEV',@NatureCode='211600'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-CONCA',@NatureCode='211640'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ENERG',@NatureCode='211610'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-POMPE',@NatureCode='211620'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-LOCMAT',@NatureCode='213110'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TOPO',@NatureCode='211650'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-VUVL',@NatureCode='211510'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-CARBU',@NatureCode='221140'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PNEU',@NatureCode='221600'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-USUR',@NatureCode='221510'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PCR',@NatureCode='221720'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TR',@NatureCode='221810'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-FOATE',@NatureCode='221930'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-GAZ',@NatureCode='221932'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-OUATE',@NatureCode='221933'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-FOMAT',@NatureCode='221900'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ENTMAT',@NatureCode='221931'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-EAU',@NatureCode='611500'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-REDE',@NatureCode='334100'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TVE',@NatureCode='311620'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-LIANT',@NatureCode='319300'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-EXPL',@NatureCode='313000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-BETON',@NatureCode='321000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-CIMEN',@NatureCode='321500'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ARMA',@NatureCode='326000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-COFFR',@NatureCode='317100'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PRECO',@NatureCode='324000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-BOIS',@NatureCode='317200'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PALPL',@NatureCode='327300'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PREFA',@NatureCode='325000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-MOBU',@NatureCode='311640'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PAVE',@NatureCode='314000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PVC',@NatureCode='317000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-METAL',@NatureCode='328000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ASPH',@NatureCode='320100'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-GEO',@NatureCode='315000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-SERR',@NatureCode='337000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-CHIM',@NatureCode='318000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-VEGE',@NatureCode='311610'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PHYTO',@NatureCode='311630'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-FOURNI',@NatureCode='333000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-FOURLABO',@NatureCode='611600'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-FOURTOPO',@NatureCode='611620'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-SECUR',@NatureCode='618710'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-REDEV',@NatureCode='334200'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TRSV',@NatureCode='334400'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-STPD',@NatureCode='410000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-STPE',@NatureCode='450000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ETUD',@NatureCode='592000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-CTRL',@NatureCode='592100'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ESSAI',@NatureCode='581400'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-GARDIEN',@NatureCode='582400'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TRANS',@NatureCode='619000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PREST',@NatureCode='590000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-HON',@NatureCode='591100'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-NDD',@NatureCode='582300'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ACTE',@NatureCode='593000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PIL',@NatureCode='594000'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-MISS',@NatureCode='611160'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-VOY',@NatureCode='611170'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-RECRT',@NatureCode='611990'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TERRAIN',@NatureCode='611230'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-CBAIL',@NatureCode='611300'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ENTC',@NatureCode='611400'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-LOCBUR',@NatureCode='611630'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ENTBUR',@NatureCode='611700'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-COURS',@NatureCode='611220'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-POST',@NatureCode='611200'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PHON',@NatureCode='611210'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-FINFO',@NatureCode='611610'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-FOURBUR',@NatureCode='611740'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-DOCU',@NatureCode='611750'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-REPRO',@NatureCode='611760'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-KDO',@NatureCode='611810'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-DON',@NatureCode='611820'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-SEMI',@NatureCode='611951'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PUB',@NatureCode='611770'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-COTIS',@NatureCode='611780'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TRAD',@NatureCode='611190'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ARCH',@NatureCode='611195'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-BREVET',@NatureCode='611790'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-DROIT',@NatureCode='611850'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-TAXE',@NatureCode='611805'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-PENAL',@NatureCode='611961'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-ASSU',@NatureCode='649400'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GRZB',@SocieteCode='RB',@Achats='Oui',@RessourceCode='LIT-SUBV',@NatureCode='630720'
