-- --------------------------------------------------
-- FRED 2018 - R4 - OCTOBRE 2018 
-- INJECTION DES DONNES POUR FRED - GROUPE FAYAT TP
-- --------------------------------------------------



-- --------------------------------------------------
-- INJECTION DES CHAPITRES
-- --------------------------------------------------
 EXEC Fred_ToolBox_Chapitre   @Code='10', @Libelle='MO ENCADREMENT', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Chapitre   @Code='20', @Libelle='MATERIEL', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Chapitre   @Code='11', @Libelle='MO PRODUCTION', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Chapitre   @Code='12', @Libelle='AUTRES CHARGES MO', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Chapitre   @Code='30', @Libelle='MATERIAUX & FOURNITURES', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Chapitre   @Code='40', @Libelle='SOUS TRAITANCE', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Chapitre   @Code='50', @Libelle='PRESTATIONS DE SERVICES', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Chapitre   @Code='60', @Libelle='AUTRES FRAIS', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Chapitre   @Code='70', @Libelle='PROVISIONS', @GroupeCode= 'GFTP'



-- --------------------------------------------------
-- INJECTION DES SOUS-CHAPITRES
-- --------------------------------------------------
 EXEC Fred_ToolBox_SousChapitre   @Code='10-105', @Libelle='CONDUCTEUR DE TRAVAUX', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-100', @Libelle='DIRECTEUR', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-110', @Libelle='CHEF DE CHANTIER', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-200', @Libelle='ETUDES', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-300', @Libelle='QSE', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-400', @Libelle='GÉOMÈTRE', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-450', @Libelle='LABORATOIRE', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-500', @Libelle='ADMINISTRATIFS', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-600', @Libelle='MÉCANIQUE', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-800', @Libelle='STAGIAIRE ENCADREMENT', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-900', @Libelle='ENCADREMENT AUTRE', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='10-109', @Libelle='Ouvrier', @ChapitreCode= '10', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='21-100', @Libelle='MATERIEL INSTALLATION', @ChapitreCode= '20', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='22-100', @Libelle='MATERIEL TERRASSEMENT', @ChapitreCode= '20', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='22-200', @Libelle='CAMIONS', @ChapitreCode= '20', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='22-300', @Libelle='MATERIEL GENIE CIVIL', @ChapitreCode= '20', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='22-400', @Libelle='MATERIEL FORAGE ET SOUTERRAINS', @ChapitreCode= '20', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='22-500', @Libelle='MATERIEL LEVAGE et MANUTENTION', @ChapitreCode= '20', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='22-600', @Libelle='MATERIEL ROUTE', @ChapitreCode= '20', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='22-700', @Libelle='MATERIEL CONCASSAGE', @ChapitreCode= '20', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='11-100', @Libelle='CHEF D''EQUIPE', @ChapitreCode= '11', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='11-200', @Libelle='CONDUCTEUR D''ENGIN/CHAUFFEUR', @ChapitreCode= '11', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='11-300', @Libelle='OUVRIER ', @ChapitreCode= '11', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='11-600', @Libelle='MECANICIEN/ELECTRICIEN', @ChapitreCode= '11', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='11-800', @Libelle='STAGIAIRE OUVRIER', @ChapitreCode= '11', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='11-900', @Libelle='MO DIRECTE AUTRE', @ChapitreCode= '11', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='12-100', @Libelle='VETEMENTS DE TRAVAIL', @ChapitreCode= '12', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='12-200', @Libelle='AUTRES FRAIS DE PERSONNEL', @ChapitreCode= '12', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='12-300', @Libelle='FORMATION', @ChapitreCode= '12', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_SousChapitre   @Code='100-101', @Libelle='Matériaux & Fournitures SOMOPA', @ChapitreCode= '30', @GroupeCode= 'GFTP'



-- --------------------------------------------------
-- INJECTION DES RESSOURCES
-- --------------------------------------------------
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-05', @Libelle='CONDUCTEUR DE TRAVAUX', @SousChapitreCode= '10-105',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-01', @Libelle='DIRECTEUR', @SousChapitreCode= '10-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-10', @Libelle='CHEF DE CHANTIER', @SousChapitreCode= '10-110',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-15', @Libelle='ETUDES', @SousChapitreCode= '10-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-20', @Libelle='QSE', @SousChapitreCode= '10-300',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-25', @Libelle='GÉOMÈTRE', @SousChapitreCode= '10-400',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-30', @Libelle='LABORATOIRE', @SousChapitreCode= '10-450',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-35', @Libelle='ADMINISTRATIFS', @SousChapitreCode= '10-500',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-40', @Libelle='MÉCANIQUE', @SousChapitreCode= '10-600',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-45', @Libelle='STAGIAIRE ENCADREMENT', @SousChapitreCode= '10-800',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-50', @Libelle='INTÉRIM ENCADREMENT', @SousChapitreCode= '10-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-60', @Libelle='PRÊT DE MO ENCADREMENT ', @SousChapitreCode= '10-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-90', @Libelle='AUTRE MO ENCADREMENT', @SousChapitreCode= '10-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-98', @Libelle='OD INTERIM ENCADREMENT', @SousChapitreCode= '10-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENCA-99', @Libelle='OD MO ENCADREMENT', @SousChapitreCode= '10-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='OUVR-01', @Libelle='Ouvrier', @SousChapitreCode= '10-109',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ASCEN-001', @Libelle='ASCENCEUR', @SousChapitreCode= '21-100',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ATELI-1661', @Libelle='HANGAR ATELIER BATEX', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BUNGA-1511', @Libelle='BUNGALOW BUREAU', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BUNGA-1610', @Libelle='BUNGALOW SANITAIRE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BUNGA-1640', @Libelle='BUNGALOW  VESTIAIRE/REFECTOIRE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BUNGA-1641', @Libelle='BUNGALOW LABORATOIRE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CLOTU-01', @Libelle='CLÖTURES', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CONTE-1215', @Libelle='CONTENEUR ENVIRONNEMENT', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CONTE-1503', @Libelle='CONTENEUR REMORQUE AMENAGE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CONTE-1530', @Libelle='CONTAINER ATELIER', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CONTE-1550', @Libelle='CONTAINER GRAISSAGE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CONTE-1570', @Libelle='CONTAINER MAGASIN', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CONTE-1571', @Libelle='CONTAINER VIDE POUR STOCKAGE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CONTE-1572', @Libelle='CONTENEUR  SECURITE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CONTE-001', @Libelle='CONTENEUR', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CUVE-1051', @Libelle='CUVE CARBURANT ', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ESCAL-001', @Libelle='ESCALIER', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='RADIO-001', @Libelle='RADIO ', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ECHAF-001', @Libelle='ECHAFFAUDAGES', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PONT-1861', @Libelle='PONT BASCULE ', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='SILO-001', @Libelle='SILOS', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TOUR-8201', @Libelle='TOUR ET MAT DECLAIRAGE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TOUR-8250', @Libelle='TOUR D''ECLAIRAGE SECTEUR', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TREMI-2771', @Libelle='TREMIE', @SousChapitreCode= '21-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='AUTOG-001', @Libelle='AUTOGRADE', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BRH-0654', @Libelle='MARTEAU BRISE ROCHE 200 A 300KG', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BRH-0657', @Libelle='MARTEAU BRISE ROCHE 600/1000KG', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BRH-0660', @Libelle='MARTEAU BRISE ROCHE 1000 KG MAXI', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BRH-0661', @Libelle='MARTEAU BRH 1000 A 2500 KG', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BRH-0672', @Libelle='MARTEAU BRH 2500 A 3500 KG', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BULL-4461', @Libelle='TRACTEUR SUR CHENILLES TYPE D5K', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BULL-4487', @Libelle='TRACTEUR CHENILLES TYPE D6K LGP', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BULL-4492', @Libelle='TRACTEUR CHENS TYPE D6R RIPPER', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BULL-4501', @Libelle='TRACTEUR CHENILLES TYPE D6R LGP', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BULL-4515', @Libelle='TRACTEUR CHENS TYPE D7R RIPPER', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BULL-4532', @Libelle='TRACTEUR CHENS TYPE D8R RIPPER', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4651', @Libelle='CHARGEUR COMPACT PNEUS TYPE 246', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4652', @Libelle='CHARGEUR COMPACT PNEUS TYPE 226', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4653', @Libelle='CHARG COMPACT PNEUS, 2,6 T+ACC', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4654', @Libelle='CHARGEUR COMPACT S/PNEUS TYP 262', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4661', @Libelle='CHARGEUSE SUR PNEU TYPE 906', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4672', @Libelle='CHARGEUR SUR PNEU TYPE 928/938', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4682', @Libelle='CHARGEUR SUR PNEU TYPE 950/L120', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4693', @Libelle='CHARGEUR SUR PNEU TYPE 966/L150', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4701', @Libelle='CHARGEUR SUR PNEU TYPE 980', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4741', @Libelle='CHARGEUSE SUR CHENILLES < 943', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4761', @Libelle='CHARGEUSE SUR CHENILLES TYPE 953', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4771', @Libelle='CHARGEUSE SUR CHENILLES TYPE 963', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4796', @Libelle='CHARGEUSE PELLETEUSE 80-100 CV', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHARG-4798', @Libelle='CHARGEUSE PELLETEUSE 90-110CV', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7609', @Libelle='PLAQUE VIBRANTE REVERSIBL BPH80', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7620', @Libelle='PLAQUE VIBRANTE', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7660', @Libelle='COMPACTEUR VIBR TANDEM 75 A 90 CM', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7661', @Libelle='COMPACTEUR VIBR & GUID TELECOMM', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7750', @Libelle='COMPACTEUR VIBRANT TANDEM 90CM', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7751', @Libelle='COMPACTEUR VIBRANT TANDEM 100CM', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7754', @Libelle='COMPACTEURVIBR TANDEM 100 A 120 CM', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7763', @Libelle='COMPACTEUR VIBR TANDEM 8 A 10 T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7766', @Libelle='COMPACTEUR VIBRANT TANDEM 10 A 13T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7781', @Libelle='COMPACTEUR BW213 SANS VARIO CONTROL', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7782', @Libelle='COMPACTEUR VIBRANT MONOBILLE 8-10T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7785', @Libelle='COMPACTEUR VIBR MONOBILLE 12 A 15T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7790', @Libelle='COMPACTEUR VIBRANT MONOBILLE 16-18T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7795', @Libelle='COMPACTEUR VIBRANT MONOBILLE 19-21T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7800', @Libelle='COMPACTEUR VIBR MONOBILL+VARIO CTRL', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7851', @Libelle='COMPACTEUR SUR PNEU P1 3T/ROUE', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='COMPA-7880', @Libelle='COMPACTEUR SUR PNEU P3 5T/ROUE', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='DECAP-015', @Libelle='DECAPEUSE', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='DUMPE-4801', @Libelle='MINI DUMPER 2,5T)', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='DUMPE-4802', @Libelle='DUMPER GRAVILLONNEUR', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='DUMPE-4807', @Libelle='DUMPER RIGIDE CU 28 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='DUMPE-4812', @Libelle='DUMPER RIGIDE CU 36 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='DUMPE-4896', @Libelle='DUMPER ARTICULE CU 30 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='DUMPE-4922', @Libelle='DUMPER ARTICULE B40', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='NIVEL-4956', @Libelle='NIVELEUSE TYPE INF 120', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='NIVEL-4960', @Libelle='NIVELEUSE TYPE 120', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='NIVEL-4966', @Libelle='NIVELEUSE TYPE 12', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='NIVEL-4973', @Libelle='NIVELEUSE TYPE 140', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='NIVEL-4979', @Libelle='NIVELEUSE TYPE 14', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4003', @Libelle='PELLE A CABLE 130T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4046', @Libelle='MINIPELLE 2.5T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4048', @Libelle='MINI PELLE SUR CHEN 5.3T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4051', @Libelle='PELLE SUR CHENILLES 7 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4116', @Libelle='PELLE SUR PNEUS 15-16 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4122', @Libelle='PELLE SUR PNEUS 17-22 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4125', @Libelle='PELLE SUR PNEUS 12-15 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4130', @Libelle='PELLE SUR PNEUS 12-15 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4236', @Libelle='PELLE SUR CHENILLES 15-17 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4262', @Libelle='PELLE SUR CHENILLES 18-23 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4306', @Libelle='PELLE SUR CHENILLES 24-27 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4331', @Libelle='PELLES SUR CHENILLE 28-37 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4333', @Libelle='EQUIPEMENT BRAS LONG 18M', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4334', @Libelle='EQUIPEMENT BRAS LONG 15M', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4342', @Libelle='PELLES SUR CHENILLE 38-45 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4365', @Libelle='PELLES SUR CHENILLE 46-58 TONNES', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4384', @Libelle='PELLE SUR CHENILLE CARR. 60-70T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PELLE-4388', @Libelle='PELLE SUR CHEN DE CARR. 71-87T', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TRACTO-001', @Libelle='TRACTOPELLE', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PILON-7601', @Libelle='PILONNEUSE', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='SCRAP-4639', @Libelle='MOTORSCRAPEUR ELEVATEUR615C', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='SCRAP-4643', @Libelle='MOTORSCRAPER ELEVATEUR TYPE 623', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TAMPI-7551', @Libelle='TAMPING 21 TONNES (815)', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TAMPI-7580', @Libelle='TAMPING 32 TONNES (825)', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TRACT-4592', @Libelle='TRACTEUR AGRICOLE 4X2 80-100 CV', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TRACT-4593', @Libelle='TRACTEUR AGRICOLE 4X4 80-100 CV', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TRACT-4595', @Libelle='TRACTEUR AGRICOLE 4X4 150-200 CV', @SousChapitreCode= '22-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5101', @Libelle='CAMION 4X2 BENNE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5102', @Libelle='CAMION 4X2 TRIBENNE 8M3', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5105', @Libelle='CAMION 4X2 BENNE GRUE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5115', @Libelle='CAMION 6X4 BENNE ', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5116', @Libelle='CAMION 6X4 TRI-BENNE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5117', @Libelle='CAMION 6X4 BENNE  GRUE ', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5120', @Libelle='CAMION 6X6 BENNE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5130', @Libelle='CAMION 8X4 BENNE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5132', @Libelle='CAMION 8X4 AVEC BENNE CARRIERE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5133', @Libelle='CAMION 8X4 BENNE TERRASS', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5170', @Libelle='CAMION INTERVENTION ATELIER', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5205', @Libelle='BUS TRANSPORT PERSONNEL 25-30 PLACES', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5206', @Libelle='BUS TRANSPORT PERSONNEL 50PL', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5260', @Libelle='CAMION 4X4 CITERNE FOD 11M3', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5275', @Libelle='CAMION 4X2  CITERNE EAU - ARROSEUSE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5285', @Libelle='CAMION 6X4 CITERNE EAU 22M3', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5330', @Libelle='SEMI BANANE CIMENT 25-30 TONNES', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5331', @Libelle='SEMI STOCKAGE PULVE PETITE CAPACITE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5410', @Libelle='CAMION 4X4 STATION GRAISSAGE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5501', @Libelle='CAMION 6X4 TOUPIE 7M3', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5503', @Libelle='CAMION 8X4 TOUPIE BETON 7M3', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5504', @Libelle='CAMION 6X4 MALAXEUR 9M3', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5551', @Libelle='BALAYEUSE ASPIR 4M3 PORT. 4X2', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5601', @Libelle='CAMION 4X2 PLATEAU', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5605', @Libelle='CAMION 4X2 PLATEAU & GRUE AUX', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5606', @Libelle='CAMION 4X2 BEN DEVT LAT+GRUE AUX', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5627', @Libelle='CAMION 6X4 PLATEAU GRUE AUXILIAIRE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5651', @Libelle='SEMI BENNE 22 M3', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5680', @Libelle='SEMI PLATEAU 12-13M , 24-28 T CU', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5691', @Libelle='SEMI PORTE ENGIN 50-55 TONNES CU', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5694', @Libelle='REMORQUE PORTE TOURET', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5695', @Libelle='REMORQUE PORTE ENGIN 6-10T', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5696', @Libelle='REMORQUE PORTE ENGIN CU INF 5T', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5699', @Libelle='REMORQUE AGRICOLE 8-10 T CU', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5701', @Libelle='CAMION ESSAI DE PLAQUE', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5751', @Libelle='TRACTEUR ROUTIER 4X2', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5760', @Libelle='TRACTEUR ROUTIER 6X4', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CAMIO-5765', @Libelle='TRACTEUR ROUTIER 6X6', @SousChapitreCode= '22-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BANCH-001', @Libelle='BANCHES', @SousChapitreCode= '22-300',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='22-600-001', @Libelle='Matériel de route générique', @SousChapitreCode= '22-600',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-01', @Libelle='CHEF D''EQUIPE', @SousChapitreCode= '11-100',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-05', @Libelle='CONDUCTEUR D''ENGIN', @SousChapitreCode= '11-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-10', @Libelle='CHAUFFEUR', @SousChapitreCode= '11-200',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-15', @Libelle='OUVRIER ', @SousChapitreCode= '11-300',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-20', @Libelle='MANŒUVRE', @SousChapitreCode= '11-300',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-30', @Libelle='MÉCANICIEN', @SousChapitreCode= '11-600',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-35', @Libelle='ELECTRICIEN', @SousChapitreCode= '11-600',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-45', @Libelle='STAGIAIRE PRODUCTION', @SousChapitreCode= '11-800',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-50', @Libelle='INTÉRIM PRODUCTION', @SousChapitreCode= '11-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-60', @Libelle='PRÊT DE MO DE PRODUCTION', @SousChapitreCode= '11-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-90', @Libelle='AUTRE MO DE PRODUCTION', @SousChapitreCode= '11-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-98', @Libelle='OD MO INTERIM', @SousChapitreCode= '11-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MO-99', @Libelle='OD MO PRODUCTION', @SousChapitreCode= '11-900',  @TypeRessourceId='2', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='GRAN-01', @Libelle='GRAVE-SABLE-AGREGATS', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='VEGE-01', @Libelle='VEGETAUX', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TERVEG-01', @Libelle='TERRE VEGETALE', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PHYTO-00', @Libelle='PRODUITS PHYTO SANITAIRES', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MOBI-01', @Libelle='MOBILIER URBAIN, MUR ET', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENROB-01', @Libelle='ENROBES', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PAVE-01', @Libelle='Pierres, dalles et pavés', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='GEO-08', @Libelle='GEOCOMPOSITES & ASSIMILÉS', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='EXPL-10', @Libelle='EMULSION', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='METAL-10', @Libelle='ELEMENTS FONTE', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PREFA-10', @Libelle='Tuyau béton Achat Conso', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BOIS-00', @Libelle='BOIS-CONTREPLAQUES', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CHAUX-01', @Libelle='CHAUX VIVE', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ASPH-02', @Libelle='ASPHALTE ET BITUME', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='BETON-01', @Libelle='BETON PRET À L''EMPLOI', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CIMEN-01', @Libelle='CIMENT', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PREFA-01', @Libelle='ELEMENTS PREFABRIQUES', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ARMA-00', @Libelle='ARMATURES BA ET BP', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='PALPL-01', @Libelle='PALPLANCHES', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='METAL-00', @Libelle='PRODUITS METALLURGIQUES', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='OUTI-00', @Libelle='OUTILLAGE TRAVAUX', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MCOM-01', @Libelle='MATERIAUX COMPOSITES', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='REDEV-02', @Libelle='REDEVANCE SUR DECHARGE', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TRANS-01', @Libelle='TRANSPORT SUR ACHAT', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='LOCA-01', @Libelle='Location véhicules', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='LOCA-02', @Libelle='Location engins de chantier', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='LOCA-03', @Libelle='Locations ponctuelles', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='LOCA-04', @Libelle='Locations longue durée > 6 mois', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='CARB-01', @Libelle='carburants & lubrifiants', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENTR-01', @Libelle='Entretien des vehicules', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ENTR-02', @Libelle='Entretien materiel & outillage Industriel', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='OXYG-01', @Libelle='Oxygène et gaz soudure atelier', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='SOUS-01', @Libelle='sous-traitance travaux chantiers PADI', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='SOUS-02', @Libelle='sous-traitance travaux chantiers', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ETUD-01', @Libelle='Achats d''études et prestations de services', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='HONO-01', @Libelle='Honoraires techniques', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='HONO-02', @Libelle='Honoraires conseils juridiques', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='FRAI-01', @Libelle='Frais d''actes et de contentieux', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='HONO-03', @Libelle='Honoraires divers', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MISS-01', @Libelle='Missions', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='POST-01', @Libelle='Affranchissements', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='TELE-01', @Libelle='Téléphone', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='FRAI-02', @Libelle='Frais divers', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='MAIN-01', @Libelle='Maintenance', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='EAU-01', @Libelle='eau', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='ELEC-01', @Libelle='Electricité', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='VETM-01', @Libelle='Vêtements de travail et  de sécurité', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='FINFO-01', @Libelle='Fournitures informatiques', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='FOURN-02', @Libelle='Autres matières et fournitures', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='LOCA-05', @Libelle='Locations ponctuelles', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='FOURN-03', @Libelle='fournitures bureau', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='DOCG-01', @Libelle='Documentation générale', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'
 EXEC Fred_ToolBox_Ressources   @Code='KDO-01', @Libelle='Cadeaux à la clientèle', @SousChapitreCode= '100-101',  @TypeRessourceId='1', @Active='1', @CarburantId='', @Consommation='', @GroupeCode= 'GFTP'



-- --------------------------------------------------
-- INJECTION DES NATURES ANALYTIQUES
-- --------------------------------------------------
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601150', @Libelle='Granulats Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115019', @Libelle='Espaces Verts Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115024', @Libelle='Pierres maturelles, dalles et pavés', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115013', @Libelle='Enrobés Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115011', @Libelle='Liants Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115016', @Libelle='Produits plastique composite manufacturés Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115020', @Libelle='Tuyau béton Achat Conso', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115022', @Libelle='Tuyau PVC Achat Conso', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115017', @Libelle='Produit Naturel Conditionné Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115014', @Libelle='Produits métalliques manufacturés Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60614000', @Libelle='carburants & lubrifiants', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115012', @Libelle='Béton prêt emploi Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115015', @Libelle='Produits béton manufacturés Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115025', @Libelle='ACIERS', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60631100', @Libelle='Fournitures d''entretien, petit outillage, petit éq', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60530000', @Libelle='Retraitement de déchets', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62410000', @Libelle='Transports sur achats', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='61353000', @Libelle='Location véhicules', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='61356000', @Libelle='Location engins de chantier', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='61351000', @Libelle='Locations ponctuelles', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='61355000', @Libelle='Locations longue durée > 6 mois', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='61552000', @Libelle='Entretien des vehicules', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='61551600', @Libelle='Entretien materiel & outillage Industriel', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60612000', @Libelle='Oxygène et gaz soudure atelier', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60500405', @Libelle='sous-traitance travaux chantiers PADI', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60500400', @Libelle='sous-traitance travaux chantiers', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60400000', @Libelle='Achats d''études et prestations de services', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62265400', @Libelle='Honoraires techniques', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62263000', @Libelle='Honoraires conseils juridiques', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62270000', @Libelle='Frais d''actes et de contentieux', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62260000', @Libelle='Honoraires divers', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62560000', @Libelle='Missions', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62610000', @Libelle='Affranchissements', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62620000', @Libelle='Téléphone', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62881000', @Libelle='Frais divers', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='61561000', @Libelle='Maintenance', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60611200', @Libelle='eau', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60613000', @Libelle='electricite', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60634000', @Libelle='vetements de travail et  de securité', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60641600', @Libelle='Fournitures informatiques', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60680000', @Libelle='Autres matières et fournitures', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60641000', @Libelle='fournitures bureau', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='61810000', @Libelle='Documentation générale', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='62340000', @Libelle='Cadeaux à la clientèle', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='60115010', @Libelle='Granulat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601151', @Libelle='Espaces Verts Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601152', @Libelle='Pierre naturelle', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601153', @Libelle='Enrobés', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601154', @Libelle='Liants Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601155', @Libelle='Produits plastique composite manufacturés Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601156', @Libelle='Produits plastique composite manufacturés Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601157', @Libelle='Tuyau béton Achat Conso', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601158', @Libelle='Tuyau PVC Achat Conso', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601159', @Libelle='Produit Naturel Conditionné Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601160', @Libelle='Produits métalliques manufacturés Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601161', @Libelle='Béton prêt emploi Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601162', @Libelle='Produits béton manufacturés Achat', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601163', @Libelle='Acier Achat Conso', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601164', @Libelle='Fournitures d''entretien, petit outillage, petit éq', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601165', @Libelle='Retraitement de déchets', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601166', @Libelle='Transports sur achats', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601167', @Libelle='Location véhicules', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601168', @Libelle='Location engins de chantier', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601169', @Libelle='Locations ponctuelles', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601170', @Libelle='Locations longue durée > 6 mois', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601171', @Libelle='carburants & lubrifiants', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601172', @Libelle='Entretien des vehicules', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601173', @Libelle='Entretien materiel & outillage Industriel', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601174', @Libelle='Oxygène et gaz soudure atelier', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601175', @Libelle='sous-traitance travaux chantiers PADI', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601176', @Libelle='sous-traitance travaux chantiers', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601177', @Libelle='Achats d''études et prestations de services', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601178', @Libelle='Honoraires techniques', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601179', @Libelle='Honoraires conseils juridiques', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601180', @Libelle='Frais d''actes et de contentieux', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601181', @Libelle='Honoraires divers', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601182', @Libelle='Missions', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601183', @Libelle='Affranchissements', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601184', @Libelle='Téléphone', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601185', @Libelle='Frais divers', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601186', @Libelle='Maintenance', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601187', @Libelle='eau', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601188', @Libelle='electricite', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601189', @Libelle='vetements de travail et  de securité', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601190', @Libelle='Fournitures informatiques', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601192', @Libelle='Autres matières et fournitures', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601193', @Libelle='Locations ponctuelles', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601194', @Libelle='fournitures bureau', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601195', @Libelle='Documentation générale', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601196', @Libelle='Cadeaux à la clientèle', @SocieteCode= '0143', @IsActif='1'
 EXEC Fred_ToolBox_Nature  @GroupeCode='GFTP' , @Code='601199', @Libelle='Ouvrier', @SocieteCode= '0143', @IsActif='1'

