------ --------------------------------------------------
------ FRED 2018 - R4 - OCTOBRE 2018 
------ INJECTION DES DONNES POUR FRED - GROUPE FAYAT TP
------ --------------------------------------------------

-- Attention Fichier envoyé uniquement en INTEGRATION - FORMATION - PREPRODUCTION -  PRODUCTION
DECLARE @MaterielCount INT;
DECLARE @SocieteId INT = (SELECT Societeid FROM FRED_SOCIETE Where Code = '0143' AND GroupeId = (SELECT GroupeId FROM FRED_GROUPE WHERE code = 'GFTP'))
DECLARE @EtablissementComptableId INT = (SELECT EtablissementComptableId FROM FRED_ETABLISSEMENT_COMPTABLE Where SocieteId =  @SocieteId)
DECLARE @RessourceId INT = 
		(
		SELECT        FRED_RESSOURCE.RessourceId
		FROM            dbo.FRED_CHAPITRE INNER JOIN
								 dbo.FRED_SOUS_CHAPITRE ON dbo.FRED_CHAPITRE.ChapitreId = dbo.FRED_SOUS_CHAPITRE.ChapitreId INNER JOIN
								 dbo.FRED_RESSOURCE ON dbo.FRED_SOUS_CHAPITRE.SousChapitreId = dbo.FRED_RESSOURCE.SousChapitreId
		WHERE		FRED_CHAPITRE.GroupeId = (SELECT GroupeId FROM FRED_GROUPE WHERE code = 'GFTP')
		AND			FRED_RESSOURCE.Code = 'MAT-1506'
		)


		
		PRINT '-------------------'
		PRINT 'MATERIEL AVANT INJECTION POUR SOMOPA'
		SET @MaterielCount =  (SELECT COUNt(*) FROM FRED_MATERIEL WHERE SocieteId = @SocieteId);
		PRINT @MaterielCount
		PRINT '-------------------'

IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00102')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00102', 'Camion 19T Grue MAN', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00103')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00103', 'Camion 19T Grue MAN', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00106')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00106', 'Renault Mascot - Double cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00112')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00112', 'Mercedes Sprinter 411 CDI', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00114')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00114', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00118')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00118', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00119')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00119', 'MANITOU', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00120')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00120', 'MANITOU', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00121')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00121', 'Abri Bodard', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00122')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00122', 'Abri Bodard', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00123')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00123', 'Abri Ouest', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00124')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00124', 'Roulotte Citadine SOMOPA', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00125')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00125', 'Roulotte Citadine SOMOPA', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00127')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00127', 'Remorque 3.5 T Gourdon', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00128')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00128', 'Remorque Moiroud', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00129')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00129', 'Mini Pelle TAKEUCHI TB 125 2,5T', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00132')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00132', 'Citerne à eau YSM', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00133')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00133', 'Citerne d''eau Gourdon', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00134')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00134', 'Citerne d''eau Ouest Abri', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00135')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00135', 'Compresseur ATLAS COPCO', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00136')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00136', 'Compresseur ATLAS COPCO', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00137')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00137', 'Compresseur YANMAR', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00138')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00138', 'Compresseur YANMAR', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00144')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00144', 'Manitou Téléscopique', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00145')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00145', 'Atelier Pavage', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00147')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00147', 'Citerne à eau', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00148')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00148', 'Mini Pelle KOMATSU PC 30MR 3T5', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00149')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00149', 'Renault Maxity Double cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00150')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00150', 'Renault Maxity Double cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00151')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00151', 'Camion 19T Grue MAN', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00152')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00152', 'Renault Maxity Double cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00153')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00153', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00154')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00154', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00155')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00155', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00156')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00156', 'Camion 19T Renault', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00157')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00157', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00158')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00158', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00159')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00159', 'Renault Maxity - Double Cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00160')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00160', 'Renault Maxity - Double Cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00163')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00163', 'Pelle Mécalac', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00164')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00164', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00165')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00165', 'Renault Maxity - Double Cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00168')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00168', 'Camion 19T Grue MAN', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00169')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00169', 'Renault Mégane', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00170')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00170', 'Renault Maxity Double cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00171')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00171', 'Renault Maxity', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00172')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00172', 'Renault Maxity Double cabine', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00173')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00173', 'Remorque MiniPat 1000', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00174')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00174', 'Remorque KOMATSU', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00175')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00175', 'Mini Pelle KOMATSU PC 35MR3,5T', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00176')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00176', 'Mini Pelle KOMATSU PC 26MR2,5T', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00177')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00177', 'Renault Clio', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00178')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00178', 'Renault Mégane scénic', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00179')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00179', 'Camion 26T Grue (6x4)', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00180')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00180', 'Abri Contener', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00181')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00181', 'Renault Mégane scénic', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00182')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00182', 'Renault Master', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00183')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00183', 'Renault Master Fourgon', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00184')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00184', 'Renault Master', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END
IF((SELECT COUNT(*) FROM FRED_MATERIEL WHERE Societeid = @SocieteId AND Code = 'SOM00185')=0) BEGIN INSERT INTO FRED_MATERIEL (SocieteId, RessourceId, Code, Libelle, Actif, AuteurCreationId, DateCreation, IsStorm, EtablissementComptableId) VALUES(@SocieteId, @RessourceId, 'SOM00185', 'Renault Clio', 1,1,GETDATE(),1,@EtablissementComptableId); PRINT 'Ajout OK' END ELSE BEGIN PRINT 'Déjà existant' END


PRINT '-------------------'
PRINT 'MATERIEL APRES INJECTION POUR SOMOPA'
SET @MaterielCount =  (SELECT COUNt(*) FROM FRED_MATERIEL WHERE SocieteId = @SocieteId);
PRINT @MaterielCount
PRINT '-------------------'