//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureDevise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureDevise() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureDevise", typeof(FeatureDevise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Iso Nombre.
        /// </summary>
        public static string Devise_Index_PanelMain_IsoNombre {
            get {
                return ResourceManager.GetString("Devise_Index_PanelMain_IsoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string Devise_Index_PanelMain_Libelle {
            get {
                return ResourceManager.GetString("Devise_Index_PanelMain_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbole.
        /// </summary>
        public static string Devise_Index_PanelMain_Symbole {
            get {
                return ResourceManager.GetString("Devise_Index_PanelMain_Symbole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Iso.
        /// </summary>
        public static string Devise_Index_PanelRight_IsoCode {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_IsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Iso.
        /// </summary>
        public static string Devise_Index_PanelRight_IsoCode_Placeholder {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_IsoCode_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Iso Nombre.
        /// </summary>
        public static string Devise_Index_PanelRight_IsoNombre {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_IsoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Iso Nombre.
        /// </summary>
        public static string Devise_Index_PanelRight_IsoNombre_Placeholder {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_IsoNombre_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string Devise_Index_PanelRight_Libelle {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string Devise_Index_PanelRight_Libelle_Placeholder {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_Libelle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbole.
        /// </summary>
        public static string Devise_Index_PanelRight_Symbole {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_Symbole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbole de la monnaie.
        /// </summary>
        public static string Devise_Index_PanelRight_Symbole_Placeholder {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_Symbole_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une devise.
        /// </summary>
        public static string Devise_Index_PanelRight_Titre_Ajouter {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_Titre_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier une Devise.
        /// </summary>
        public static string Devise_Index_PanelRight_Titre_Modifier {
            get {
                return ResourceManager.GetString("Devise_Index_PanelRight_Titre_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une Devise ....
        /// </summary>
        public static string Devise_Index_Rechercher_Placeholder {
            get {
                return ResourceManager.GetString("Devise_Index_Rechercher_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer Codes Devise.
        /// </summary>
        public static string Devise_Index_Titre {
            get {
                return ResourceManager.GetString("Devise_Index_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devises.
        /// </summary>
        public static string Devise_Index_TitreOnglet {
            get {
                return ResourceManager.GetString("Devise_Index_TitreOnglet", resourceCulture);
            }
        }
    }
}
