//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureRessourcesSpecifiquesCI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureRessourcesSpecifiquesCI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureRessourcesSpecifiquesCI", typeof(FeatureRessourcesSpecifiquesCI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Active {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Annuler {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour annuler et fermer.
        /// </summary>
        public static string RessourcesSpecifiquesCI_AnnulerFermer_Info {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_AnnulerFermer_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter au format Excel.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Bouton_ExportExcel {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Bouton_ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout déplier.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Bouton_ToutDeplier {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Bouton_ToutDeplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout replier.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Bouton_ToutReplier {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Bouton_ToutReplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_CI_SousTitre {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_CI_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Code {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une ressource spécifique CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Creation_Info {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Creation_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création Ressource spécifique CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_CreationTitre {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_CreationTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification Ressource spécifique CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_EditionTitre {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_EditionTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Enregistrer {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécifique CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_EstSpecifiqueCI {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_EstSpecifiqueCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Inactive {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner un CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Index_Selectionner_CI_Warning {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Index_Selectionner_CI_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Libelle {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer cette ressource spécifique ci ?.
        /// </summary>
        public static string RessourcesSpecifiquesCI_MessageSupprConfirmation {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_MessageSupprConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier la ressource spécifique CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Modification_Info {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Modification_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ressources spécifiques CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_NombreWarning {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_NombreWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune donnée trouvée.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Notification_AucuneDonnees {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Notification_AucuneDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référentiel des CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_ReferentielCI {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_ReferentielCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un CI....
        /// </summary>
        public static string RessourcesSpecifiquesCI_ReferentielCI_Placeholder {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_ReferentielCI_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une ressource....
        /// </summary>
        public static string RessourcesSpecifiquesCI_ReferentielRessource_Placeholder {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_ReferentielRessource_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer le référentiel.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Ressource_SousTitre {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Ressource_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource de rattachement.
        /// </summary>
        public static string RessourcesSpecifiquesCI_RessourceRattachement {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_RessourceRattachement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de supprimer cette Ressource car elle est liée à au moins un autre élément : commande(s), matériel(s), personnel(s) et/ou nature(s)..
        /// </summary>
        public static string RessourcesSpecifiquesCI_Suppression_Impossible {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Suppression_Impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la ressource spécifique CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Suppression_Info {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Suppression_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression Ressource spécifique CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_SuppressionTitre {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_SuppressionTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources spécifiques CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Titre {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources spécifiques CI.
        /// </summary>
        public static string RessourcesSpecifiquesCI_TitreOnglet {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_TitreOnglet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string RessourcesSpecifiquesCI_Valider {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCI_Valider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez-vous l&apos;exportation ?.
        /// </summary>
        public static string RessourcesSpecifiquesCl_Modal_ConfirmationExportation {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCl_Modal_ConfirmationExportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ Libelle est requis pour l&apos;ajout d&apos;une ressource spécifique CI..
        /// </summary>
        public static string RessourcesSpecifiquesCl_Modal_Erreur_Libelle_Vide {
            get {
                return ResourceManager.GetString("RessourcesSpecifiquesCl_Modal_Erreur_Libelle_Vide", resourceCulture);
            }
        }
    }
}
