//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FeatureClassificationSocietes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureClassificationSocietes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureClassificationSocietes", typeof(FeatureClassificationSocietes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une classification société.
        /// </summary>
        internal static string AddClass {
            get {
                return ResourceManager.GetString("AddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refermer le panneau.
        /// </summary>
        internal static string btn_ClosePanel {
            get {
                return ResourceManager.GetString("btn_ClosePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer et Nouveau.
        /// </summary>
        internal static string btn_Save_New {
            get {
                return ResourceManager.GetString("btn_Save_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de la classification société impossible : celle - ci est rattachée à au moins une société.
        /// </summary>
        internal static string DeleteActiveClass {
            get {
                return ResourceManager.GetString("DeleteActiveClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactivation de la classification société impossible : celle - ci est rattachée à au moins une société.
        /// </summary>
        internal static string DisableAssocieClass {
            get {
                return ResourceManager.GetString("DisableAssocieClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code*.
        /// </summary>
        internal static string inputCode_Title {
            get {
                return ResourceManager.GetString("inputCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier une classification société.
        /// </summary>
        internal static string ModifClass {
            get {
                return ResourceManager.GetString("ModifClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactivation de la classification société impossible : celle - ci est rattachée à au moins une société.
        /// </summary>
        internal static string msg_DesactivationClassification {
            get {
                return ResourceManager.GetString("msg_DesactivationClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de la classification société impossible : celle - ci est rattachée à au moins une société.
        /// </summary>
        internal static string msg_SuppressionClassification {
            get {
                return ResourceManager.GetString("msg_SuppressionClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une classification société.
        /// </summary>
        internal static string PlaceHolder_ClasseSociete {
            get {
                return ResourceManager.GetString("PlaceHolder_ClasseSociete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un Goupe ....
        /// </summary>
        internal static string PlaceHolder_GroupeSociete {
            get {
                return ResourceManager.GetString("PlaceHolder_GroupeSociete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 caractères max.
        /// </summary>
        internal static string PlaceHolder_InputCode {
            get {
                return ResourceManager.GetString("PlaceHolder_InputCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les champs marqués d&apos;un astérisque (*) sont obligatoires.
        /// </summary>
        internal static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de la classification société impossible : champ(s) requis.
        /// </summary>
        internal static string SocieteClassification_CreationImpossible {
            get {
                return ResourceManager.GetString("SocieteClassification_CreationImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifications Sociétés.
        /// </summary>
        internal static string SocieteClassification_Lookup_Title {
            get {
                return ResourceManager.GetString("SocieteClassification_Lookup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        internal static string Text_Libelle {
            get {
                return ResourceManager.GetString("Text_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les classifications sociétés.
        /// </summary>
        internal static string Title_ClassSoc {
            get {
                return ResourceManager.GetString("Title_ClassSoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe Sociétés .
        /// </summary>
        internal static string TitleSearch_Lookup_Groupe {
            get {
                return ResourceManager.GetString("TitleSearch_Lookup_Groupe", resourceCulture);
            }
        }
    }
}
