//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureRessourcesRecommandees {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureRessourcesRecommandees() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureRessourcesRecommandees", typeof(FeatureRessourcesRecommandees).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement.
        /// </summary>
        public static string RessourcesRecommandees_Etablissement {
            get {
                return ResourceManager.GetString("RessourcesRecommandees_Etablissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquer la sélection en &lt;br/&gt; &apos;Non Recommandée&apos;.
        /// </summary>
        public static string RessourcesRecommandees_Index_Ressource_Table_Marquer_NonRecommandee {
            get {
                return ResourceManager.GetString("RessourcesRecommandees_Index_Ressource_Table_Marquer_NonRecommandee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquer la sélection en &lt;br/&gt; &apos;Recommandée&apos;.
        /// </summary>
        public static string RessourcesRecommandees_Index_Ressource_Table_Marquer_Recommandee {
            get {
                return ResourceManager.GetString("RessourcesRecommandees_Index_Ressource_Table_Marquer_Recommandee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un établissement pour gérer les ressources recommandées.
        /// </summary>
        public static string RessourcesRecommandees_Message_Information {
            get {
                return ResourceManager.GetString("RessourcesRecommandees_Message_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche d&apos;un établissement....
        /// </summary>
        public static string RessourcesRecommandees_RechercheEtablissement {
            get {
                return ResourceManager.GetString("RessourcesRecommandees_RechercheEtablissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommandée.
        /// </summary>
        public static string RessourcesRecommandees_SwitchTitle {
            get {
                return ResourceManager.GetString("RessourcesRecommandees_SwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources Recommandées.
        /// </summary>
        public static string RessourcesRecommandees_TitreOnglet {
            get {
                return ResourceManager.GetString("RessourcesRecommandees_TitreOnglet", resourceCulture);
            }
        }
    }
}
