//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureCI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureCI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureCI", typeof(FeatureCI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’astreinte ne peut pas être mise à jour car le pointage est verrouillé.
        /// </summary>
        public static string CI_Affectation_Astreintes_Verouiller {
            get {
                return ResourceManager.GetString("CI_Affectation_Astreintes_Verouiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le personnel ne peut être supprimé, car il a effectué des pointages sur ce CI.
        /// </summary>
        public static string CI_Affectation_Delete_Affectation_Message {
            get {
                return ResourceManager.GetString("CI_Affectation_Delete_Affectation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La devise sélectionnée est déjà la devise de référence..
        /// </summary>
        public static string CI_Controller_ErrorMetier_DeviseDejaReference {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_DeviseDejaReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La devise sélectionnée est déjà une devise secondaire..
        /// </summary>
        public static string CI_Controller_ErrorMetier_DeviseDejaSecondaire {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_DeviseDejaSecondaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas sélectionner deux fois la même devise.
        /// </summary>
        public static string CI_Controller_ErrorMetier_DoubleSelectionDevise {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_DoubleSelectionDevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas les droits suffisants pour accéder à cet élément.
        /// </summary>
        public static string CI_Controller_ErrorMetier_DroitsInsuffisants {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_DroitsInsuffisants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La société est déjà présente dans la liste des partenaires.
        /// </summary>
        public static string CI_Controller_ErrorMetier_DuplicateSociete {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_DuplicateSociete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;avoir plusieurs sociétés Mandataire ou Gérante.
        /// </summary>
        public static string CI_Controller_ErrorMetier_DuplicateTypeParticipation {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_DuplicateTypeParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre maximum de devises atteint.
        /// </summary>
        public static string CI_Controller_ErrorMetier_NbrMaxDevise {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_NbrMaxDevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement impossible : dans le paramétrages des carburants, toutes les valeurs du champ Prix doivent être renseignées..
        /// </summary>
        public static string CI_Controller_ErrorMetier_PrixObligatoire {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_PrixObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une quote-part ne peut être négative..
        /// </summary>
        public static string CI_Controller_ErrorMetier_QuotePart {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_QuotePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le total de quote-parts doit être de 100%.
        /// </summary>
        public static string CI_Controller_ErrorMetier_QuotePartTotal {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_QuotePartTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Redirection vers les CI....
        /// </summary>
        public static string CI_Controller_ErrorMetier_RedirectionCI {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_RedirectionCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise de référence requise.
        /// </summary>
        public static string CI_Controller_ErrorMetier_RequiredReferenceDevise {
            get {
                return ResourceManager.GetString("CI_Controller_ErrorMetier_RequiredReferenceDevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référence.
        /// </summary>
        public static string CI_Controller_Reference {
            get {
                return ResourceManager.GetString("CI_Controller_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondaires.
        /// </summary>
        public static string CI_Controller_Secondaires {
            get {
                return ResourceManager.GetString("CI_Controller_Secondaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de désaffecter une astreinte sur un pointage verrouillé.
        /// </summary>
        public static string CI_Desaffectation_Astreintes_Verouiller {
            get {
                return ResourceManager.GetString("CI_Desaffectation_Astreintes_Verouiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer la prise en compte du carburant dans l&apos;exploitation.
        /// </summary>
        public static string CI_Detail_Carburant_ActiverCarburant {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_ActiverCarburant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une devise.
        /// </summary>
        public static string CI_Detail_Carburant_SelectionDevise {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_SelectionDevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage de la consommation des ressources matérielles.
        /// </summary>
        public static string CI_Detail_Carburant_SousTitre_ParametrageConsommationRessource {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_SousTitre_ParametrageConsommationRessource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage du prix des carburants.
        /// </summary>
        public static string CI_Detail_Carburant_SousTitre_ParametragePrixCarburant {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_SousTitre_ParametragePrixCarburant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string CI_Detail_Carburant_TableCarburant_Action {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableCarburant_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clôturé.
        /// </summary>
        public static string CI_Detail_Carburant_TableCarburant_Cloture {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableCarburant_Cloture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un carburant ne peut avoir qu&apos;un prix par période et par devise..
        /// </summary>
        public static string CI_Detail_Carburant_TableCarburant_ErrorPeriodeUnique {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableCarburant_ErrorPeriodeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 décimales maximum..
        /// </summary>
        public static string CI_Detail_Carburant_TableCarburant_ErrorPrixDecimal {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableCarburant_ErrorPrixDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix obligatoire..
        /// </summary>
        public static string CI_Detail_Carburant_TableCarburant_ErrorPrixObligatoire {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableCarburant_ErrorPrixObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix doit être positif..
        /// </summary>
        public static string CI_Detail_Carburant_TableCarburant_ErrorPrixPositif {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableCarburant_ErrorPrixPositif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Période d&apos;application (à partir de).
        /// </summary>
        public static string CI_Detail_Carburant_TableCarburant_PeriodeApplication {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableCarburant_PeriodeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string CI_Detail_Carburant_TableCarburant_Prix {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableCarburant_Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carburant.
        /// </summary>
        public static string CI_Detail_Carburant_TableRessource_Carburant {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableRessource_Carburant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CI_Detail_Carburant_TableRessource_Code {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableRessource_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consommation CI.
        /// </summary>
        public static string CI_Detail_Carburant_TableRessource_ConsommationCI {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableRessource_ConsommationCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consommation par défaut.
        /// </summary>
        public static string CI_Detail_Carburant_TableRessource_ConsommationDefaut {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableRessource_ConsommationDefaut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 décimales maximum..
        /// </summary>
        public static string CI_Detail_Carburant_TableRessource_ErrorConsommationDecimal {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableRessource_ErrorConsommationDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consommation doit être positive..
        /// </summary>
        public static string CI_Detail_Carburant_TableRessource_ErrorConsommationPositive {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableRessource_ErrorConsommationPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string CI_Detail_Carburant_TableRessource_Libelle {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_TableRessource_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage du carburant.
        /// </summary>
        public static string CI_Detail_Carburant_Titre {
            get {
                return ResourceManager.GetString("CI_Detail_Carburant_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code / Libellé.
        /// </summary>
        public static string CI_Detail_CodeLibelle {
            get {
                return ResourceManager.GetString("CI_Detail_CodeLibelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier l&apos;adresse de facturation.
        /// </summary>
        public static string CI_Detail_Commande_CopierFacturation {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_CopierFacturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string CI_Detail_Commande_Facturation_Adresse {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Facturation_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string CI_Detail_Commande_Facturation_Adresse_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Facturation_Adresse_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string CI_Detail_Commande_Facturation_CodePostal {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Facturation_CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string CI_Detail_Commande_Facturation_CodePostal_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Facturation_CodePostal_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string CI_Detail_Commande_Facturation_Pays {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Facturation_Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string CI_Detail_Commande_Facturation_Pays_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Facturation_Pays_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string CI_Detail_Commande_Facturation_Ville {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Facturation_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string CI_Detail_Commande_Facturation_Ville_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Facturation_Ville_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chantier/Plateforme.
        /// </summary>
        public static string CI_Detail_Commande_Factutation_Choix1 {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Factutation_Choix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement.
        /// </summary>
        public static string CI_Detail_Commande_Factutation_Choix2 {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Factutation_Choix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_Adresse {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_Adresse_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_Adresse_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_CodePostal {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_CodePostal_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_CodePostal_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entête.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_Entete {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_Entete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entête.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_Entete_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_Entete_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_Pays {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_Pays_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_Pays_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_Ville {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string CI_Detail_Commande_Livraison_Ville_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Livraison_Ville_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de facturation des commandes.
        /// </summary>
        public static string CI_Detail_Commande_SousTitre_Facturation {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_SousTitre_Facturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de livraison des commandes.
        /// </summary>
        public static string CI_Detail_Commande_SousTitre_Livraison {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_SousTitre_Livraison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage du module commande.
        /// </summary>
        public static string CI_Detail_Commande_Titre {
            get {
                return ResourceManager.GetString("CI_Detail_Commande_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CI_Detail_Description {
            get {
                return ResourceManager.GetString("CI_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres devises.
        /// </summary>
        public static string CI_Detail_Devise_SousTitre_AutresDevises {
            get {
                return ResourceManager.GetString("CI_Detail_Devise_SousTitre_AutresDevises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise de référence.
        /// </summary>
        public static string CI_Detail_Devise_SousTitre_DeviseRef {
            get {
                return ResourceManager.GetString("CI_Detail_Devise_SousTitre_DeviseRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une devise.
        /// </summary>
        public static string CI_Detail_Devise_TableDevise_AjouterDevise {
            get {
                return ResourceManager.GetString("CI_Detail_Devise_TableDevise_AjouterDevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise.
        /// </summary>
        public static string CI_Detail_Devise_TableDevise_Devise {
            get {
                return ResourceManager.GetString("CI_Detail_Devise_TableDevise_Devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la devise secondaire.
        /// </summary>
        public static string CI_Detail_Devise_TableDevise_SupprimerDevise {
            get {
                return ResourceManager.GetString("CI_Detail_Devise_TableDevise_SupprimerDevise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage des devises.
        /// </summary>
        public static string CI_Detail_Devise_Titre {
            get {
                return ResourceManager.GetString("CI_Detail_Devise_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte Interne Sep.
        /// </summary>
        public static string CI_Detail_General_CompteInterneSep {
            get {
                return ResourceManager.GetString("CI_Detail_General_CompteInterneSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fermeture.
        /// </summary>
        public static string CI_Detail_General_DateFermeture {
            get {
                return ResourceManager.GetString("CI_Detail_General_DateFermeture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fermeture.
        /// </summary>
        public static string CI_Detail_General_DateFermeture_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_General_DateFermeture_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;ouverture.
        /// </summary>
        public static string CI_Detail_General_DateOuverture {
            get {
                return ResourceManager.GetString("CI_Detail_General_DateOuverture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de fermeture doit être postérieure à la date d&apos;ouverture.
        /// </summary>
        public static string CI_Detail_General_DateOuverture_ErrorLogique {
            get {
                return ResourceManager.GetString("CI_Detail_General_DateOuverture_ErrorLogique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;ouverture.
        /// </summary>
        public static string CI_Detail_General_DateOuverture_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_General_DateOuverture_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise du marché.
        /// </summary>
        public static string CI_Detail_General_DeviseMontantHT {
            get {
                return ResourceManager.GetString("CI_Detail_General_DeviseMontantHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée du chantier (mois).
        /// </summary>
        public static string CI_Detail_General_DureeChantier {
            get {
                return ResourceManager.GetString("CI_Detail_General_DureeChantier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre entier, pas de négatif.
        /// </summary>
        public static string CI_Detail_General_ErrorDureeChantier {
            get {
                return ResourceManager.GetString("CI_Detail_General_ErrorDureeChantier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement comptable.
        /// </summary>
        public static string CI_Detail_General_EtablissementComptable {
            get {
                return ResourceManager.GetString("CI_Detail_General_EtablissementComptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement comptable.
        /// </summary>
        public static string CI_Detail_General_EtablissementComptable_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_General_EtablissementComptable_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taux de frais généraux (%).
        /// </summary>
        public static string CI_Detail_General_FraisGeneraux {
            get {
                return ResourceManager.GetString("CI_Detail_General_FraisGeneraux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas plus de 2 décimales, pas de négatif et limité à 100.
        /// </summary>
        public static string CI_Detail_General_FraisGeneraux_ErrorFormat {
            get {
                return ResourceManager.GetString("CI_Detail_General_FraisGeneraux_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frais généraux.
        /// </summary>
        public static string CI_Detail_General_FraisGeneraux_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_General_FraisGeneraux_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horaires.
        /// </summary>
        public static string CI_Detail_General_Horaires {
            get {
                return ResourceManager.GetString("CI_Detail_General_Horaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le format horaire doit être HH:MM.
        /// </summary>
        public static string CI_Detail_General_Horaires_ErrorFormat {
            get {
                return ResourceManager.GetString("CI_Detail_General_Horaires_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La première tranche Horaires est obligatoire..
        /// </summary>
        public static string CI_Detail_General_Horaires_PremiereTrancheManquante {
            get {
                return ResourceManager.GetString("CI_Detail_General_Horaires_PremiereTrancheManquante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ou les tranches horaires ne sont pas saisies correctement.
        /// </summary>
        public static string CI_Detail_General_Horaires_TrancheInvalide {
            get {
                return ResourceManager.GetString("CI_Detail_General_Horaires_TrancheInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé CI.
        /// </summary>
        public static string CI_Detail_General_Libelle {
            get {
                return ResourceManager.GetString("CI_Detail_General_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé CI.
        /// </summary>
        public static string CI_Detail_General_Libelle_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_General_Libelle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant du marché HT.
        /// </summary>
        public static string CI_Detail_General_MontantHT {
            get {
                return ResourceManager.GetString("CI_Detail_General_MontantHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas plus de 2 décimales, pas de négatif.
        /// </summary>
        public static string CI_Detail_General_MontantHT_ErrorFormat {
            get {
                return ResourceManager.GetString("CI_Detail_General_MontantHT_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectif heures d&apos;insertion du chantier (heures).
        /// </summary>
        public static string CI_Detail_General_ObjectifHeuresInsertion {
            get {
                return ResourceManager.GetString("CI_Detail_General_ObjectifHeuresInsertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectif heures d&apos;insertion du chantier (heures).
        /// </summary>
        public static string CI_Detail_General_ObjectifHeuresInsertion_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_General_ObjectifHeuresInsertion_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable administratif.
        /// </summary>
        public static string CI_Detail_General_ResponsableAdministratif {
            get {
                return ResourceManager.GetString("CI_Detail_General_ResponsableAdministratif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable chantier.
        /// </summary>
        public static string CI_Detail_General_ResponsableChantier {
            get {
                return ResourceManager.GetString("CI_Detail_General_ResponsableChantier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP.
        /// </summary>
        public static string CI_Detail_General_SEP {
            get {
                return ResourceManager.GetString("CI_Detail_General_SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        public static string CI_Detail_General_Societe {
            get {
                return ResourceManager.GetString("CI_Detail_General_Societe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        public static string CI_Detail_General_Societe_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_General_Societe_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taux horaire moyen.
        /// </summary>
        public static string CI_Detail_General_TauxHoraire {
            get {
                return ResourceManager.GetString("CI_Detail_General_TauxHoraire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas plus de 2 décimales, pas de négatif et limité à 100.
        /// </summary>
        public static string CI_Detail_General_TauxHoraire_ErrorFormat {
            get {
                return ResourceManager.GetString("CI_Detail_General_TauxHoraire_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taux horaire.
        /// </summary>
        public static string CI_Detail_General_TauxHoraire_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_General_TauxHoraire_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage général.
        /// </summary>
        public static string CI_Detail_General_Titre {
            get {
                return ResourceManager.GetString("CI_Detail_General_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string CI_Detail_General_TypeAutre {
            get {
                return ResourceManager.GetString("CI_Detail_General_TypeAutre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chantier.
        /// </summary>
        public static string CI_Detail_General_TypeChantier {
            get {
                return ResourceManager.GetString("CI_Detail_General_TypeChantier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type CI.
        /// </summary>
        public static string CI_Detail_General_TypeCI {
            get {
                return ResourceManager.GetString("CI_Detail_General_TypeCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frais Généraux.
        /// </summary>
        public static string CI_Detail_General_TypeFraisGeneraux {
            get {
                return ResourceManager.GetString("CI_Detail_General_TypeFraisGeneraux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériel.
        /// </summary>
        public static string CI_Detail_General_TypeMateriel {
            get {
                return ResourceManager.GetString("CI_Detail_General_TypeMateriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 1.
        /// </summary>
        public static string CI_Detail_Paie_Adresse {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 1.
        /// </summary>
        public static string CI_Detail_Paie_Adresse_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Adresse_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 2.
        /// </summary>
        public static string CI_Detail_Paie_Adresse_Placeholder2 {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Adresse_Placeholder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 3.
        /// </summary>
        public static string CI_Detail_Paie_Adresse_Placeholder3 {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Adresse_Placeholder3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 2.
        /// </summary>
        public static string CI_Detail_Paie_Adresse2 {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Adresse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse 3.
        /// </summary>
        public static string CI_Detail_Paie_Adresse3 {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Adresse3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string CI_Detail_Paie_CodePostal {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string CI_Detail_Paie_CodePostal_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_CodePostal_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string CI_Detail_Paie_Latitude {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string CI_Detail_Paie_Latitude_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Latitude_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation affaire.
        /// </summary>
        public static string CI_Detail_Paie_LocalisationAffaire {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_LocalisationAffaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string CI_Detail_Paie_Longitude {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string CI_Detail_Paie_Longitude_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Longitude_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string CI_Detail_Paie_Pays {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string CI_Detail_Paie_Pays_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Pays_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrer la majoration des heures pointées.
        /// </summary>
        public static string CI_Detail_Paie_SousTitre_Majoration {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_SousTitre_Majoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrer les primes.
        /// </summary>
        public static string CI_Detail_Paie_SousTitre_Prime {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_SousTitre_Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affecter.
        /// </summary>
        public static string CI_Detail_Paie_TableMajoration_Entete_Affecter {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TableMajoration_Entete_Affecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CI_Detail_Paie_TableMajoration_Entete_Code {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TableMajoration_Entete_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string CI_Detail_Paie_TableMajoration_Entete_Libelle {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TableMajoration_Entete_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string CI_Detail_Paie_TableMajoration_Entete_Public {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TableMajoration_Entete_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affecter.
        /// </summary>
        public static string CI_Detail_Paie_TablePrime_Entete_Affecter {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TablePrime_Entete_Affecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CI_Detail_Paie_TablePrime_Entete_Code {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TablePrime_Entete_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string CI_Detail_Paie_TablePrime_Entete_Libelle {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TablePrime_Entete_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string CI_Detail_Paie_TablePrime_Entete_Public {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TablePrime_Entete_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        public static string CI_Detail_Paie_TablePrime_Entete_Societe {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_TablePrime_Entete_Societe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage de la paye.
        /// </summary>
        public static string CI_Detail_Paie_Titre {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string CI_Detail_Paie_Ville {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string CI_Detail_Paie_Ville_Placeholder {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_Ville_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Modifiable.
        /// </summary>
        public static string CI_Detail_Paie_ZoneModifiable {
            get {
                return ResourceManager.GetString("CI_Detail_Paie_ZoneModifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la liste des CI.
        /// </summary>
        public static string CI_Detail_RetourListeCI {
            get {
                return ResourceManager.GetString("CI_Detail_RetourListeCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        public static string CI_Detail_Societe {
            get {
                return ResourceManager.GetString("CI_Detail_Societe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une société partenaire.
        /// </summary>
        public static string CI_Detail_Societe_Table_Entete_AjouterSociete {
            get {
                return ResourceManager.GetString("CI_Detail_Societe_Table_Entete_AjouterSociete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote-part.
        /// </summary>
        public static string CI_Detail_Societe_Table_Entete_QuotePart {
            get {
                return ResourceManager.GetString("CI_Detail_Societe_Table_Entete_QuotePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        public static string CI_Detail_Societe_Table_Entete_Societe {
            get {
                return ResourceManager.GetString("CI_Detail_Societe_Table_Entete_Societe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type participation.
        /// </summary>
        public static string CI_Detail_Societe_Table_Entete_TypeParticipation {
            get {
                return ResourceManager.GetString("CI_Detail_Societe_Table_Entete_TypeParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la société partenaire.
        /// </summary>
        public static string CI_Detail_Societe_Table_Supprimer {
            get {
                return ResourceManager.GetString("CI_Detail_Societe_Table_Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociétés partenaires.
        /// </summary>
        public static string CI_Detail_Societe_Titre {
            get {
                return ResourceManager.GetString("CI_Detail_Societe_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astreinte.
        /// </summary>
        public static string CI_Detail_Team_Astreinte {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Astreinte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour ajouter ce personnel dans mon équipe favorite.
        /// </summary>
        public static string CI_Detail_Team_Click_To_Add_To_FavoriteTeam {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Click_To_Add_To_FavoriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour gérer les astreintes au niveau du CI.
        /// </summary>
        public static string CI_Detail_Team_Click_To_Manage_Astreints {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Click_To_Manage_Astreints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour supprimer ce personnel dans mon équipe favorite.
        /// </summary>
        public static string CI_Detail_Team_Click_To_Remove_From_FavoriteTeam {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Click_To_Remove_From_FavoriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour ne plus gérer les astreintes.
        /// </summary>
        public static string CI_Detail_Team_Click_To_Stop_Managing_Astreints {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Click_To_Stop_Managing_Astreints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous affecter tous les membres de votre équipe favorite à ce centre d&apos;imputation ?.
        /// </summary>
        public static string CI_Detail_Team_Confirm_Import_All_Team_Members {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Confirm_Import_All_Team_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;affectation du personnel .
        /// </summary>
        public static string CI_Detail_Team_Error_Affecation {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Error_Affecation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activer les restrictions de pointage.
        /// </summary>
        public static string CI_Detail_Team_Handle_Pointage_Restrictions {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Handle_Pointage_Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer équipe.
        /// </summary>
        public static string CI_Detail_Team_Import {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les astreintes.
        /// </summary>
        public static string CI_Detail_Team_ManageAstreints {
            get {
                return ResourceManager.GetString("CI_Detail_Team_ManageAstreints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricule.
        /// </summary>
        public static string CI_Detail_Team_Matricul {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Matricul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La gestion des astreintes s&apos;applique uniquement pour les CI du type \&quot;Affaire\&quot;.
        /// </summary>
        public static string CI_Detail_Team_Notification_Managing_Astreintes_IsOnlyFor_Affaire_Type {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Notification_Managing_Astreintes_IsOnlyFor_Affaire_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce personnel est déja affecté à ce centre d&apos;imputation.
        /// </summary>
        public static string CI_Detail_Team_Notification_Personnel_Existant {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Notification_Personnel_Existant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        public static string CI_Detail_Team_Personnel {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce personnel a une délégation sur l&apos;affaire.
        /// </summary>
        public static string CI_Detail_Team_Personnel_Has_Delegation {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Personnel_Has_Delegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une personne.
        /// </summary>
        public static string CI_Detail_Team_Search_PlaceHolder {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Search_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référentiel des Personnels.
        /// </summary>
        public static string CI_Detail_Team_Select_Personnel {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Select_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout afficher.
        /// </summary>
        public static string CI_Detail_Team_ShowAll {
            get {
                return ResourceManager.GetString("CI_Detail_Team_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string CI_Detail_Team_Status {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage des équipes et affectations.
        /// </summary>
        public static string CI_Detail_Team_Title {
            get {
                return ResourceManager.GetString("CI_Detail_Team_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sans Astreinte.
        /// </summary>
        public static string CI_Detail_Team_WithoutAstreinte {
            get {
                return ResourceManager.GetString("CI_Detail_Team_WithoutAstreinte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration du Centre d&apos;Imputation.
        /// </summary>
        public static string CI_Detail_Titre {
            get {
                return ResourceManager.GetString("CI_Detail_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail CI.
        /// </summary>
        public static string CI_Detail_TitreOnglet {
            get {
                return ResourceManager.GetString("CI_Detail_TitreOnglet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez-vous la désactivation des astreintes sur ce centre d&apos;imputation ? toutes les astreintes seront annulées..
        /// </summary>
        public static string CI_Details_Team_Confirm_Desactivate_Managing_Astreintes {
            get {
                return ResourceManager.GetString("CI_Details_Team_Confirm_Desactivate_Managing_Astreintes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’équipe favorite ne peut contenir que des ouvriers..
        /// </summary>
        public static string CI_Details_Team_Only_Workers_Can_Be_In_Team {
            get {
                return ResourceManager.GetString("CI_Details_Team_Only_Workers_Can_Be_In_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrier.
        /// </summary>
        public static string CI_Details_Team_Worker {
            get {
                return ResourceManager.GetString("CI_Details_Team_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ouvriers.
        /// </summary>
        public static string CI_Details_Team_Workers {
            get {
                return ResourceManager.GetString("CI_Details_Team_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des CI.
        /// </summary>
        public static string CI_Index_SousTitre_ListeCI {
            get {
                return ResourceManager.GetString("CI_Index_SousTitre_ListeCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre d&apos;imputation est une SEP.
        /// </summary>
        public static string CI_Index_Table_SelectionIconeSEP {
            get {
                return ResourceManager.GetString("CI_Index_Table_SelectionIconeSEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour accéder au détail du centre d&apos;imputation #.
        /// </summary>
        public static string CI_Index_Table_SelectionLigne {
            get {
                return ResourceManager.GetString("CI_Index_Table_SelectionLigne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code CI.
        /// </summary>
        public static string CI_Index_TableCI_Entete_CodeCI {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_CodeCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Etablissement.
        /// </summary>
        public static string CI_Index_TableCI_Entete_CodeEtab {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_CodeEtab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fermeture.
        /// </summary>
        public static string CI_Index_TableCI_Entete_DateFermeture {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_DateFermeture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;ouverture.
        /// </summary>
        public static string CI_Index_TableCI_Entete_DateOuverture {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_DateOuverture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé CI.
        /// </summary>
        public static string CI_Index_TableCI_Entete_LibelleCI {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_LibelleCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé Etablissement.
        /// </summary>
        public static string CI_Index_TableCI_Entete_LibelleEtab {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_LibelleEtab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé Société.
        /// </summary>
        public static string CI_Index_TableCI_Entete_LibelleSoc {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_LibelleSoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP.
        /// </summary>
        public static string CI_Index_TableCI_Entete_SEP {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CI_Index_TableCI_Entete_TypeCI {
            get {
                return ResourceManager.GetString("CI_Index_TableCI_Entete_TypeCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les CI.
        /// </summary>
        public static string CI_Index_Titre {
            get {
                return ResourceManager.GetString("CI_Index_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre d&apos;Imputation.
        /// </summary>
        public static string CI_Index_TitreOnglet {
            get {
                return ResourceManager.GetString("CI_Index_TitreOnglet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres informations....
        /// </summary>
        public static string CI_Partial_Team_Personnel_Filter_Autre_Information_Placeholder {
            get {
                return ResourceManager.GetString("CI_Partial_Team_Personnel_Filter_Autre_Information_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du personnel....
        /// </summary>
        public static string CI_Partial_Team_Personnel_Nom_Placeholder {
            get {
                return ResourceManager.GetString("CI_Partial_Team_Personnel_Nom_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom du personnel....
        /// </summary>
        public static string CI_Partial_Team_Personnel_Prenom_Placeholder {
            get {
                return ResourceManager.GetString("CI_Partial_Team_Personnel_Prenom_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affaire.
        /// </summary>
        public static string CI_Search_CIType_Affaire {
            get {
                return ResourceManager.GetString("CI_Search_CIType_Affaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etude.
        /// </summary>
        public static string CI_Search_CIType_Etude {
            get {
                return ResourceManager.GetString("CI_Search_CIType_Etude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string CI_Search_CIType_Section {
            get {
                return ResourceManager.GetString("CI_Search_CIType_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fermeture avant le :.
        /// </summary>
        public static string CI_Search_DateFermeture_Placeholder {
            get {
                return ResourceManager.GetString("CI_Search_DateFermeture_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;ouverture après le :.
        /// </summary>
        public static string CI_Search_DateOuverture_Placeholder {
            get {
                return ResourceManager.GetString("CI_Search_DateOuverture_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour enregistrer les critères de recherche comme favori.
        /// </summary>
        public static string CI_Search_Favori_Tooltip {
            get {
                return ResourceManager.GetString("CI_Search_Favori_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclure les CI clôturés.
        /// </summary>
        public static string CI_Search_InclureClotures {
            get {
                return ResourceManager.GetString("CI_Search_InclureClotures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seulement les SEP.
        /// </summary>
        public static string CI_Search_SeulementSEP {
            get {
                return ResourceManager.GetString("CI_Search_SeulementSEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche CI.
        /// </summary>
        public static string CI_Search_TitreOnglet {
            get {
                return ResourceManager.GetString("CI_Search_TitreOnglet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI Cloturés.
        /// </summary>
        public static string CI_Search_Tuile_ClotureOk {
            get {
                return ResourceManager.GetString("CI_Search_Tuile_ClotureOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Fermeture &lt;=.
        /// </summary>
        public static string CI_Search_Tuile_DateFermeture {
            get {
                return ResourceManager.GetString("CI_Search_Tuile_DateFermeture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Ouverture &gt;=.
        /// </summary>
        public static string CI_Search_Tuile_DateOuverture {
            get {
                return ResourceManager.GetString("CI_Search_Tuile_DateOuverture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP.
        /// </summary>
        public static string CI_Search_Tuile_SEP {
            get {
                return ResourceManager.GetString("CI_Search_Tuile_SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La gestion d&apos;astreinte ne peut pas être désactivée car il existe au moins une astreinte d&apos;affectée.
        /// </summary>
        public static string Gestion_CI_Disable_Atreintes_Warning {
            get {
                return ResourceManager.GetString("Gestion_CI_Disable_Atreintes_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les valeurs admises sont ‘0.5’ et ‘1’.
        /// </summary>
        public static string Pointage_IAC_AbsenceSaisie_Error {
            get {
                return ResourceManager.GetString("Pointage_IAC_AbsenceSaisie_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les valeurs admises sont ‘0.25’, ‘0.5’, ‘0.75’ et ‘1’.
        /// </summary>
        public static string Pointage_IAC_TacheSaisie_Error {
            get {
                return ResourceManager.GetString("Pointage_IAC_TacheSaisie_Error", resourceCulture);
            }
        }
    }
}
