//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureCommandeEnergie {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureCommandeEnergie() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureCommandeEnergie", typeof(FeatureCommandeEnergie).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;une ligne.
        /// </summary>
        public static string Bouton_Ajout_Ligne {
            get {
                return ResourceManager.GetString("Bouton_Ajout_Ligne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle commande Energies.
        /// </summary>
        public static string Bouton_Nouvelle_Commande_Energie {
            get {
                return ResourceManager.GetString("Bouton_Nouvelle_Commande_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner à la liste des commandes.
        /// </summary>
        public static string Bouton_Retour_Liste_Commande_Energie {
            get {
                return ResourceManager.GetString("Bouton_Retour_Liste_Commande_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour retourner à la liste des commandes.
        /// </summary>
        public static string Bouton_Retour_Liste_Commande_Energie_Tooltip {
            get {
                return ResourceManager.GetString("Bouton_Retour_Liste_Commande_Energie_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider la commande d&apos;énergies.
        /// </summary>
        public static string Bouton_Valider_Commande_Energie {
            get {
                return ResourceManager.GetString("Bouton_Valider_Commande_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour valider la commande énergie.
        /// </summary>
        public static string Bouton_Valider_Commande_Energie_Tooltip {
            get {
                return ResourceManager.GetString("Bouton_Valider_Commande_Energie_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer la commande énergie ?.
        /// </summary>
        public static string Confirmation_Suppression_Commande_Energie {
            get {
                return ResourceManager.GetString("Confirmation_Suppression_Commande_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entête de la commande.
        /// </summary>
        public static string Entete_Commande_Energie {
            get {
                return ResourceManager.GetString("Entete_Commande_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barème €.
        /// </summary>
        public static string Libelle_Bareme {
            get {
                return ResourceManager.GetString("Libelle_Bareme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chantier SEP.
        /// </summary>
        public static string Libelle_Chantier_SEP {
            get {
                return ResourceManager.GetString("Libelle_Chantier_SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire.
        /// </summary>
        public static string Libelle_Commentaire {
            get {
                return ResourceManager.GetString("Libelle_Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;émission.
        /// </summary>
        public static string Libelle_Date_Emission {
            get {
                return ResourceManager.GetString("Libelle_Date_Emission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désignation.
        /// </summary>
        public static string Libelle_Designation {
            get {
                return ResourceManager.GetString("Libelle_Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur partenaire.
        /// </summary>
        public static string Libelle_Fournisseur_Partenaire {
            get {
                return ResourceManager.GetString("Libelle_Fournisseur_Partenaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant énergie HT €.
        /// </summary>
        public static string Libelle_Montant_Energie {
            get {
                return ResourceManager.GetString("Libelle_Montant_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant valorisé €.
        /// </summary>
        public static string Libelle_Montant_Valorise {
            get {
                return ResourceManager.GetString("Libelle_Montant_Valorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro commande.
        /// </summary>
        public static string Libelle_Numero_Commande {
            get {
                return ResourceManager.GetString("Libelle_Numero_Commande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PU HT ajusté €.
        /// </summary>
        public static string Libelle_PUHT_Ajuste {
            get {
                return ResourceManager.GetString("Libelle_PUHT_Ajuste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité ajustée.
        /// </summary>
        public static string Libelle_Quantite_Ajustee {
            get {
                return ResourceManager.GetString("Libelle_Quantite_Ajustee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité convertie.
        /// </summary>
        public static string Libelle_Quantite_Convertie {
            get {
                return ResourceManager.GetString("Libelle_Quantite_Convertie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité pointée.
        /// </summary>
        public static string Libelle_Quantite_Pointee {
            get {
                return ResourceManager.GetString("Libelle_Quantite_Pointee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité barème.
        /// </summary>
        public static string Libelle_Unite_Bareme {
            get {
                return ResourceManager.GetString("Libelle_Unite_Bareme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité pointage.
        /// </summary>
        public static string Libelle_Unite_Pointage {
            get {
                return ResourceManager.GetString("Libelle_Unite_Pointage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Ci est obligatoire.
        /// </summary>
        public static string Notification_Ci_Obligatoire {
            get {
                return ResourceManager.GetString("Notification_Ci_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande énergie n&apos;a pas été trouvée.
        /// </summary>
        public static string Notification_Commande_Energie_Non_Trouvee {
            get {
                return ResourceManager.GetString("Notification_Commande_Energie_Non_Trouvee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de la validation.
        /// </summary>
        public static string Notification_Echec_Validation {
            get {
                return ResourceManager.GetString("Notification_Echec_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur éligible pour ce code CI.
        /// </summary>
        public static string Notification_Fournisseur_Eligible {
            get {
                return ResourceManager.GetString("Notification_Fournisseur_Eligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Fournisseur est obligatoire.
        /// </summary>
        public static string Notification_Fournisseur_Obligatoire {
            get {
                return ResourceManager.GetString("Notification_Fournisseur_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le numéro de commande est obligatoire.
        /// </summary>
        public static string Notification_Numero_Obligatoire {
            get {
                return ResourceManager.GetString("Notification_Numero_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La période est obligatoire.
        /// </summary>
        public static string Notification_Periode_Obligatoire {
            get {
                return ResourceManager.GetString("Notification_Periode_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préchargement de la commande réussi.
        /// </summary>
        public static string Notification_Prechargement_Succes {
            get {
                return ResourceManager.GetString("Notification_Prechargement_Succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreurs de saisie détectées : veuillez consulter la liste des erreurs à l&apos;aide de l&apos;icône d&apos;erreur..
        /// </summary>
        public static string Notification_Saisie_Error {
            get {
                return ResourceManager.GetString("Notification_Saisie_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code &apos;{0}&apos; du type d&apos;énergie n&apos;est pas géré..
        /// </summary>
        public static string Notification_Type_Energie_Non_Gere {
            get {
                return ResourceManager.GetString("Notification_Type_Energie_Non_Gere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type d&apos;énergie est obligatoire.
        /// </summary>
        public static string Notification_Type_Energie_Obligatoire {
            get {
                return ResourceManager.GetString("Notification_Type_Energie_Obligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro.
        /// </summary>
        public static string Numero_Commande_Energie {
            get {
                return ResourceManager.GetString("Numero_Commande_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande d&apos;Energies.
        /// </summary>
        public static string Titre_Commande_Energie {
            get {
                return ResourceManager.GetString("Titre_Commande_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lignes de commande supplémentaires.
        /// </summary>
        public static string Titre_Lignes_Supplementaires {
            get {
                return ResourceManager.GetString("Titre_Lignes_Supplementaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointages et ajustements.
        /// </summary>
        public static string Titre_Pointage_Ajustement {
            get {
                return ResourceManager.GetString("Titre_Pointage_Ajustement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préparation des commandes d&apos;Energies.
        /// </summary>
        public static string Titre_Preparation_Commande_Energie {
            get {
                return ResourceManager.GetString("Titre_Preparation_Commande_Energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Energie.
        /// </summary>
        public static string Type_Energie_Commande_Energie {
            get {
                return ResourceManager.GetString("Type_Energie_Commande_Energie", resourceCulture);
            }
        }
    }
}
