//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeaturePermission {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeaturePermission() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeaturePermission", typeof(FeaturePermission).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu.
        /// </summary>
        public static string AffichageMenuAreasPointageViewsRapportDetail {
            get {
                return ResourceManager.GetString("AffichageMenuAreasPointageViewsRapportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu du rapport ..
        /// </summary>
        public static string AffichageMenuAreasPointageViewsRapportIndex {
            get {
                return ResourceManager.GetString("AffichageMenuAreasPointageViewsRapportIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu devise.
        /// </summary>
        public static string AffichageMenuAreasReferentialViewsDeviseIndex {
            get {
                return ResourceManager.GetString("AffichageMenuAreasReferentialViewsDeviseIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu le menu des logs d&apos;authentification..
        /// </summary>
        public static string AffichageMenuAuthentificationLogIndex {
            get {
                return ResourceManager.GetString("AffichageMenuAuthentificationLogIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu du budget.
        /// </summary>
        public static string AffichageMenuBudgetIndex {
            get {
                return ResourceManager.GetString("AffichageMenuBudgetIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu centre d&apos;imputation.
        /// </summary>
        public static string AffichageMenuCIIndex {
            get {
                return ResourceManager.GetString("AffichageMenuCIIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu code absence.
        /// </summary>
        public static string AffichageMenuCodeAbsenceIndex {
            get {
                return ResourceManager.GetString("AffichageMenuCodeAbsenceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu code déplacement.
        /// </summary>
        public static string AffichageMenuCodeDeplacementIndex {
            get {
                return ResourceManager.GetString("AffichageMenuCodeDeplacementIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu code majoration.
        /// </summary>
        public static string AffichageMenuCodeMajorationIndex {
            get {
                return ResourceManager.GetString("AffichageMenuCodeMajorationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu code zone déplacement.
        /// </summary>
        public static string AffichageMenuCodeZoneDeplacementIndex {
            get {
                return ResourceManager.GetString("AffichageMenuCodeZoneDeplacementIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu commande.
        /// </summary>
        public static string AffichageMenuCommandeDetail {
            get {
                return ResourceManager.GetString("AffichageMenuCommandeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu date calendrier paie.
        /// </summary>
        public static string AffichageMenuDatesCalendrierPaieIndex {
            get {
                return ResourceManager.GetString("AffichageMenuDatesCalendrierPaieIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu date cloture comptable.
        /// </summary>
        public static string AffichageMenuDatesClotureComptableIndex {
            get {
                return ResourceManager.GetString("AffichageMenuDatesClotureComptableIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu depense explorer.
        /// </summary>
        public static string AffichageMenuDepenseExplorateur {
            get {
                return ResourceManager.GetString("AffichageMenuDepenseExplorateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu depense.
        /// </summary>
        public static string AffichageMenuDepenseIndex {
            get {
                return ResourceManager.GetString("AffichageMenuDepenseIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu transfert FAR.
        /// </summary>
        public static string AffichageMenuDepenseTransfertFAR {
            get {
                return ResourceManager.GetString("AffichageMenuDepenseTransfertFAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu établissement comptable.
        /// </summary>
        public static string AffichageMenuEtablissementComptableIndex {
            get {
                return ResourceManager.GetString("AffichageMenuEtablissementComptableIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu établissement de paie.
        /// </summary>
        public static string AffichageMenuEtablissementPaieIndex {
            get {
                return ResourceManager.GetString("AffichageMenuEtablissementPaieIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu facture.
        /// </summary>
        public static string AffichageMenuFactureIndex {
            get {
                return ResourceManager.GetString("AffichageMenuFactureIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu fournisseur.
        /// </summary>
        public static string AffichageMenuFournisseurIndex {
            get {
                return ResourceManager.GetString("AffichageMenuFournisseurIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu materiel.
        /// </summary>
        public static string AffichageMenuMaterielIndex {
            get {
                return ResourceManager.GetString("AffichageMenuMaterielIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu module.
        /// </summary>
        public static string AffichageMenuModuleIndex {
            get {
                return ResourceManager.GetString("AffichageMenuModuleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu nature.
        /// </summary>
        public static string AffichageMenuNatureIndex {
            get {
                return ResourceManager.GetString("AffichageMenuNatureIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu organisation.
        /// </summary>
        public static string AffichageMenuOrganisationIndex {
            get {
                return ResourceManager.GetString("AffichageMenuOrganisationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu param tarif référentiel.
        /// </summary>
        public static string AffichageMenuParamTarifsReferentielsIndex {
            get {
                return ResourceManager.GetString("AffichageMenuParamTarifsReferentielsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu personnel.
        /// </summary>
        public static string AffichageMenuPersonnelIndex {
            get {
                return ResourceManager.GetString("AffichageMenuPersonnelIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu rapport.
        /// </summary>
        public static string AffichageMenuPointagePersonnelIndex {
            get {
                return ResourceManager.GetString("AffichageMenuPointagePersonnelIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu pointage personnel.
        /// </summary>
        public static string AffichageMenuPrimeIndex {
            get {
                return ResourceManager.GetString("AffichageMenuPrimeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu reception.
        /// </summary>
        public static string AffichageMenuReceptionIndex {
            get {
                return ResourceManager.GetString("AffichageMenuReceptionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu référentiel etendu.
        /// </summary>
        public static string AffichageMenuReferentielEtenduIndex {
            get {
                return ResourceManager.GetString("AffichageMenuReferentielEtenduIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu référentiel fixe.
        /// </summary>
        public static string AffichageMenuReferentielFixesIndex {
            get {
                return ResourceManager.GetString("AffichageMenuReferentielFixesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu plan de taches.
        /// </summary>
        public static string AffichageMenuReferentielTachesIndex {
            get {
                return ResourceManager.GetString("AffichageMenuReferentielTachesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu rôle.
        /// </summary>
        public static string AffichageMenuRoleIndex {
            get {
                return ResourceManager.GetString("AffichageMenuRoleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu société.
        /// </summary>
        public static string AffichageMenuSocieteIndex {
            get {
                return ResourceManager.GetString("AffichageMenuSocieteIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher le menu validation pointage.
        /// </summary>
        public static string AffichageMenuValidationPointageIndex {
            get {
                return ResourceManager.GetString("AffichageMenuValidationPointageIndex", resourceCulture);
            }
        }
    }
}
