//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureFamilleOperationDiverse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureFamilleOperationDiverse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureFamilleOperationDiverse", typeof(FeatureFamilleOperationDiverse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enregistrée en compta.
        /// </summary>
        public static string FamilleOperationDivers_Index_EnregistrerEnCompta {
            get {
                return ResourceManager.GetString("FamilleOperationDivers_Index_EnregistrerEnCompta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° de commande.
        /// </summary>
        public static string FamilleOperationDivers_Index_NumeroCommande {
            get {
                return ResourceManager.GetString("FamilleOperationDivers_Index_NumeroCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajust FAR.
        /// </summary>
        public static string FamilleOperationDiverse_AjustementFAR {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_AjustementFAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Famille OD/Natures/Journaux.
        /// </summary>
        public static string FamilleOperationDiverse_AssociationFodNaturesJournaux_Titre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_AssociationFodNaturesJournaux_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familles &gt; Journal.
        /// </summary>
        public static string FamilleOperationDiverse_ChoixFamilleJournal_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ChoixFamilleJournal_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familles &gt; Nature.
        /// </summary>
        public static string FamilleOperationDiverse_ChoixFamilleNature_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ChoixFamilleNature_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal &gt; Familles.
        /// </summary>
        public static string FamilleOperationDiverse_ChoixJournalFamille_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ChoixJournalFamille_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature &gt; Familles.
        /// </summary>
        public static string FamilleOperationDiverse_ChoixNatureFamille_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ChoixNatureFamille_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôler le paramétrage.
        /// </summary>
        public static string FamilleOperationDiverse_ControleParametrage_Action {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ControleParametrage_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhaitez-vous lancer le contrôle du paramétrage ?.
        /// </summary>
        public static string FamilleOperationDiverse_ControleParametrage_Question_Message {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ControleParametrage_Question_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucunes anomalies constatées sur le paramétrage..
        /// </summary>
        public static string FamilleOperationDiverse_ControleParametrage_Question_Message_AucuneDonnees {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ControleParametrage_Question_Message_AucuneDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôler le paramétrage.
        /// </summary>
        public static string FamilleOperationDiverse_ControleParametrage_Question_Titre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ControleParametrage_Question_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner une société avant d&apos;effectuer le contrôle du paramétrage..
        /// </summary>
        public static string FamilleOperationDiverse_ControleParametrage_SocieteVide {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_ControleParametrage_SocieteVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier une famille OD.
        /// </summary>
        public static string FamilleOperationDiverse_EditFod_Titre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_EditFod_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;export Excel.
        /// </summary>
        public static string FamilleOperationDiverse_Export_Erreur {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Export_Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que souhaitez-vous faire ?.
        /// </summary>
        public static string FamilleOperationDiverse_Export_Question_Titre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Export_Question_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner une société avant d&apos;effectuer l&apos;export du paramétrage..
        /// </summary>
        public static string FamilleOperationDiverse_Export_SocieteVide {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Export_SocieteVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export du paramétrage.
        /// </summary>
        public static string FamilleOperationDiverse_Export_Titre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Export_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture.
        /// </summary>
        public static string FamilleOperationDiverse_Facture {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Facture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famille des OD.
        /// </summary>
        public static string FamilleOperationDiverse_Index_FamilleOd_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_FamilleOd_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un journal....
        /// </summary>
        public static string FamilleOperationDiverse_Index_PlaceholderJournal_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_PlaceholderJournal_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une nature....
        /// </summary>
        public static string FamilleOperationDiverse_Index_PlaceholderNature_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_PlaceholderNature_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANAEL - Rechercher un journal.
        /// </summary>
        public static string FamilleOperationDiverse_Index_RechercherJournal_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_RechercherJournal_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANAEL - Rechercher une nature analytique.
        /// </summary>
        public static string FamilleOperationDiverse_Index_RechercherNature_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_RechercherNature_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une famille....
        /// </summary>
        public static string FamilleOperationDiverse_Index_SelectionnerFamille {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_SelectionnerFamille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une société.
        /// </summary>
        public static string FamilleOperationDiverse_Index_Societe_SousTitre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_Societe_SousTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage des familles d&apos;OD.
        /// </summary>
        public static string FamilleOperationDiverse_Index_Titre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famille.
        /// </summary>
        public static string FamilleOperationDiverse_Index_TitreOnglet {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Index_TitreOnglet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string FamilleOperationDiverse_Libelle {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le libellé court est trop long (max 20 caractères).
        /// </summary>
        public static string FamilleOperationDiverse_LibelleCourtTropLong {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_LibelleCourtTropLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le libellé court est requis.
        /// </summary>
        public static string FamilleOperationDiverse_LibelleCourtVide {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_LibelleCourtVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familles opérations diverses.
        /// </summary>
        public static string FamilleOperationDiverse_List_Titre {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_List_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réception.
        /// </summary>
        public static string FamilleOperationDiverse_Reception {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valorisation.
        /// </summary>
        public static string FamilleOperationDiverse_Valorisation {
            get {
                return ResourceManager.GetString("FamilleOperationDiverse_Valorisation", resourceCulture);
            }
        }
    }
}
