//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureDatesCalendrierPaie {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureDatesCalendrierPaie() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureDatesCalendrierPaie", typeof(FeatureDatesCalendrierPaie).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour des dates relatives aux calendriers de paie effectuée avec succès.
        /// </summary>
        public static string Action_Update_Success {
            get {
                return ResourceManager.GetString("Action_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Btn_Annuler_lb {
            get {
                return ResourceManager.GetString("Btn_Annuler_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Btn_Valider_lb {
            get {
                return ResourceManager.GetString("Btn_Valider_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur durant le chargement des données..
        /// </summary>
        public static string Data_Load_Fail {
            get {
                return ResourceManager.GetString("Data_Load_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La saisie du mois {0} est en anomalie : La date d&apos;arrêt des pointages réels est supérieure à la date de transfert des pointages en paie.
        /// </summary>
        public static string DateFinPointage_error {
            get {
                return ResourceManager.GetString("DateFinPointage_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage du calendrier de paie.
        /// </summary>
        public static string DatesCalendrierPaie_titre {
            get {
                return ResourceManager.GetString("DatesCalendrierPaie_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt des pointages réels.
        /// </summary>
        public static string Radio_ChoixArretPointages_lb {
            get {
                return ResourceManager.GetString("Radio_ChoixArretPointages_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfert des pointages en paie.
        /// </summary>
        public static string Radio_ChoixTransfertPointages_lb {
            get {
                return ResourceManager.GetString("Radio_ChoixTransfertPointages_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        public static string Societe_lb {
            get {
                return ResourceManager.GetString("Societe_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société obligatoire.
        /// </summary>
        public static string SocieteObligatoire_lb {
            get {
                return ResourceManager.GetString("SocieteObligatoire_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage de la clôture paie.
        /// </summary>
        public static string tit_DatesCloturePaie_lb {
            get {
                return ResourceManager.GetString("tit_DatesCloturePaie_lb", resourceCulture);
            }
        }
    }
}
