//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureMateriel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureMateriel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.FeatureMateriel", typeof(FeatureMateriel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement.
        /// </summary>
        public static string Materiel_PanelMain_Etablissement {
            get {
                return ResourceManager.GetString("Materiel_PanelMain_Etablissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un Code Matériel ....
        /// </summary>
        public static string Materiel_PanelMain_Recherche_Placeholder {
            get {
                return ResourceManager.GetString("Materiel_PanelMain_Recherche_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string Materiel_PanelMain_Table_Libelle {
            get {
                return ResourceManager.GetString("Materiel_PanelMain_Table_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Materiel_PanelMain_Table_Location {
            get {
                return ResourceManager.GetString("Materiel_PanelMain_Table_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer Codes Matériel.
        /// </summary>
        public static string Materiel_PanelMain_Titre {
            get {
                return ResourceManager.GetString("Materiel_PanelMain_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Materiel_PanelRight_Code {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 caractères max.
        /// </summary>
        public static string Materiel_PanelRight_Code_Placeholder {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_Code_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début.
        /// </summary>
        public static string Materiel_PanelRight_DateDebut {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_DateDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisir une date de début.
        /// </summary>
        public static string Materiel_PanelRight_DateDebut_title {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_DateDebut_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string Materiel_PanelRight_DateFin {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_DateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisir une date de fin.
        /// </summary>
        public static string Materiel_PanelRight_DateFin_title {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_DateFin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement Comptable.
        /// </summary>
        public static string Materiel_PanelRight_EtablissementComptable {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_EtablissementComptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        public static string Materiel_PanelRight_Fournisseur {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_Fournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string Materiel_PanelRight_Libelle {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string Materiel_PanelRight_Libelle_Placeholder {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_Libelle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériel de location.
        /// </summary>
        public static string Materiel_PanelRight_MaterielLocation {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_MaterielLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource.
        /// </summary>
        public static string Materiel_PanelRight_Ressource {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_Ressource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un Code Matériel.
        /// </summary>
        public static string Materiel_PanelRight_Titre_Ajouter {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_Titre_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier un Code Matériel.
        /// </summary>
        public static string Materiel_PanelRight_Titre_Modifier {
            get {
                return ResourceManager.GetString("Materiel_PanelRight_Titre_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériel.
        /// </summary>
        public static string Materiel_TitreOnglet {
            get {
                return ResourceManager.GetString("Materiel_TitreOnglet", resourceCulture);
            }
        }
    }
}
