//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Web.Shared.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Page_Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Page_Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Web.Shared.App_LocalResources.Page_Title", typeof(Page_Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceuil.
        /// </summary>
        public static string Title_Acceuil {
            get {
                return ResourceManager.GetString("Title_Acceuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRED - .
        /// </summary>
        public static string Title_App {
            get {
                return ResourceManager.GetString("Title_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification.
        /// </summary>
        public static string Title_Athentification {
            get {
                return ResourceManager.GetString("Title_Athentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barème.
        /// </summary>
        public static string Title_Bareme {
            get {
                return ResourceManager.GetString("Title_Bareme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgets.
        /// </summary>
        public static string Title_budget {
            get {
                return ResourceManager.GetString("Title_budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre d&apos;imputation.
        /// </summary>
        public static string Title_Ci {
            get {
                return ResourceManager.GetString("Title_Ci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendrier de clôture comptable.
        /// </summary>
        public static string Title_Cloture_Comptable {
            get {
                return ResourceManager.GetString("Title_Cloture_Comptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes absense.
        /// </summary>
        public static string Title_Code_Absence {
            get {
                return ResourceManager.GetString("Title_Code_Absence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes deplacement.
        /// </summary>
        public static string Title_Code_Deplacement {
            get {
                return ResourceManager.GetString("Title_Code_Deplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes majoration.
        /// </summary>
        public static string Title_Code_Majoration {
            get {
                return ResourceManager.GetString("Title_Code_Majoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes zone déplacement.
        /// </summary>
        public static string Title_Code_Zone_Deplacement {
            get {
                return ResourceManager.GetString("Title_Code_Zone_Deplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandes.
        /// </summary>
        public static string Title_Commande {
            get {
                return ResourceManager.GetString("Title_Commande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendrier de paie.
        /// </summary>
        public static string Title_Date_Paie {
            get {
                return ResourceManager.GetString("Title_Date_Paie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dépense.
        /// </summary>
        public static string Title_Depense {
            get {
                return ResourceManager.GetString("Title_Depense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement comptable.
        /// </summary>
        public static string Title_Etablissement_Comptable {
            get {
                return ResourceManager.GetString("Title_Etablissement_Comptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement paie.
        /// </summary>
        public static string Title_Etablissement_Paie {
            get {
                return ResourceManager.GetString("Title_Etablissement_Paie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des factures.
        /// </summary>
        public static string Title_Facture {
            get {
                return ResourceManager.GetString("Title_Facture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Flipping.
        /// </summary>
        public static string Title_FeatureFlipping {
            get {
                return ResourceManager.GetString("Title_FeatureFlipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des fournisseur.
        /// </summary>
        public static string Title_Founisseur {
            get {
                return ResourceManager.GetString("Title_Founisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide et support.
        /// </summary>
        public static string Title_Help {
            get {
                return ResourceManager.GetString("Title_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayat://FRED.
        /// </summary>
        public static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indemnité déplacement.
        /// </summary>
        public static string Title_Indemnite_Deplacement {
            get {
                return ResourceManager.GetString("Title_Indemnite_Deplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journaux comptables.
        /// </summary>
        public static string Title_Journal_Comptable {
            get {
                return ResourceManager.GetString("Title_Journal_Comptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup.
        /// </summary>
        public static string Title_Lookup {
            get {
                return ResourceManager.GetString("Title_Lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériel.
        /// </summary>
        public static string Title_Materiel {
            get {
                return ResourceManager.GetString("Title_Materiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Title_Module {
            get {
                return ResourceManager.GetString("Title_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string Title_Monitoring {
            get {
                return ResourceManager.GetString("Title_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string Title_Nature {
            get {
                return ResourceManager.GetString("Title_Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Title_Notification {
            get {
                return ResourceManager.GetString("Title_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string Title_Organisation {
            get {
                return ResourceManager.GetString("Title_Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifs référentiel.
        /// </summary>
        public static string Title_Param_Tarif {
            get {
                return ResourceManager.GetString("Title_Param_Tarif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnels.
        /// </summary>
        public static string Title_Personnel {
            get {
                return ResourceManager.GetString("Title_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapports.
        /// </summary>
        public static string Title_Pointage {
            get {
                return ResourceManager.GetString("Title_Pointage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointages personnels.
        /// </summary>
        public static string Title_Pointage_Personnel {
            get {
                return ResourceManager.GetString("Title_Pointage_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primes.
        /// </summary>
        public static string Title_Prime {
            get {
                return ResourceManager.GetString("Title_Prime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapprochement de factures.
        /// </summary>
        public static string Title_Rapprochement {
            get {
                return ResourceManager.GetString("Title_Rapprochement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception.
        /// </summary>
        public static string Title_Reception {
            get {
                return ResourceManager.GetString("Title_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référentiels.
        /// </summary>
        public static string Title_Referentiel {
            get {
                return ResourceManager.GetString("Title_Referentiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référentiels étentus.
        /// </summary>
        public static string Title_Referentiel_Etendu {
            get {
                return ResourceManager.GetString("Title_Referentiel_Etendu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référentiels fixe.
        /// </summary>
        public static string Title_Referentiel_Fixe {
            get {
                return ResourceManager.GetString("Title_Referentiel_Fixe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référentiels taches.
        /// </summary>
        public static string Title_Referentiel_Tache {
            get {
                return ResourceManager.GetString("Title_Referentiel_Tache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources recommandées.
        /// </summary>
        public static string Title_Ressources_Recommandees {
            get {
                return ResourceManager.GetString("Title_Ressources_Recommandees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources spécifiques CI.
        /// </summary>
        public static string Title_Ressources_Specifiques_CI {
            get {
                return ResourceManager.GetString("Title_Ressources_Specifiques_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôles.
        /// </summary>
        public static string Title_Role {
            get {
                return ResourceManager.GetString("Title_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociétés.
        /// </summary>
        public static string Title_Societe {
            get {
                return ResourceManager.GetString("Title_Societe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur.
        /// </summary>
        public static string Title_User {
            get {
                return ResourceManager.GetString("Title_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointages personnel.
        /// </summary>
        public static string Title_Validation_Pointage {
            get {
                return ResourceManager.GetString("Title_Validation_Pointage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valorisation.
        /// </summary>
        public static string Title_Valorisation {
            get {
                return ResourceManager.GetString("Title_Valorisation", resourceCulture);
            }
        }
    }
}
