SELECT ENTRE.ENTRE_SOC_PAYE,ISNULL(AFFAI.AFFAI_PREST, AFFAI.AFFAI_ID) AS AFFAI_ID,PERIGD.PERSO_ID,PERIGD.CODEP_ID,PERIGD.ZONE_ID,PERIGD.KM,PERIGD.VEHICULE,PERIGD.IVD,PERIGD.RAT_CHA_KMVO,PERIGD.DOM_CHA_KMVO
FROM PERIGD
	INNER JOIN AFFAI ON AFFAI.AFFAI_ID=PERIGD.AFFAI_ID
	INNER JOIN PERSO ON PERSO.ENTRE_ID=PERIGD.ENTRE_ID AND PERSO.PERSO_ID=PERIGD.PERSO_ID
	INNER JOIN ENTRE ON ENTRE.ENTRE_ID=PERSO.ENTRE_ID
WHERE PERSO.PERSO_INTERIM = 0
	AND (PERIGD.ENTRE_ID = 'RB' or PERIGD.ENTRE_ID = 'GB')
	AND PERIGD.AFFAI_ID NOT IN ({0})
