-- --------------------------------------------------
-- INJECTION GROUPE
-- --------------------------------------------------

EXEC Fred_ToolBox_Groupe @PoleCode='PFES',@Code='GFES',@Libelle='FAYAT ENERGIE SERVICES'
PRINT 'INFO : CHARGEMENT GROUPE GFES'


-- --------------------------------------------------
-- INJECTION SOCIETE
-- --------------------------------------------------
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E001',@CodeSocietePaye='1',@CodeSocieteComptable='E001',@Libelle='SATELEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E002',@CodeSocietePaye='2',@CodeSocieteComptable='E002',@Libelle='SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E003',@CodeSocietePaye='3',@CodeSocieteComptable='E003',@Libelle='FARECO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E006',@CodeSocietePaye='6',@CodeSocieteComptable='E006',@Libelle='CITEPARK'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E007',@CodeSocietePaye='7',@CodeSocieteComptable='E007',@Libelle='TRAFIPARC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E010',@CodeSocietePaye='101',@CodeSocieteComptable='E010',@Libelle='ERS'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E011',@CodeSocietePaye='102',@CodeSocieteComptable='E011',@Libelle='ERS Maine'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E012',@CodeSocietePaye='103',@CodeSocieteComptable='E012',@Libelle='DHENNIN'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E013',@CodeSocietePaye='13',@CodeSocieteComptable='E013',@Libelle='SODECLIM'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E014',@CodeSocietePaye='14',@CodeSocieteComptable='E014',@Libelle='GROUPE FESI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E015',@CodeSocietePaye='15',@CodeSocieteComptable='E015',@Libelle='GABRIELLE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E016',@CodeSocietePaye='16',@CodeSocieteComptable='E016',@Libelle='AVEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E017',@CodeSocietePaye='17',@CodeSocieteComptable='E017',@Libelle='SATELEC-CENERGI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E018',@CodeSocietePaye='18',@CodeSocieteComptable='E018',@Libelle='SATCOMPTAGES'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E019',@CodeSocietePaye='19',@CodeSocieteComptable='E019',@Libelle='VALIANCE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EG01',@CodeSocietePaye='n/a',@CodeSocieteComptable='EG01',@Libelle='GIE Lignes Souterraines'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EG02',@CodeSocietePaye='n/a',@CodeSocieteComptable='EG02',@Libelle='GIE Fayat Postes HT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES01',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES01',@Libelle='SEP CHU NICE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES02',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES02',@Libelle='SEP DAI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES04',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES04',@Libelle='SEP SLT GRAND LYON'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES05',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES05',@Libelle='SEP - RADARS MEEDDAT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES06',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES06',@Libelle='SEP TUNNEL DU LANDY'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES07',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES07',@Libelle='SEP R-GTC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES08',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES08',@Libelle='SEP MAGES Maintenance'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES09',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES09',@Libelle='SEP LISA SATELEC - INEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES10',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES10',@Libelle='SEP TUNNEL DE NOGENT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES11',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES11',@Libelle='SEP GTC SEMERU / SPIE / INEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES12',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES12',@Libelle='SEP Seine Aval - ADEN/AXEAU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES13',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES13',@Libelle='SEP MESS SDEL / SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES14',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES14',@Libelle='SEP RFF - SATELEC / SNCF INGEN'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES15',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES15',@Libelle='SEP ETM - FARECO / SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES16',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES16',@Libelle='SEP SAT/INEO Maint. Radar Auto'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES17',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES17',@Libelle='SEP Ligne LMCU INEO - SATELEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES18',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES18',@Libelle='SEP CAC SATELEC-SDEL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES19',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES19',@Libelle='SEP BPNL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES20',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES20',@Libelle='SEP RN7 SATELEC SPIE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES21',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES21',@Libelle='SEP MEDTS SEMERU/SDEL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES22',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES22',@Libelle='SEP IP 13'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES23',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES23',@Libelle='SEP BPNL GTC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES24',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES24',@Libelle='SEP SATELEC-RAZEL BEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES25',@CodeSocietePaye='n/a',@CodeSocieteComptable='ES25',@Libelle='SEP MAINTENANCE RADARS MOF'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX05',@CodeSocietePaye='n/a',@CodeSocieteComptable='EX05',@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX06',@CodeSocietePaye='n/a',@CodeSocieteComptable='EX06',@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX07',@CodeSocietePaye='n/a',@CodeSocieteComptable='EX07',@Libelle='FESI - MAROC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX08',@CodeSocietePaye='n/a',@CodeSocieteComptable='EX08',@Libelle='FESI - CAMEROUN'

PRINT 'INFO : CHARGEMENT SOCIETE OK'


-- --------------------------------------------------
-- INJECTION ETABLISSEMENTS COMPTABLES
-- --------------------------------------------------

EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0010',@Libelle='SATELEC PIDF'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0020',@Libelle='SATELEC France NORD'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0030',@Libelle='SATELEC PACA'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0040',@Libelle='SATELEC AQUITAINE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0050',@Libelle='SATELEC Grands Projets'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0075',@Libelle='SATELEC DG'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0090',@Libelle='FESI - NIGER'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0091',@Libelle='FESI - CAMEROUN'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0092',@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0093',@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E002',@Code='0001',@Libelle='SEMERU PIDF'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E002',@Code='0002',@Libelle='SEMERU NORD'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E002',@Code='0003',@Libelle='SEMERU PACA'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E002',@Code='0004',@Libelle='SEMERU OUEST'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E003',@Code='0010',@Libelle='FARECO'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E004',@Code='0098',@Libelle='FARECO TUNISIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E006',@Code='0010',@Libelle='CITEPARK PIDF'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E006',@Code='0015',@Libelle='DSP Ville de Pré Saint Gervais'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E006',@Code='0016',@Libelle='DSP Melun'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E007',@Code='0031',@Libelle='SAM TRAFIPARC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E010',@Code='0041',@Libelle='ERS'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E011',@Code='0042',@Libelle='ERS Maine'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E012',@Code='0043',@Libelle='DHENNIN'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E013',@Code='0011',@Libelle='SODECLIM'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0020',@Libelle='FESI QUINCY'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0094',@Libelle='FESI - MOZAMBIQUE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0095',@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0096',@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0097',@Libelle='FESI - MAROC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E015',@Code='0060',@Libelle='GABRIELLE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E016',@Code='0013',@Libelle='AVEO'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E017',@Code='0974',@Libelle='SATELEC-CENERGI'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E018',@Code='0014',@Libelle='SATCOMPTAGES'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EG01',@Code='EG01',@Libelle='GIE Lignes Souterraines'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EG02',@Code='EG02',@Libelle='GIE Fayat Postes HT'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES01',@Code='ES01',@Libelle='SEP CHU NICE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES02',@Code='ES02',@Libelle='SEP DAI'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES04',@Code='ES04',@Libelle='SEP SLT GRAND LYON'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES05',@Code='ES05',@Libelle='SEP - RADARS MEEDDAT'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES06',@Code='ES06',@Libelle='SEP TUNNEL DU LANDY'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES07',@Code='ES07',@Libelle='SEP R-GTC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES08',@Code='ES08',@Libelle='SEP MAGES Maintenance'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES09',@Code='ES09',@Libelle='SEP LISA SATELEC - INEO'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES10',@Code='ES10',@Libelle='SEP TUNNEL DE NOGENT'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES11',@Code='ES11',@Libelle='SEP GTC SEMERU / SPIE / INEO'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES12',@Code='ES12',@Libelle='SEP Seine Aval - ADEN/AXEAU'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES13',@Code='ES13',@Libelle='SEP MESS SDEL / SEMERU'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES14',@Code='ES14',@Libelle='SEP RFF - SATELEC / SNCF INGEN'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES15',@Code='ES15',@Libelle='SEP ETM - FARECO / SEMERU'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES16',@Code='ES16',@Libelle='SEP SAT/INEO Maint. Radar Auto'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES17',@Code='ES17',@Libelle='SEP Ligne LMCU INEO - SATELEC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES18',@Code='ES18',@Libelle='SEP CAC SATELEC-SDEL'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES19',@Code='ES19',@Libelle='SEP BPNL'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES20',@Code='ES20',@Libelle='SEP RN7 SATELEC SPIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES21',@Code='ES21',@Libelle='SEP MEDTS SEMERU/SDEL'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES22',@Code='ES22',@Libelle='SEP IP 13'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES23',@Code='ES23',@Libelle='SEP BPNL GTC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES24',@Code='ES24',@Libelle='SEP SATELEC-RAZEL BEC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES25',@Code='ES25',@Libelle='SEP MAINTENANCE RADARS MOF'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EX05',@Code='EX05',@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EX06',@Code='EX06',@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EX07',@Code='EX07',@Libelle='FESI - MAROC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EX08',@Code='EX08',@Libelle='FESI - CAMEROUN'

PRINT 'INFO : CHARGEMENT ETABLISSEMENTS COMPTABLES OK'


-- --------------------------------------------------
-- INJECTION ETABLISSEMENT PAIE
-- --------------------------------------------------

EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='75',@Code='09',@Libelle='SATELEC DG',@Adresse='24 ave du Général de Gaulle, 91170 VIRY-CHATILLON',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='10',@Libelle='SATELEC VIRY',@Adresse='24 ave du Général de Gaulle, 91170 VIRY-CHATILLON',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='11',@Libelle='SATELEC ANTONY',@Adresse='3 rue Henri Poincaré, 92160 ANTONY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='50',@Code='12',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='13',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='14',@Libelle='SATELEC BAGNOLET',@Adresse='73 rue des Rigondes, 93170 BAGNOLET',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='15',@Libelle='SATELEC BONNEUIL',@Adresse='4 ave des Marronniers, 94380 BONNEUIL SUR MARNE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='16',@Libelle='SATELEC CESSON',@Adresse='225 ave de l''Europe, 77240 VERT SAINT DENIS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='17',@Libelle='SATELEC NANTERRE',@Adresse='85 Rue des hautes Patures, 92000 NANTERRE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='50',@Code='18',@Libelle='SATELEC POWER NANT.',@Adresse='85 Rue des hautes Patures, 92000 NANTERRE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='20',@Libelle='SATELEC CUINCY',@Adresse='945 rue du Faubourg, 59553 CUINCY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='21',@Libelle='SATELEC TRITH',@Adresse='14  ZA Les Poutrelles, 59125 TRITH SAINT LEGER',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='22',@Libelle='SATELEC TOURCOING',@Adresse='59  Chaussée Berthelot, 59200 TOURCOING',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='23',@Libelle='SATELEC GDE SYNTHE',@Adresse='17 rue de l''Abbé Grégoire, 59760 GRANDE-SYNTHE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='24',@Libelle='SATELEC HENIN BT',@Adresse='141 bld Edouard Branly, 62110 HENIN-BEAUMONT',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='25',@Libelle='SATELEC MONTIGNY',@Adresse='4 rue Saussaies-aux-Dames, 57950 MONTIGNY-LES-METZ',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='26',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='27',@Libelle='SATELEC POULAINVILLE',@Adresse='0 rue Marius Morel, 80260 POULAINVILLE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='28',@Libelle='SATELEC ST ANDRE',@Adresse='10 RUE GUSTAVE EIFFEL, 10120 SAINT ANDRE LES VERGERS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='29',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='30',@Code='30',@Libelle='SATELEC PACA',@Adresse='68  Parc de l''Argile, 6370 MOUANS-SARTOUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='40',@Code='40',@Libelle='SATELEC AQUITAINE',@Adresse='27 rue de Fleurenne, 33290 BLANQUEFORT',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='50',@Code='41',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='40',@Code='42',@Libelle='SATELEC BISCARROSSE',@Adresse='175 rue Forestière, 40600 BISCARROSSE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@Code='69',@Libelle='SATELEC LYON',@Adresse='2  Chemin du Genie, 69200 VENISSIEUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='2A',@Libelle='SATELEC ALLONNE',@Adresse='115 rue des quarantes Mines, 60000 ALLONNE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='2B',@Libelle='SATELEC ST PAUL',@Adresse='3 Ave Piton Batard, 97460 SAINT PAUL',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='10',@Libelle='SEMERU VIRY',@Adresse='34 RUE CHARLES PIKETTY, 91170 VIRY CHATILLON',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='11',@Libelle='SEMERU ANTONY',@Adresse='3 RUE HENRI POINCARE, 92160 ANTONY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='12',@Libelle='SEMERU BONNEUIL',@Adresse='4 AVE DES MARRONNIERS, 94380 BONNEUIL SUR MARNE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='13',@Libelle='SEMERU RUNGIS',@Adresse='54 RUE D ARCUEIL, 94150 RUNGIS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@Code='20',@Libelle='SEMERU CUINCY',@Adresse='945 RUE DU FAUBOURG, 59553 CUINCY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='21',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='22',@Libelle='SEMERU TEMPLEMARS',@Adresse='0  PARC D''ACTIVITE B, 59175 TEMPLEMARS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='30',@Libelle='SEMERU PACA',@Adresse='68  PARC de L''ARGILE, 6370 MOUANS SARTOUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='40',@Libelle='SEMERU AQUITAINE',@Adresse='27 RUE DE FLEURENNE, 33290 BLANQUEFORT',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='50',@Libelle='SEMERU LYON',@Adresse='2  CHEMIN DU GENIE, 69200 VENISSIEUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='10',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='11',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='12',@Libelle='FARECO GENNEVILLIERS',@Adresse='223 RUE DES CABOEUFS, 92230 GENNEVILLIERS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='13',@Libelle='FARECO ASNIERES',@Adresse='250 Av DES GRESILLONS, 92600 ASNIERES',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='20',@Libelle='FARECO MEYREUIL',@Adresse='8  PARC TECHNOLOGIQUE, 13590 MEYREUIL',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E006',@AgenceRattachementCode='10',@Code='10',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E006',@AgenceRattachementCode='10',@Code='11',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E006',@AgenceRattachementCode='10',@Code='12',@Libelle='CITEPARK ANTONY',@Adresse='3 RUE HENRI POINCARE, 92160 ANTONY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E006',@AgenceRattachementCode='10',@Code='30',@Libelle='CITEPARK PACA',@Adresse='68  PARC DE l''ARGILE, 6370 MOUANS SARTOUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E007',@AgenceRattachementCode='31',@Code='10',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='10',@Libelle='ERS SAINT GREGOIRE',@Adresse='7  P.A. de Brocéliande, 35760 SAINT GREGOIRE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='11',@Libelle='ERS MELESSE',@Adresse='0 Rue de la Perrière, 35520 MELESSE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='20',@Libelle='ERS LAVAL',@Adresse='0  Allée de la Goberie, 53940 SAINT-BERTHEVIN',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='30',@Libelle='ERS COUTANCES',@Adresse='0  ZI Chateau de la Mare, 50200 COUTANCES',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='40',@Libelle='ERS ANGERS',@Adresse='15 rue Paul Langevin, 49240 AVRILLE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='50',@Libelle='ERS DINAN',@Adresse='2 rue de la Tramontane, 22100 TADEN',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='60',@Libelle='ERS CARQUEFOU',@Adresse='25  Allée des Sapins, 44470 CARQUEFOU',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='70',@Libelle='ERS SAINT AVE',@Adresse='30 rue Marcel Dassault, 56890 SAINT AVE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@Code='80',@Libelle='ERS ELLIANT',@Adresse='0  Impasse Penalen, 29370 ELLIANT',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='90',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E011',@AgenceRattachementCode='42',@Code='10',@Libelle='ERS MAINE',@Adresse='5  Allée du Perquoi, 72560 CHANGE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E011',@AgenceRattachementCode='42',@Code='20',@Libelle='ERS MAINE',@Adresse='3 rue de la Briaudière, 37510 Ballan-Mire',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E012',@AgenceRattachementCode='43',@Code='10',@Libelle='SR DHENNIN',@Adresse='0  Zone Industrielle, 28140 ORGERES EN BEAUCE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E012',@AgenceRattachementCode='43',@Code='20',@Libelle='SR DHENNIN GELLAINVI',@Adresse='12 ave Gustave Eiffel, 28630 GELLAINVILLE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E013',@AgenceRattachementCode='11',@Code='11',@Libelle='SODECLIM',@Adresse='56 RUE LOUIS AUROUX, 94120 FONTENAY SOUS BOIS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E014',@AgenceRattachementCode='20',@Code='20',@Libelle='F.E.S.I Cuincy',@Adresse='945 RUE DU FBG D ESQUERCHIN, 59553 CUINCY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E015',@AgenceRattachementCode='60',@Code='40',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E015',@AgenceRattachementCode='60',@Code='41',@Libelle='GABRIELLE AUCH',@Adresse='2 IMP D ENGACHIES, 32000 AUCH',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E015',@AgenceRattachementCode='60',@Code='42',@Libelle='GABRIELLE RIGNAC',@Adresse='0 ZA LES VIEILLES VIGNES, 46500 RIGNAC',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E015',@AgenceRattachementCode='60',@Code='43',@Libelle='GABRIELLE  BEAUZELLE',@Adresse='160 RUE DE LA SUR, 31700 BEAUZELLE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E015',@Code='44',@Libelle='GABRIELLE CADOURS',@Adresse='0  Route de Toulouse, 31480 CADOURS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E016',@AgenceRattachementCode='13',@Code='13',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E016',@Code='14',@Libelle='AVEO NANTERRE',@Adresse='45 rue des hautes patures, 92000 NANTERRE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E017',@AgenceRattachementCode='974',@Code='97',@Libelle='SATELEC CENERGI',@Adresse='9 Rue Sully Prudhomme, 97420 Le Port',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E017',@AgenceRattachementCode='974',@Code='98',@Libelle='SATELEC CENERGI',@Adresse='22 Rue Pierre Brossolette, 97420 Le Port',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E018',@AgenceRattachementCode='14',@Code='14',@Libelle='SATCOMPTAGES SIEGE',@Adresse='24 Ave Gal de Gaulle, 91170 VIRY CHATILLON',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E018',@AgenceRattachementCode='14',@Code='27',@Libelle='SATCOMPTAGES VAUCH.',@Adresse='36 rue Rene Dingeon, 80132 VAUCHELLES LES QUESNOY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E018',@AgenceRattachementCode='14',@Code='56',@Libelle='SATCOMPTAGES ST AVE',@Adresse='30 rue Marcel Dassault, 56890 SAINT AVE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E019',@AgenceRattachementCode='21',@Code='27',@Libelle='VALIANCE CATTENOM',@Adresse='17 RUE DE L ABBE GREGOIRE, 59760 GRANDE SYNTHE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @GroupeCode='GFES',@SocieteCode='E019',@Code='23',@Libelle='VALIANCE GRDE SYNTHE',@Adresse='0 ZAC D HUSANGE, 57570 CATTENOM',@PaysCode='FR'



PRINT 'INFO : CHARGEMENT ETABLISSEMENTS PAIE OK'