/*

-- SUPPRESSION DES CHAPITRES DE TESTS PRECEDEMENTS INJECTES DANS LE FICHIER 00030_FRED_GFES_RESSOURCES_V1.sql
--  ----------------------------------------------------------

declare @groupid int;
set @groupid = (select GroupeId from FRED_GROUPE where Code='GFES')
--select * from FRED_CHAPITRE  where GroupeId = @groupid
--select * from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)
--select * from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid))
--select * from FRED_SOCIETE_RESSOURCE_NATURE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
--select * from FRED_PERSONNEL where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
--select * from FRED_COMMANDE_LIGNE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
--select BudgetT4SousDetailId from FRED_BUDGET_T4_RESSOURCE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
--select AvancementId from FRED_AVANCEMENT where BudgetSousDetailId in (select BudgetT4SousDetailId from FRED_BUDGET_T4_RESSOURCE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid))))
--select * from FRED_AVANCEMENT_WORKFLOW where AvancementId in (select AvancementId from FRED_AVANCEMENT where BudgetT4SousDetailId in 

delete from FRED_AVANCEMENT_WORKFLOW where AvancementId in (select AvancementId from FRED_AVANCEMENT where BudgetSousDetailId in (select BudgetT4SousDetailId from FRED_BUDGET_T4_RESSOURCE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))))
delete from FRED_COMMANDE_LIGNE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
update FRED_PERSONNEL set RessourceId = null where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
delete from FRED_SOCIETE_RESSOURCE_NATURE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
delete from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid))
delete from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)
delete from FRED_CHAPITRE  where GroupeId = @groupid





-- --------------------------------------------------
-- INJECTION DES CHAPITRES
-- --------------------------------------------------
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='MOEOP',@Libelle='Main d œuvre Opérationnelle'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='MOEADM',@Libelle='Main d œuvre Administrative'




-- --------------------------------------------------
-- INJECTION DES SOUS-CHAPITRES
-- --------------------------------------------------
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEADM',@Code='001',@Libelle='Moyen/Achat/Atelier'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEADM',@Code='002',@Libelle='Compta. et Gestion'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEOP',@Code='003',@Libelle='Chantier Travaux'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEADM',@Code='004',@Libelle='RH/Paie/QSE/Juriste'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEOP',@Code='005',@Libelle='Ch.affaire/sect./gpe'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEOP',@Code='006',@Libelle='Commercial'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEOP',@Code='007',@Libelle='Direction Opération.'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEOP',@Code='008',@Libelle='Bureau d études'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='MOEADM',@Code='009',@Libelle='Direction Générale'







-- AJOUT RESSOURCES
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00626',@Libelle='Contrôleur Gestion',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00995',@Libelle='Assistante RH',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00711',@Libelle='Ing. Commercial',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00461',@Libelle='DGA Capital Humain',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='01004',@Libelle='Resp. Comptable',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00688',@Libelle='Animateur QSE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00430',@Libelle='Dir Report. & Finan. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00A37',@Libelle='Apprenti',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00133',@Libelle='Commercial',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00055',@Libelle='Comptable',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00996',@Libelle='Resp. Ress. Humaines',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00994',@Libelle='Resp. Report. Social',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00469',@Libelle='Resp Contr. Gestion',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00627',@Libelle='Contrôleur Financier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00582',@Libelle='Tech. Paie',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00127',@Libelle='Secrétaire',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00464',@Libelle='DGA Genie Electrique',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00769',@Libelle='Admin. Fonctionnel',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00360',@Libelle='Resp Serv Juridiques',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00903',@Libelle='Dir. Développement',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00431',@Libelle='Dir. Adm. & Financ. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00226',@Libelle='Directeur d Activité',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00692',@Libelle='Chargé de communic. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00140',@Libelle='Chef Groupe Achats',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00807',@Libelle='Tech. Achat',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00054',@Libelle='Assist Comptable',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00359',@Libelle='Juriste',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00700',@Libelle='DG Délégué',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00228',@Libelle='Dir Sces Moyens',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='0A169',@Libelle='Resp. Compta. Aux. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00682',@Libelle='Resp. Achats',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00008',@Libelle='Resp. Commercial',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00084',@Libelle='Président',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='0C146',@Libelle='Acheteur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00906',@Libelle='Directeur Commercial',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00801',@Libelle='Resp. Svce Approvis. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00904',@Libelle='DGD Secrét. Général',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00998',@Libelle='Resp. Proj. Formation',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00015',@Libelle='Chef Comptable',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00032',@Libelle='Secr. de Direction',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00772',@Libelle='Resp. Transf. Numér. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00146',@Libelle='Acheteur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00007',@Libelle='Responsable Paie',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00118',@Libelle='Hôtesse d Accueil',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00120',@Libelle='Responsable SIM',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='0C467',@Libelle='Directeur SSE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00147',@Libelle='Agent Administratif',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00691',@Libelle='Chargé de recrut. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00681',@Libelle='Directeur Délégué',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00169',@Libelle='Resp. Compta. Aux. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00839',@Libelle='Employé Administrati',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00900',@Libelle='DGA Commerce',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00889',@Libelle='Assist. de Direction',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00463',@Libelle='DGA Grands Projets',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00775',@Libelle='Analyste Fonctionnel',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00CRH',@Libelle='Chargée RH',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00057',@Libelle='Trésorier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00910',@Libelle='Resp. Rec. Créances',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00908',@Libelle='Dir. Projet Transfo. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='0C468',@Libelle='Resp. Mission RSE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00549',@Libelle='Tech. Serv. Moyen',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00141',@Libelle='Comptable Général',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='0C147',@Libelle='Acheteur Projet',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00475',@Libelle='Chef de Projet SI',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00230',@Libelle='Dir Achats',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00460',@Libelle='DGA Finances',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00465',@Libelle='Responsable QSE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00448',@Libelle='Ing. Junior',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00277',@Libelle='Monteur Electricien',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00161',@Libelle='Ing. Etudes',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00685',@Libelle='Chargé d Affaires',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00056',@Libelle='Conducteur Travaux',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='01106',@Libelle='Assistant(e)',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='0B145',@Libelle='Agent Technique',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00050',@Libelle='Dessinateur Etudes',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00302',@Libelle='Magasinier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='01219',@Libelle='Chef de Chantier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00117',@Libelle='Chef d Equipe',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00125',@Libelle='Chef de Groupe',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00124',@Libelle='Directeur de Zone',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='0B379',@Libelle='Dessin. Projeteur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00413',@Libelle='Cond. Travaux Adj. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00224',@Libelle='Chauffeur P. L. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00890',@Libelle='Resp. Serv. Matériel',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00892',@Libelle='Magasinier Cariste',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00776',@Libelle='Maitre Ouvrier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='0A553',@Libelle='Resp. Ress. Chantier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00683',@Libelle='Cadre Service Moyens',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00590',@Libelle='Chef de Secteur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00326',@Libelle='Chauffeur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00304',@Libelle='Tireur de CÃ¢bles',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00271',@Libelle='Mécanicien',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00247',@Libelle='Electromécanicien',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00366',@Libelle='Resp. Serv. Moy. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00750',@Libelle='Monteur Souterrain',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00106',@Libelle='Tech. de Chantier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00365',@Libelle='Resp. Serv. Gen. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00654',@Libelle='Tech. Etudes',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00862',@Libelle='Chauffeur Coursier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00RMG',@Libelle='Responsable Magasin',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00208',@Libelle='Aide Monteur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00470',@Libelle='Monteur Tuyauteur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00152',@Libelle='Assist. Administratif',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00049',@Libelle='Dessin. Exécution',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00777',@Libelle='Maitre Chef d Equipe',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00130',@Libelle='Secrétaire Technique',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='0C526',@Libelle='Tech. Maintenance',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00180',@Libelle='Contrôleur Projet',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00909',@Libelle='Technicien',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00000',@Libelle='Stagiaire',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='0A472',@Libelle='Chef de Projet',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='0A527',@Libelle='Tech. d Exploitation',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00ERH',@Libelle='Chargée RH',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='0F146',@Libelle='Agent Exploitation',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00177',@Libelle='MaÃ§on Electricien',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00260',@Libelle='MaÃ§on',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00199',@Libelle='Cadre Technique',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00126',@Libelle='Chef d entreprise',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00132',@Libelle='Chef Groupe Opérat',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00667',@Libelle='Terrass. Aide Macon',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00999',@Libelle='Terrass. Cond. de Pell',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00C37',@Libelle='Apprenti',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00666',@Libelle='Terrassier Niveleur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00265',@Libelle='Mineur Boiseur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00MOR',@Libelle='Monteur de réseaux',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00AS5',@Libelle='Assistant Techniq. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00660',@Libelle='Resp. d Affaires',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00467',@Libelle='Terrass. Mont. Elect. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00303',@Libelle='Terrassier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00570',@Libelle='Tech. Automaticien',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00400',@Libelle='Resp. Bureau Etudes',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00041',@Libelle='Chargé de Production',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00407',@Libelle='Comptable Principal',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00680',@Libelle='Resp. Achats Moyens',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00227',@Libelle='Câbleur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00439',@Libelle='Resp. d Atelier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='00421',@Libelle='Assistant(e) Paie',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00173',@Libelle='Agent d Entretien',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00630',@Libelle='Resp. Serv. Prix',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00318',@Libelle='Formateur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00621',@Libelle='Tech. Chiffrage',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00148',@Libelle='Acheteur Principal',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00689',@Libelle='Assist Chargé d Aff. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='0C153',@Libelle='Assistant(e) ADV',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00131',@Libelle='Secr. Comptable',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00D37',@Libelle='Apprenti',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='0C366',@Libelle='Resp. Serv. Moy. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00225',@Libelle='Chauf. P. L. Manut. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00849',@Libelle='Chauffeur Manut,',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00236',@Libelle='Conducteur d Engins',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00282',@Libelle='Mécanicien',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00561',@Libelle='Monteur Serrurier',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00CEN',@Libelle='Chauffeur Engins',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00162',@Libelle='Ing. Etudes de prix',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00213',@Libelle='Resp. Opérationnel',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00445',@Libelle='Ing. Chef de Projet',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00231',@Libelle='Admin. des Ventes',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00462',@Libelle='DGA Systemes FM',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00320',@Libelle='Planificateur projet',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00613',@Libelle='Agent Tech. Princip. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='0F145',@Libelle='Agent Technique',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00186',@Libelle='Appro Gest Stock',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='01203',@Libelle='Agent Tech. Cariste',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00710',@Libelle='Resp. Prod. Achats Log',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00200',@Libelle='Ingénieur Méthodes',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00170',@Libelle='Tech. gestion prod',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00157',@Libelle='Ing. Logiciel',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00451',@Libelle='Resp. Technique',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00774',@Libelle='Dir. Technique',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00905',@Libelle='Dir. Rech. Dev. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00002',@Libelle='Directeur Général',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00229',@Libelle='Dir Ventes Market',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='004',@Code='0C469',@Libelle='Chargée QSE/Methodes',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00153',@Libelle='Resp. Marketing Comm',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00158',@Libelle='Resp. Dev. Logiciel',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00368',@Libelle='Office Manager',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00600',@Libelle='Resp. de Site',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00150',@Libelle='Resp. d Exploitation',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00429',@Libelle='Resp. Adm. & Financ. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00450',@Libelle='Dir. de Projets',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00REE',@Libelle='Resp. d équipe Elect. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00CPR',@Libelle='Chauffeur Poseur Rés',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00MAN',@Libelle='Manoeuvre',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00POR',@Libelle='Poseur de Réseaux',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00490',@Libelle='Chauff. Mont. Electr',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00591',@Libelle='Chef de Service',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='01MAG',@Libelle='Logisticien(ne)',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='008',@Code='00402',@Libelle='Responsable Etudes',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00319',@Libelle='Planificatrice',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00286',@Libelle='Monteur Poseur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='006',@Code='00896',@Libelle='Assist. Commercial(e)',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00011',@Libelle='Ingénieur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='007',@Code='00072',@Libelle='Directeur',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00TEC',@Libelle='Technicien Chiffrage',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='002',@Code='00COM',@Libelle='Cptable-Gestion paie',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00ACH',@Libelle='Responsable Achat',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='009',@Code='00DIG',@Libelle='Directeur Régional',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00RRS',@Libelle='Resp. Equipe Rés. Sout',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='003',@Code='00RRA',@Libelle='Resp. Equipe Rés. Aér. ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='001',@Code='00FME',@Libelle='Femme de ménage',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='005',@Code='00684',@Libelle='Charg. d Aff. ETAM',@Type='Personnel'



*/