
/*  DONNEES DE TESTS  => Désactivé


-- --------------------------------------------------
-- INJECTION DES CHAPITRES
-- --------------------------------------------------
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='10',@Libelle='*MO ENCADREMENT'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='11',@Libelle='*MO PRODUCTION'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='12',@Libelle='*AUTRES CHARGES MO'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='20',@Libelle='*MATERIEL'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='30',@Libelle='*MATERIAUX & FOURNITURES'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='40',@Libelle='*SOUS TRAITANCE'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='50',@Libelle='*PRESTATIONS DE SERVICES'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='60',@Libelle='*AUTRES FRAIS'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='70',@Libelle='*PROVISIONS'




-- --------------------------------------------------
-- INJECTION DES SOUS-CHAPITRES
-- --------------------------------------------------
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-100',@Libelle='*DIRECTEUR'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-105',@Libelle='*CONDUCTEUR DE TRAVAUX'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-110',@Libelle='*CHEF DE CHANTIER'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-200',@Libelle='*ETUDES'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-300',@Libelle='*QSE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-400',@Libelle='*GÉOMÈTRE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-450',@Libelle='*LABORATOIRE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-500',@Libelle='*ADMINISTRATIFS'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-600',@Libelle='*MÉCANIQUE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-800',@Libelle='*STAGIAIRE ENCADREMENT'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='10',@Code='10-900',@Libelle='*ENCADREMENT AUTRE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='11',@Code='11-100',@Libelle='*CHEF D''EQUIPE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='11',@Code='11-200',@Libelle='*CONDUCTEUR D''ENGIN/CHAUFFEUR'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='11',@Code='11-300',@Libelle='*OUVRIER '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='11',@Code='11-600',@Libelle='*MECANICIEN/ELECTRICIEN'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='11',@Code='11-800',@Libelle='*STAGIAIRE OUVRIER'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='11',@Code='11-900',@Libelle='*MO DIRECTE AUTRE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='12',@Code='12-100',@Libelle='*VETEMENTS DE TRAVAIL'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='12',@Code='12-200',@Libelle='*AUTRES FRAIS DE PERSONNEL'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='12',@Code='12-300',@Libelle='*FORMATION'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='20',@Code='21-100',@Libelle='*MATERIEL INSTALLATION'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='20',@Code='22-100',@Libelle='*MATERIEL TERRASSEMENT'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='20',@Code='22-200',@Libelle='*CAMIONS'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='20',@Code='22-300',@Libelle='*MATERIEL GENIE CIVIL'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='20',@Code='22-400',@Libelle='*MATERIEL FORAGE ET SOUTERRAINS'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='20',@Code='22-500',@Libelle='*MATERIEL LEVAGE et MANUTENTION'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='20',@Code='22-600',@Libelle='*MATERIEL ROUTE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='20',@Code='22-700',@Libelle='*MATERIEL CONCASSAGE'




-- AJOUT RESSOURCES
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-100',@Code='ENCA-01',@Libelle='*DIRECTEUR',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-105',@Code='ENCA-05',@Libelle='*CONDUCTEUR DE TRAVAUX',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-110',@Code='ENCA-10',@Libelle='*CHEF DE CHANTIER',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-200',@Code='ENCA-15',@Libelle='*ETUDES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-300',@Code='ENCA-20',@Libelle='*QSE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-400',@Code='ENCA-25',@Libelle='*GÉOMÈTRE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-450',@Code='ENCA-30',@Libelle='*LABORATOIRE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-500',@Code='ENCA-35',@Libelle='*ADMINISTRATIFS',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-600',@Code='ENCA-40',@Libelle='*MÉCANIQUE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-800',@Code='ENCA-45',@Libelle='*STAGIAIRE ENCADREMENT',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-900',@Code='ENCA-50',@Libelle='*INTÉRIM ENCADREMENT',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-900',@Code='ENCA-60',@Libelle='*PRÊT DE MO ENCADREMENT ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-900',@Code='ENCA-90',@Libelle='*AUTRE MO ENCADREMENT',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-900',@Code='ENCA-98',@Libelle='*OD INTERIM ENCADREMENT',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10-900',@Code='ENCA-99',@Libelle='*OD MO ENCADREMENT',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-100',@Code='MO-01',@Libelle='*CHEF D''EQUIPE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-200',@Code='MO-05',@Libelle='*CONDUCTEUR D''ENGIN',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-200',@Code='MO-10',@Libelle='*CHAUFFEUR',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-300',@Code='MO-15',@Libelle='*OUVRIER ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-300',@Code='MO-20',@Libelle='*MANŒUVRE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-600',@Code='MO-30',@Libelle='*MÉCANICIEN',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-600',@Code='MO-35',@Libelle='*ELECTRICIEN',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-800',@Code='MO-45',@Libelle='*STAGIAIRE PRODUCTION',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-900',@Code='MO-50',@Libelle='*INTÉRIM PRODUCTION',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-900',@Code='MO-60',@Libelle='*PRÊT DE MO DE PRODUCTION',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-900',@Code='MO-90',@Libelle='*AUTRE MO DE PRODUCTION',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-900',@Code='MO-98',@Libelle='*OD MO INTERIM',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11-900',@Code='MO-99',@Libelle='*OD MO PRODUCTION',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='ASCEN-001',@Libelle='*ASCENCEUR',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='ATELI-1661',@Libelle='*HANGAR ATELIER BATEX',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='BUNGA-1511',@Libelle='*BUNGALOW BUREAU',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='BUNGA-1610',@Libelle='*BUNGALOW SANITAIRE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='BUNGA-1640',@Libelle='*BUNGALOW  VESTIAIRE/REFECTOIRE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='BUNGA-1641',@Libelle='*BUNGALOW LABORATOIRE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CLOTU-01',@Libelle='*CLÖTURES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CONTE-1215',@Libelle='*CONTENEUR ENVIRONNEMENT',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CONTE-1503',@Libelle='*CONTENEUR REMORQUE AMENAGE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CONTE-1530',@Libelle='*CONTAINER ATELIER',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CONTE-1550',@Libelle='*CONTAINER GRAISSAGE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CONTE-1570',@Libelle='*CONTAINER MAGASIN',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CONTE-1571',@Libelle='*CONTAINER VIDE POUR STOCKAGE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CONTE-1572',@Libelle='*CONTENEUR  SECURITE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CONTE-001',@Libelle='*CONTENEUR',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='CUVE-1051',@Libelle='*CUVE CARBURANT ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='ESCAL-001',@Libelle='*ESCALIER',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='RADIO-001',@Libelle='*RADIO ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='ECHAF-001',@Libelle='*ECHAFFAUDAGES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='PONT-1861',@Libelle='*PONT BASCULE ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='SILO-001',@Libelle='*SILOS',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='TOUR-8201',@Libelle='*TOUR ET MAT DECLAIRAGE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='TOUR-8250',@Libelle='*TOUR D''ECLAIRAGE SECTEUR',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21-100',@Code='TREMI-2771',@Libelle='*TREMIE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='AUTOG-001',@Libelle='*AUTOGRADE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BRH-0654',@Libelle='*MARTEAU BRISE ROCHE 200 A 300KG',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BRH-0657',@Libelle='*MARTEAU BRISE ROCHE 600/1000KG',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BRH-0660',@Libelle='*MARTEAU BRISE ROCHE 1000 KG MAXI',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BRH-0661',@Libelle='*MARTEAU BRH 1000 A 2500 KG',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BRH-0672',@Libelle='*MARTEAU BRH 2500 A 3500 KG',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BULL-4461',@Libelle='*TRACTEUR SUR CHENILLES TYPE D5K',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BULL-4487',@Libelle='*TRACTEUR CHENILLES TYPE D6K LGP',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BULL-4492',@Libelle='*TRACTEUR CHENS TYPE D6R RIPPER',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BULL-4501',@Libelle='*TRACTEUR CHENILLES TYPE D6R LGP',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BULL-4515',@Libelle='*TRACTEUR CHENS TYPE D7R RIPPER',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='BULL-4532',@Libelle='*TRACTEUR CHENS TYPE D8R RIPPER',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4651',@Libelle='*CHARGEUR COMPACT PNEUS TYPE 246',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4652',@Libelle='*CHARGEUR COMPACT PNEUS TYPE 226',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4653',@Libelle='*CHARG COMPACT PNEUS, 2,6 T+ACC',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4654',@Libelle='*CHARGEUR COMPACT S/PNEUS TYP 262',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4661',@Libelle='*CHARGEUSE SUR PNEU TYPE 906',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4672',@Libelle='*CHARGEUR SUR PNEU TYPE 928/938',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4682',@Libelle='*CHARGEUR SUR PNEU TYPE 950/L120',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4693',@Libelle='*CHARGEUR SUR PNEU TYPE 966/L150',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4701',@Libelle='*CHARGEUR SUR PNEU TYPE 980',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4741',@Libelle='*CHARGEUSE SUR CHENILLES < 943',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4761',@Libelle='*CHARGEUSE SUR CHENILLES TYPE 953',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4771',@Libelle='*CHARGEUSE SUR CHENILLES TYPE 963',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4796',@Libelle='*CHARGEUSE PELLETEUSE 80-100 CV',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='CHARG-4798',@Libelle='*CHARGEUSE PELLETEUSE 90-110CV',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7609',@Libelle='*PLAQUE VIBRANTE REVERSIBL BPH80',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7620',@Libelle='*PLAQUE VIBRANTE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7660',@Libelle='*COMPACTEUR VIBR TANDEM 75 A 90 CM',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7661',@Libelle='*COMPACTEUR VIBR & GUID TELECOMM',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7750',@Libelle='*COMPACTEUR VIBRANT TANDEM 90CM',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7751',@Libelle='*COMPACTEUR VIBRANT TANDEM 100CM',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7754',@Libelle='*COMPACTEURVIBR TANDEM 100 A 120 CM',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7763',@Libelle='*COMPACTEUR VIBR TANDEM 8 A 10 T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7766',@Libelle='*COMPACTEUR VIBRANT TANDEM 10 A 13T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7781',@Libelle='*COMPACTEUR BW213 SANS VARIO CONTROL',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7782',@Libelle='*COMPACTEUR VIBRANT MONOBILLE 8-10T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7785',@Libelle='*COMPACTEUR VIBR MONOBILLE 12 A 15T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7790',@Libelle='*COMPACTEUR VIBRANT MONOBILLE 16-18T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7795',@Libelle='*COMPACTEUR VIBRANT MONOBILLE 19-21T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7800',@Libelle='*COMPACTEUR VIBR MONOBILL+VARIO CTRL',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7851',@Libelle='*COMPACTEUR SUR PNEU P1 3T/ROUE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='COMPA-7880',@Libelle='*COMPACTEUR SUR PNEU P3 5T/ROUE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='DECAP-015',@Libelle='*DECAPEUSE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='DUMPE-4801',@Libelle='*MINI DUMPER 2,5T)',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='DUMPE-4802',@Libelle='*DUMPER GRAVILLONNEUR',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='DUMPE-4807',@Libelle='*DUMPER RIGIDE CU 28 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='DUMPE-4812',@Libelle='*DUMPER RIGIDE CU 36 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='DUMPE-4896',@Libelle='*DUMPER ARTICULE CU 30 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='DUMPE-4922',@Libelle='*DUMPER ARTICULE B40',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='NIVEL-4956',@Libelle='*NIVELEUSE TYPE INF 120',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='NIVEL-4960',@Libelle='*NIVELEUSE TYPE 120',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='NIVEL-4966',@Libelle='*NIVELEUSE TYPE 12',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='NIVEL-4973',@Libelle='*NIVELEUSE TYPE 140',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='NIVEL-4979',@Libelle='*NIVELEUSE TYPE 14',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4003',@Libelle='*PELLE A CABLE 130T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4046',@Libelle='*MINIPELLE 2.5T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4048',@Libelle='*MINI PELLE SUR CHEN 5.3T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4051',@Libelle='*PELLE SUR CHENILLES 7 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4116',@Libelle='*PELLE SUR PNEUS 15-16 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4122',@Libelle='*PELLE SUR PNEUS 17-22 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4125',@Libelle='*PELLE SUR PNEUS 12-15 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4130',@Libelle='*PELLE SUR PNEUS 12-15 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4236',@Libelle='*PELLE SUR CHENILLES 15-17 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4262',@Libelle='*PELLE SUR CHENILLES 18-23 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4306',@Libelle='*PELLE SUR CHENILLES 24-27 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4331',@Libelle='*PELLES SUR CHENILLE 28-37 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4333',@Libelle='*EQUIPEMENT BRAS LONG 18M',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4334',@Libelle='*EQUIPEMENT BRAS LONG 15M',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4342',@Libelle='*PELLES SUR CHENILLE 38-45 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4365',@Libelle='*PELLES SUR CHENILLE 46-58 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4384',@Libelle='*PELLE SUR CHENILLE CARR. 60-70T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PELLE-4388',@Libelle='*PELLE SUR CHEN DE CARR. 71-87T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='TRACTO-001',@Libelle='*TRACTOPELLE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='PILON-7601',@Libelle='*PILONNEUSE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='SCRAP-4639',@Libelle='*MOTORSCRAPEUR ELEVATEUR615C',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='SCRAP-4643',@Libelle='*MOTORSCRAPER ELEVATEUR TYPE 623',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='TAMPI-7551',@Libelle='*TAMPING 21 TONNES (815)',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='TAMPI-7580',@Libelle='*TAMPING 32 TONNES (825)',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='TRACT-4592',@Libelle='*TRACTEUR AGRICOLE 4X2 80-100 CV',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='TRACT-4593',@Libelle='*TRACTEUR AGRICOLE 4X4 80-100 CV',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-100',@Code='TRACT-4595',@Libelle='*TRACTEUR AGRICOLE 4X4 150-200 CV',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5101',@Libelle='*CAMION 4X2 BENNE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5102',@Libelle='*CAMION 4X2 TRIBENNE 8M3',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5105',@Libelle='*CAMION 4X2 BENNE GRUE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5115',@Libelle='*CAMION 6X4 BENNE ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5116',@Libelle='*CAMION 6X4 TRI-BENNE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5117',@Libelle='*CAMION 6X4 BENNE  GRUE ',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5120',@Libelle='*CAMION 6X6 BENNE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5130',@Libelle='*CAMION 8X4 BENNE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5132',@Libelle='*CAMION 8X4 AVEC BENNE CARRIERE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5133',@Libelle='*CAMION 8X4 BENNE TERRASS',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5170',@Libelle='*CAMION INTERVENTION ATELIER',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5205',@Libelle='*BUS TRANSPORT PERSONNEL 25-30 PLACES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5206',@Libelle='*BUS TRANSPORT PERSONNEL 50PL',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5260',@Libelle='*CAMION 4X4 CITERNE FOD 11M3',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5275',@Libelle='*CAMION 4X2  CITERNE EAU - ARROSEUSE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5285',@Libelle='*CAMION 6X4 CITERNE EAU 22M3',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5330',@Libelle='*SEMI BANANE CIMENT 25-30 TONNES',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5331',@Libelle='*SEMI STOCKAGE PULVE PETITE CAPACITE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5410',@Libelle='*CAMION 4X4 STATION GRAISSAGE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5501',@Libelle='*CAMION 6X4 TOUPIE 7M3',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5503',@Libelle='*CAMION 8X4 TOUPIE BETON 7M3',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5504',@Libelle='*CAMION 6X4 MALAXEUR 9M3',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5551',@Libelle='*BALAYEUSE ASPIR 4M3 PORT. 4X2',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5601',@Libelle='*CAMION 4X2 PLATEAU',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5605',@Libelle='*CAMION 4X2 PLATEAU & GRUE AUX',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5606',@Libelle='*CAMION 4X2 BEN DEVT LAT+GRUE AUX',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5627',@Libelle='*CAMION 6X4 PLATEAU GRUE AUXILIAIRE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5651',@Libelle='*SEMI BENNE 22 M3',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5680',@Libelle='*SEMI PLATEAU 12-13M , 24-28 T CU',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5691',@Libelle='*SEMI PORTE ENGIN 50-55 TONNES CU',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5694',@Libelle='*REMORQUE PORTE TOURET',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5695',@Libelle='*REMORQUE PORTE ENGIN 6-10T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5696',@Libelle='*REMORQUE PORTE ENGIN CU INF 5T',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5699',@Libelle='*REMORQUE AGRICOLE 8-10 T CU',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5701',@Libelle='*CAMION ESSAI DE PLAQUE',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5751',@Libelle='*TRACTEUR ROUTIER 4X2',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5760',@Libelle='*TRACTEUR ROUTIER 6X4',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-200',@Code='CAMIO-5765',@Libelle='*TRACTEUR ROUTIER 6X6',@Type='Personnel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='22-300',@Code='BANCH-001',@Libelle='*BANCHES',@Type='Personnel'




EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='60000',@Libelle='Nature 1'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='70000',@Libelle='Nature 2'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='70356',@Libelle='Nature 3'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='70712',@Libelle='Nature 4'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='71068',@Libelle='Nature 5'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='71424',@Libelle='Nature 6'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='71780',@Libelle='Nature 7'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='72136',@Libelle='Nature 8'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='72492',@Libelle='Nature 9'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='72848',@Libelle='Nature 10'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='73204',@Libelle='Nature 11'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='73560',@Libelle='Nature 12'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='73916',@Libelle='Nature 13'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='74272',@Libelle='Nature 14'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='74628',@Libelle='Nature 15'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='74984',@Libelle='Nature 16'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='75340',@Libelle='Nature 17'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='75696',@Libelle='Nature 18'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='76052',@Libelle='Nature 19'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='76408',@Libelle='Nature 20'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='76764',@Libelle='Nature 21'
EXEC Fred_ToolBox_Nature @GroupeCode='GFES',@SocieteCode='E001',@Code='77120',@Libelle='Nature 22'


EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GFES',@SocieteCode='E001',@Achats='Oui',@RessourceCode='ENCA-15',@NatureCode='E001'
EXEC Fred_Toolbox_Nature_Ressources @GroupeCode='GFES',@SocieteCode='E001',@Achats='Oui',@RessourceCode='ENCA-30',@NatureCode='E001'


*/