

-- SUPPRESSION DES CHAPITRES DE TESTS PRECEDEMENTS INJECTES DANS LE FICHIER 00030_FRED_GFES_RESSOURCES_V3.sql
--  ----------------------------------------------------------

declare @groupid int;
set @groupid = (select GroupeId from FRED_GROUPE where Code='GFES')
--select * from FRED_CHAPITRE  where GroupeId = @groupid
--select * from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)
--select * from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid))
--select * from FRED_SOCIETE_RESSOURCE_NATURE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
--select * from FRED_PERSONNEL where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
--select * from FRED_COMMANDE_LIGNE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
--select BudgetT4SousDetailId from FRED_BUDGET_T4_RESSOURCE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
--select AvancementId from FRED_AVANCEMENT where BudgetSousDetailId in (select BudgetT4SousDetailId from FRED_BUDGET_T4_RESSOURCE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid))))
--select * from FRED_AVANCEMENT_WORKFLOW where AvancementId in (select AvancementId from FRED_AVANCEMENT where BudgetT4SousDetailId in 

delete from FRED_AVANCEMENT_WORKFLOW where AvancementId in (select AvancementId from FRED_AVANCEMENT where BudgetSousDetailId in (select BudgetT4SousDetailId from FRED_BUDGET_T4_RESSOURCE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))))
delete from FRED_COMMANDE_LIGNE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
update FRED_PERSONNEL set RessourceId = null where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
delete from FRED_SOCIETE_RESSOURCE_NATURE where RessourceId in (select RessourceId from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)))
delete from FRED_RESSOURCE where SousChapitreId in (select SousChapitreId from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid))
delete from FRED_SOUS_CHAPITRE where ChapitreId in (select ChapitreId from FRED_CHAPITRE  where GroupeId = @groupid)
delete from FRED_CHAPITRE  where GroupeId = @groupid




-- --------------------------------------------------
-- INJECTION DES CHAPITRES
-- --------------------------------------------------
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='EIMATERIEL',@Libelle='Matériel'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='EIOUTILLAGE',@Libelle='Outillage'
EXEC Fred_ToolBox_Chapitre @GroupeCode='GFES',@Code='EIROULANT',@Libelle='Véhicule'




-- --------------------------------------------------
-- INJECTION DES SOUS-CHAPITRES
-- --------------------------------------------------
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10000',@Libelle='Famille Mesure'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10100',@Libelle='Analyseur d énergie'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10200',@Libelle='Analyseur enregistreur harmonique'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10300',@Libelle='Caméra thermo graphique'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10400',@Libelle='Contrôleur bipolaire HTA'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10500',@Libelle='Tellurohmètre contrôleur de terre '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10600',@Libelle='Megohmetre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10600',@Libelle='Megohmetre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10700',@Libelle='Contrôleur VAT'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10800',@Libelle='Appareil photo numérique '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='10900',@Libelle='Détecteur canalisations ecchoM'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11000',@Libelle='Détecteur de câbles'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11100',@Libelle='détecteur de métaux'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11200',@Libelle='Dynamomètre de traction'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11300',@Libelle='Luxmètre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11400',@Libelle='Lasermetre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11500',@Libelle='Multimètre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11600',@Libelle='Multi testeur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11700',@Libelle='Ohmmètre de boucle '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11800',@Libelle='Oscilloscope'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='11900',@Libelle='Pince ampéremétrique'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='12000',@Libelle='Topomètre / odomètre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='12100',@Libelle='Vérificateur de réseaux info wirescope'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='12200',@Libelle='Sonometre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='12300',@Libelle='Cle dynamometrique'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='12400',@Libelle='Reflectometre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='12500',@Libelle='Anemometre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='12600',@Libelle='Spectrosonde'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='12700',@Libelle='Calibrateur 4/20'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='13000',@Libelle=' Mesureur de câble'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='13100',@Libelle='Thermohygrometre '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='13200',@Libelle='Mesureur de vibration'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='13300',@Libelle='Dielectrometre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='13400',@Libelle='Calibreur de pression'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='13500',@Libelle='PRELEVEUR D ECHANTILLONS ASSAINISSEMENT'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20000',@Libelle='Famille Perfo Sciage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20100',@Libelle='Visseuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20200',@Libelle='Meuleuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20300',@Libelle='Perceuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20400',@Libelle='Perforateur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20500',@Libelle='Ponceuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20600',@Libelle='Scie circulaire'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20700',@Libelle='Scie sabre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20800',@Libelle='Scie sauteuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='20900',@Libelle='Tronçonneuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='21000',@Libelle='Burineur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='21100',@Libelle='Carotteuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='21200',@Libelle='Brise béton '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='21300',@Libelle='Marteau piqueur autonome'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='21400',@Libelle='Marteau piqueur '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='21500',@Libelle='Rainureuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='21600',@Libelle='Scie à sol'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='30000',@Libelle='Famille Installation chantier'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='30100',@Libelle='Coffre à outillage '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='30200',@Libelle='Coffret électrique de chantier'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='30300',@Libelle='Frigo'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='30400',@Libelle='Glacière'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='30500',@Libelle='Micro ondes'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='30600',@Libelle='Tente'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='30700',@Libelle='Etabli   eteau'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='30800',@Libelle='Vestiaire'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='30900',@Libelle='Compresseur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='31000',@Libelle='Aerotherme'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='31100',@Libelle='Groupe électrogène'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='31200',@Libelle='Climatisation'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='31300',@Libelle='Sono/multimedia'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='31400',@Libelle='Bungalows containers'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='31500',@Libelle='Benne'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='31600',@Libelle='Compacteur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='31700',@Libelle='Extracteur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='31900',@Libelle='Cone panneau signalisation'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40000',@Libelle='Famille Manut Transport'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40100',@Libelle='Chariot diable'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40200',@Libelle='hOME TRAINER'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40300',@Libelle='Chariot dérouleur de touret'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40400',@Libelle='Diables élévateurs jumelés'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40500',@Libelle='vérin de déroulage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40600',@Libelle='Porte charge monte escaliers'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40700',@Libelle='Rouleurs de fortes charges'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40800',@Libelle='Dérouleur de gaine'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='40900',@Libelle='Galet'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='41000',@Libelle='Palans'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='41100',@Libelle='Tirefort'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='41200',@Libelle='Treuil'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='41300',@Libelle='Transpalette'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='41400',@Libelle='Aiguille fibre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='41500',@Libelle='Leve tampon'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='41600',@Libelle='Rampe '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='41700',@Libelle='Porteuse pneumatique'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='41800',@Libelle='Dérouleuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='41900',@Libelle='Chariot élévateur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='42000',@Libelle='Remorque'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='43000',@Libelle='Potence'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50000',@Libelle='Famille Outillage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50100',@Libelle='Cintreuse '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50200',@Libelle='Filliere'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50300',@Libelle='Enrouleur rallonge'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50400',@Libelle='Clé a choc'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50500',@Libelle='Cloueuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50600',@Libelle='Coffret à dénuder HT/BT'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50700',@Libelle='Coffret à douilles'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50800',@Libelle='Coffret à cliquet'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='50900',@Libelle='Coffret de mise à la terre " BT aérien " '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='51000',@Libelle='Etiqueteuse'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60000',@Libelle='Famille Soudure'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60100',@Libelle='Poste à souder '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60200',@Libelle='Chariot chalumeau découpeur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60300',@Libelle='Chariot chalumeau '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60400',@Libelle='Poste TIG'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60500',@Libelle='Soudeuse bobine fb opt. '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60600',@Libelle='Decap thermique'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60700',@Libelle='Furet thermo'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='60800',@Libelle='Soudure ensemble Flasch GAZ'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70000',@Libelle='Famille Sertissage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70100',@Libelle='Pince à sertir mamuelle'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70200',@Libelle='Pince à sertir électrique '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70300',@Libelle='Pompe à sertir (20T)'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70400',@Libelle='Coffret sertissage cuivre '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70500',@Libelle='Coffret sertissage alu'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70600',@Libelle='Coupe câble '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70700',@Libelle='Emporte pièces'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70800',@Libelle='Presse à sertir'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='70900',@Libelle='groupe hydraulique pour presse à sertir'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80000',@Libelle='Famille Securité'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80100',@Libelle='Détecteur gaz'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80200',@Libelle='Entourage egout'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80300',@Libelle='Emetteur récepteur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80400',@Libelle='Masque autosauveteur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80500',@Libelle='Gilet sauvetage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80600',@Libelle='Tripod   acces'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80700',@Libelle='Feux tricolore'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80800',@Libelle='Projecteur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='80900',@Libelle='Lampe frontale'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='81000',@Libelle='Harnais'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='81100',@Libelle='Trousse TST'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='81200',@Libelle='Bouée'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='81300',@Libelle='Perche Malt 63/90-225/420K'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='90000',@Libelle='Famille Travail Hauteur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='90100',@Libelle='Echafaudage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='90200',@Libelle='Echelles'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='90300',@Libelle='Escabeau'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='90400',@Libelle='PIR '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='90500',@Libelle='Nacelle'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='90600',@Libelle='Echafaudage emissaire'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='100000',@Libelle='Famille Nettoyage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='100100',@Libelle='Aspirateur chantier'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='100200',@Libelle='Nettoyeur haute pression '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='100300',@Libelle='Pompe à eau '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='100400',@Libelle='Pompe de relevage '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='100500',@Libelle='AUTOLAVEUSE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110000',@Libelle='Famille Gros Oeuvre'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110100',@Libelle='Barrières'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110200',@Libelle='Fonceur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110300',@Libelle='Moto pompe '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110400',@Libelle='Passerelles'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110500',@Libelle='Pont lourd'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110600',@Libelle='Betonniere'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110700',@Libelle='Etais'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110800',@Libelle='Compactage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='110900',@Libelle='Aerateur d egout'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='111000',@Libelle='Obturateur d egout'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='111100',@Libelle='Pelles '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='111200',@Libelle='Leve poteau QUATTRO'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIMATERIEL',@Code='111300',@Libelle='Tracteur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='111600',@Libelle='BLINDAGES KVL'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='120000',@Libelle='Famille Divers'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='120100',@Libelle='Meche  '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='120200',@Libelle='Couronne '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='120300',@Libelle='Recharge gaz'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='120400',@Libelle='Disque diamant'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='130100',@Libelle='Atelier serrurerie peinture'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIOUTILLAGE',@Code='140100',@Libelle='Atelier Garage'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='ABOMAT',@Libelle='Abonnements Matériels'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='BENNE',@Libelle='FOURGONS BENNE'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='BENNEGRUE',@Libelle='FOURGONS BENNE GRUE '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='CONVOY',@Libelle='Convoyage de véhicules IDF'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='CTTE1',@Libelle='Camionettes léger1'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='CTTE2',@Libelle='Camionettes Utilitaires2'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='ENGINSPEC',@Libelle='ENGINS SPECIAUX PL'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='FOURGON',@Libelle='FOURGONS'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='GEOLOC',@Libelle='Abonnements géolocalisation DAM S'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='GY',@Libelle='Gyropode'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='LOCATEXTM',@Libelle='Location extérieure MO Chauffeurs'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='LOCEXTCTTE',@Libelle='Loc Ext - CTTE '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='LOCEXTNAC',@Libelle='Loc Ext - Nacelles'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='LOCEXTPL',@Libelle='Loc Ext - PL '
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='LOCEXTVL',@Libelle='Loc Ext - VL'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='NACELLE',@Libelle='NACELLES VL'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='PL',@Libelle='Poids lourds'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='TM',@Libelle='Tricycle à Moteur'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='VL',@Libelle='Véhicule légers'
EXEC Fred_ToolBox_SousChapitre @GroupeCode='GFES',@ChapitreCode='EIROULANT',@Code='VP',@Libelle='Véhicules particuliers'








-- AJOUT RESSOURCES
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='106',@Libelle='106',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='206',@Libelle='206',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='207',@Libelle='207',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='208',@Libelle='Peugeot 208',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='307',@Libelle='307',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='308',@Libelle='Peugeot 308',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCATEXTM',@Code='1000',@Libelle='1000 Locatext MO Chauffeur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTVL',@Code='1500',@Libelle='1500 (Clio sté / C2 sté)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTCTTE',@Code='1511',@Libelle='1511 (kangoo)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTCTTE',@Code='1512',@Libelle='1512 (Jumpy / Traffic)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTCTTE',@Code='1520',@Libelle='1520 (Jumper)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTCTTE',@Code='1521',@Libelle='1521 (Benne) ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTCTTE',@Code='1522',@Libelle='1522 (Benne grue)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTPL',@Code='1530',@Libelle='1530 (10T grue)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTNAC',@Code='1532',@Libelle='1532 (Nacelle 16m plateau)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTNAC',@Code='1533',@Libelle='1533 (Nacelle Topy 10m) ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTNAC',@Code='1534',@Libelle='1534 (Nacelle fourgon 11m)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTPL',@Code='1535',@Libelle='1535 (15T grue)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTPL',@Code='1536',@Libelle='CAMION PORTE POTEAUX ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='LOCEXTPL',@Code='1537',@Libelle='PL 19T GRUE 8x4',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10000',@Code='10000',@Libelle='Achat Mesure',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10100',@Code='10110',@Libelle='Analyseur d énergie',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10200',@Code='10210',@Libelle='Analyseur enregistreur harmonique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10300',@Code='10310',@Libelle='Caméra thermo graphique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10300',@Code='10320',@Libelle='Caméra de contrôle thermo graphique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10400',@Code='10410',@Libelle='Contrôleur bipolaire HTA',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10500',@Code='10510',@Libelle='Tellurohmetre contrôleur de terre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10600',@Code='10610',@Libelle='Megohmetre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10600',@Code='10620',@Libelle='Controleur d isolement',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10700',@Code='10710',@Libelle='Contrôleur VAT',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10700',@Code='10711',@Libelle='Contrôleur VAT HT',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10800',@Code='10810',@Libelle='Appareil photo numérique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='10900',@Code='10910',@Libelle='Détecteur canalisations ecchoM',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11000',@Code='11010',@Libelle='Détecteur de câbles',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11100',@Code='11110',@Libelle='Détecteur de métaux',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11200',@Code='11210',@Libelle='Dynamomètre de traction',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11300',@Code='11310',@Libelle='Luxmètre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11300',@Code='11320',@Libelle='Luxmetre Cartographie',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11400',@Code='11410',@Libelle='Lasermetre metrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11400',@Code='11420',@Libelle='Lasermetre Niveau',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11400',@Code='11430',@Libelle='Lasermetre Rotatif',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11500',@Code='11510',@Libelle='Multimetre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11500',@Code='11520',@Libelle='Multimetre   Pince ampermetrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11500',@Code='11530',@Libelle='Controleur differentiel',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11600',@Code='11610',@Libelle='Multi testeur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11700',@Code='11710',@Libelle='Ohmmètre de boucle',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11800',@Code='11810',@Libelle='Oscilloscope',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11900',@Code='11910',@Libelle='Pince Amp. 200 A',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='11900',@Code='11920',@Libelle='Pince Amp. 400A',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12000',@Code='12010',@Libelle='Topomètre / odomètre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12100',@Code='12110',@Libelle='Vérificateur de réseaux info wirescope',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12100',@Code='12120',@Libelle='Testeur réseaux',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12200',@Code='12210',@Libelle='Sonometre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12300',@Code='12310',@Libelle='Cle dynamometrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12400',@Code='12410',@Libelle='Reflectometre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12400',@Code='12420',@Libelle='Accessoire reflect. Bobine amorce',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12500',@Code='12510',@Libelle='Anemometre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12600',@Code='12610',@Libelle='Spectrosonde',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='12700',@Code='12710',@Libelle='Calibrateur 4/20',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='13000',@Code='13010',@Libelle='Mesureur de cable',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='13100',@Code='13110',@Libelle='thermohygrometre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='13200',@Code='13210',@Libelle='Mesureur de vibration',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='13300',@Code='13310',@Libelle='Dielectrometre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='13400',@Code='13410',@Libelle='Calibreur de pression',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='13500',@Code='13510',@Libelle='PRELEVEUR AUTONOME MULTIFLACONS ISOTHERME',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='13500',@Code='13520',@Libelle='DEBITMETRE D ECHANTILLON AUTONOME MAINFLOW',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='13500',@Code='13530',@Libelle='CAPTEUR ODEON',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20000',@Code='20000',@Libelle='Achat Perfo Sciage',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20100',@Code='20110',@Libelle='Visseuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20200',@Code='20210',@Libelle='Meuleuse diam 125',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20200',@Code='20211',@Libelle='Meuleuse diam 125 accu',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20200',@Code='20220',@Libelle='Meuleuse diam 230',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20200',@Code='20230',@Libelle='Meuleuse diam 230 pneumatic',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20200',@Code='20240',@Libelle='Meuleuse diam 300 pneumatic',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20300',@Code='20310',@Libelle='Perceuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20400',@Code='20410',@Libelle='Perfo autonome',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20400',@Code='20420',@Libelle='Perfo filaire moyenne puissance',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20400',@Code='20430',@Libelle='Perfo filaire forte puissance',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20400',@Code='20440',@Libelle='Perfo Amiante',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20500',@Code='20510',@Libelle='Ponceuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20600',@Code='20610',@Libelle='Scie circulaire',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20700',@Code='20710',@Libelle='Scie sabre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20800',@Code='20810',@Libelle='Scie sauteuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='20900',@Code='20910',@Libelle='Tronçonneuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21000',@Code='21010',@Libelle='Burineur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21100',@Code='21110',@Libelle='Carotteuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21200',@Code='21210',@Libelle='Brise béton',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21300',@Code='21310',@Libelle='Marteau piqueur autonome',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21400',@Code='21410',@Libelle='Marteau piqueur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21400',@Code='21415',@Libelle='Marteau piqueur électrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21500',@Code='21510',@Libelle='Rainureuse beton',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21500',@Code='21520',@Libelle='Rainureuse platre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21600',@Code='21610',@Libelle='Scie de sol manuelle',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21600',@Code='21620',@Libelle='Scie de sol autoportée',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='21600',@Code='21630',@Libelle='Scie de sol pneumatique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30000',@Code='30000',@Libelle='Achat Installation Chantier',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30100',@Code='30110',@Libelle='Coffre de chantier 1000x800x600',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30100',@Code='30120',@Libelle='Coffre de chantier 2000x1000x1000',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30200',@Code='30210',@Libelle='Coffret électrique de chantier',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30300',@Code='30310',@Libelle='Frigo',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30400',@Code='30410',@Libelle='Glacière',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30500',@Code='30510',@Libelle='Micro ondes',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30600',@Code='30610',@Libelle='Tente',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30700',@Code='30710',@Libelle='Etabli   eteau',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30800',@Code='30810',@Libelle='Vestiaire',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30900',@Code='30910',@Libelle='Compress compact air',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='30900',@Code='30920',@Libelle='Compresseur 8à 10bars',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31000',@Code='31010',@Libelle='Aerotherme 3000 W',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31000',@Code='31020',@Libelle='Aerotherme 5000 W',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31000',@Code='31030',@Libelle='Aerotherme 12000 W',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31100',@Code='31110',@Libelle='Grp elec ess <2.4KVA',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31100',@Code='31120',@Libelle='Grp elec ess 4KVA',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31100',@Code='31130',@Libelle='Grp elec ess >7KVA',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31100',@Code='31140',@Libelle='Grp elec GO  7KVA',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31100',@Code='31150',@Libelle='Grp elec 100KVA',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31100',@Code='31160',@Libelle='Grp elec 15KVA',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31200',@Code='31210',@Libelle='Climatisation',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31300',@Code='31310',@Libelle='Sono',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31300',@Code='31320',@Libelle='video projecteur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31410',@Libelle='Bungalows vestiaire',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31420',@Libelle='Bungalows bureau',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31430',@Libelle='Bungalow sanitaire',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31440',@Libelle='Bungalow réfectoire',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31450',@Libelle='Bungalow mixte (vest / refect)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31455',@Libelle='WC chimique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31460',@Libelle='Container 10 pieds',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31470',@Libelle='Container 20 pieds',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31480',@Libelle='Container 40 pieds',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31400',@Code='31490',@Libelle='Roulotte',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31500',@Code='31500',@Libelle='Benne 10m3',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31600',@Code='31600',@Libelle='Compacteur à déchets',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31700',@Code='31710',@Libelle='Extracteur air',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='31900',@Code='31910',@Libelle='Cone panneau signalisation',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40000',@Code='40000',@Libelle='Achat Manut Transport',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40100',@Code='40110',@Libelle='Chariot diable',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40100',@Code='40120',@Libelle='Gerbeur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40200',@Code='40210',@Libelle='Home trainer - 200 Kg',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40200',@Code='40220',@Libelle='Home trainer  200 à 800 Kg',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40200',@Code='40230',@Libelle='Home trainer  800 à 1.5 T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40300',@Code='40310',@Libelle='Chariot dérouleur de touret',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40400',@Code='40410',@Libelle='Diables élévateurs jumelés',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40500',@Code='40510',@Libelle='Vérin de déroulage >800 Kg',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40500',@Code='40520',@Libelle='Vérin de déroulage 800 Kg à 2 T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40600',@Code='40610',@Libelle='Porte charge monte escaliers',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40700',@Code='40710',@Libelle='Rouleurs de fortes charges',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40800',@Code='40810',@Libelle='Dérouleur de gaine',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='40900',@Code='40910',@Libelle='Galet',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41000',@Code='41010',@Libelle='Palans 1 T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41000',@Code='41020',@Libelle='Palans 3 T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41100',@Code='41110',@Libelle='Tirefort 0.8T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41100',@Code='41120',@Libelle='Tirefort 5T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41210',@Libelle='Treuil 0.5 T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41220',@Libelle='Treuil 1 T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41230',@Libelle='Treuil 2 T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41240',@Libelle='Treuil 3T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41250',@Libelle='Treuil 4T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41260',@Libelle='Treuil 0.3 T elec220v',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41270',@Libelle='Treuil 0.5 T elec 220v',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41280',@Libelle='Treuil 2 T elec 220v',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41200',@Code='41290',@Libelle='TREUIL 10T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41300',@Code='41310',@Libelle='Transpalette',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41400',@Code='41410',@Libelle='Aiguille 80 M',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41400',@Code='41420',@Libelle='Aiguille 200 M',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41400',@Code='41430',@Libelle='Aiguille 300M',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41400',@Code='41440',@Libelle='Aiguille vibrante autonome',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41400',@Code='41450',@Libelle='Corde sur touret',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41500',@Code='41510',@Libelle='Leve tampon',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41600',@Code='41610',@Libelle='Rampe',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41700',@Code='41710',@Libelle='Porteuse pneumatique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41800',@Code='41810',@Libelle='Dérouleuse 1T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41800',@Code='41820',@Libelle='Dérouleuse 1T5',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41800',@Code='41830',@Libelle='Dérouleuse 4T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41800',@Code='41840',@Libelle='Dérouleuse 5T5',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41800',@Code='41850',@Libelle='Dérouleuse 20T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='41900',@Code='41910',@Libelle='Chariot élévateur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='42000',@Code='42010',@Libelle='Remorque',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='42000',@Code='42020',@Libelle='Remorque basculante',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='42000',@Code='42030',@Libelle='Remorque plateau',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='43000',@Code='43010',@Libelle='Potence',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='43000',@Code='43020',@Libelle='Potence materiel',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50000',@Code='50000',@Libelle='Achat Outillage',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50100',@Code='50110',@Libelle='Cintreuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50200',@Code='50210',@Libelle='Filliere',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50300',@Code='50310',@Libelle='Enrouleur rallonge',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50400',@Code='50410',@Libelle='Clé a choc electrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50400',@Code='50420',@Libelle='Clé a choc pneumatique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50500',@Code='50510',@Libelle='Cloueuse electrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50500',@Code='50520',@Libelle='Cloueuse à gaz',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50600',@Code='50610',@Libelle='Coffret à dénuder HT/BT',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50700',@Code='50710',@Libelle='Coffret à douilles',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50800',@Code='50810',@Libelle='Coffret à cliquet',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='50900',@Code='50910',@Libelle='Coffret de mise à la terre «  BT aérien »',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='51000',@Code='51010',@Libelle='Etiqueteuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60000',@Code='60000',@Libelle='Achat Soudure',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60100',@Code='60110',@Libelle='Poste à souder',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60200',@Code='60210',@Libelle='Chariot chalumeau découpeur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60300',@Code='60310',@Libelle='Chariot chalumeau',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60400',@Code='60410',@Libelle='Poste TIG',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60500',@Code='60510',@Libelle='Soudeuse bobine fb opt.',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60600',@Code='60610',@Libelle='Decap thermique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60700',@Code='60710',@Libelle='Furet thermo',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='60800',@Code='60810',@Libelle='Soudure ensemble Flasch GAZ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70000',@Code='70000',@Libelle='Achat Sertissage',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70100',@Code='70110',@Libelle='Pince à sertir mamuelle',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70200',@Code='70210',@Libelle='Pince à sertir electrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70300',@Code='70310',@Libelle='Pompe à sertir (20T)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70400',@Code='70410',@Libelle='Coffret sertissage cuivre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70500',@Code='70510',@Libelle='Coffret sertissage alu',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70600',@Code='70610',@Libelle='Coupe câble a cliquet',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70600',@Code='70620',@Libelle='Coupe câble a chaine',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70600',@Code='70630',@Libelle='Coupe câble electrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70600',@Code='70640',@Libelle='Coupe câble hydraulique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70600',@Code='70650',@Libelle='Outil de coupe',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70700',@Code='70710',@Libelle='Emporte pièces',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70800',@Code='70810',@Libelle='Presse à sertir 100 tonnes',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70800',@Code='70820',@Libelle='Presse à sertir 20 Tonnes',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='70900',@Code='70910',@Libelle='Groupe hydraulique thermique pour presse à sertir',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80000',@Code='80000',@Libelle='Achat Securite',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80100',@Code='80110',@Libelle='Xam 2000',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80100',@Code='80120',@Libelle='Xam 2000 (ari)',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80100',@Code='80130',@Libelle='Xam 7000',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80100',@Code='80140',@Libelle='XAM 5000',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80200',@Code='80210',@Libelle='Entourage egout',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80300',@Code='80310',@Libelle='Talky Walky',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80300',@Code='80320',@Libelle='Accessoire longue porté',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80300',@Code='80330',@Libelle='Talky Walky ATEX',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80400',@Code='80410',@Libelle='Masque autosauveteur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80500',@Code='80510',@Libelle='Gilet sauvetage',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80600',@Code='80610',@Libelle='Tripod  acces',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80700',@Code='80710',@Libelle='Feux tricolore',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80800',@Code='80810',@Libelle='Projecteur pied  500W',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80800',@Code='80820',@Libelle='Projecteur Siroco 2000W',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80800',@Code='80830',@Libelle='Projecteur LED',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='80900',@Code='80910',@Libelle='Lampe frontale',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='81000',@Code='81010',@Libelle='Harnais Nacelle',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='81000',@Code='81020',@Libelle='Harnais Assainissement',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='81000',@Code='81030',@Libelle='Harnais Pylone',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='81100',@Code='81110',@Libelle='Trousse TST',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='81100',@Code='81120',@Libelle='Caisse boite edf',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='81200',@Code='81210',@Libelle='Bouée',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='81300',@Code='81310',@Libelle='Perche Malt 63/90-225/420K',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90000',@Code='90000',@Libelle='Achat Travail Hauteur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90100',@Code='90110',@Libelle='Echafaudage',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90200',@Code='90210',@Libelle='Echelles',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90300',@Code='90310',@Libelle='Escabeau 3 marches',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90300',@Code='90320',@Libelle='Escabeau 5 marches',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90300',@Code='90330',@Libelle='Escabeau 7 marches',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90300',@Code='90340',@Libelle='Escabeau 9 marches',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90400',@Code='90410',@Libelle='PIR 3/5 marches',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90400',@Code='90420',@Libelle='PIR 4/7 marches',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90400',@Code='90430',@Libelle='PIR 7/9 marches',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90500',@Code='90510',@Libelle='Nacelle',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='90600',@Code='90610',@Libelle='Echafaudage emissaire',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='100000',@Code='100000',@Libelle='Achat Nettoyage',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='100100',@Code='100110',@Libelle='Aspirateur chantier',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='100100',@Code='100120',@Libelle='Aspirateur Amiante',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='100200',@Code='100210',@Libelle='Nettoyeur haute pression electrique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='100200',@Code='100220',@Libelle='Nettoyeur haute pression thermique',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='100300',@Code='100310',@Libelle='Pompe a eau',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='100400',@Code='100410',@Libelle='Pompe de relevage',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='100500',@Code='100510',@Libelle='AUTOLAVEUSE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110000',@Code='110000',@Libelle='Achat Gros Oeuvre',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110100',@Code='110110',@Libelle='Barrières HERAS',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110100',@Code='110120',@Libelle='Barrières protection fouille',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110200',@Code='110210',@Libelle='Fonceur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110200',@Code='110220',@Libelle='Fusée 45',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110300',@Code='110310',@Libelle='Moto pompe',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110400',@Code='110410',@Libelle='Passerelles',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110500',@Code='110510',@Libelle='Pont lourd',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110600',@Code='110610',@Libelle='Betonniere',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110700',@Code='110710',@Libelle='Etais',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110800',@Code='110810',@Libelle='Dameuse / pilonneuse 80kg',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110800',@Code='110820',@Libelle='Plaque vibrante 300 kg / Pied de mouton',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='110900',@Code='110910',@Libelle='Aerateur d egout',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111000',@Code='111010',@Libelle='Obturateur d egout',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111100',@Code='111110',@Libelle='Pelle 2T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111100',@Code='111120',@Libelle='Pelle 2T5',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111100',@Code='111130',@Libelle='Pelle 12T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111100',@Code='111140',@Libelle='BRH',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111200',@Code='111210',@Libelle='Leve poteau QUATTRO',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111300',@Code='111310',@Libelle='Tracteur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111100',@Code='111320',@Libelle='TRACTO PELLE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='111600',@Code='111610',@Libelle='BLINDAGES KVL',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='120000',@Code='120000',@Libelle='Achat Divers',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='120100',@Code='120110',@Libelle='Meche',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='120200',@Code='120210',@Libelle='Couronne',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='120300',@Code='120310',@Libelle='Recharge gaz',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='120400',@Code='120410',@Libelle='Disque diamant',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='130100',@Code='130110',@Libelle='Perceuse sur pieds',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='130100',@Code='130120',@Libelle='Plieuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='130100',@Code='130130',@Libelle='Presse plieuse HAWA',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='130100',@Code='130140',@Libelle='Nettoyeur peinture',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='130100',@Code='130150',@Libelle='Aspirateur de fumée',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='130100',@Code='130160',@Libelle='Cisaille',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='130100',@Code='130170',@Libelle='Secheur d air',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='140100',@Code='140110',@Libelle='Pince dymo',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='140100',@Code='140120',@Libelle='Reglophare',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='140100',@Code='140130',@Libelle='Resculteur pneu',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='140100',@Code='140140',@Libelle='Equilibreuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='140100',@Code='140150',@Libelle='Balayeuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='140100',@Code='140160',@Libelle='Concept auto diagnostic',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='140100',@Code='140170',@Libelle='Demonte pneu',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ABOMAT',@Code='ABOMAT',@Libelle='Abonnements Matériels',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='PL',@Code='AMPLIROL15',@Libelle='Camion Amplirol 15 T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='BENNE',@Code='B100BENNE',@Libelle='B110 Benne ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='B110FOURG',@Libelle='B110 fourgon ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='PL',@Code='BENNE9T',@Libelle='Camion benne 9T',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE1',@Code='BERLINGO',@Libelle='Berlingo',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='BOXER',@Libelle='Boxer',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ENGINSPEC',@Code='BUS',@Libelle='Bus plateforme',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE1',@Code='C15',@Libelle='C15',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='C2',@Libelle='C2',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='C3',@Libelle='C3',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ENGINSPEC',@Code='CAMAYONNPC',@Libelle='Ravitailleur NPC',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ENGINSPEC',@Code='CAMAYONPIF',@Libelle='Ravitailleur PIF ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='PL',@Code='CAMBOUCLE',@Libelle='Camion Boucle',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ENGINSPEC',@Code='CAMDEP',@Libelle='Depanneuse',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ENGINSPEC',@Code='CAMPLATEF',@Libelle='Camion plateforme',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ENGINSPEC',@Code='CAMST',@Libelle='Camion TST',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ENGINSPEC',@Code='CAMTREUIL',@Libelle='Camion Treuil ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='CANTER',@Libelle='Canter',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='CLIO ',@Libelle='CLIO ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CONVOY',@Code='CONVOY',@Libelle='Convoyage de véhicules IDF',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='BENNE',@Code='DAILYBENNE',@Libelle='Daily benne',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='DAILYFOURG',@Libelle='Daily Fourgon ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='BENNEGRUE',@Code='DAILYGRUE',@Libelle='Daily benne grue',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='DUCATO ',@Libelle='Ducato ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE2',@Code='EXPERT',@Libelle='Expert ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='NACELLE',@Code='FOURGON11',@Libelle='Fourgon 11m',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='GEOLOC',@Code='GEOLOC',@Libelle='Abonnements géolocalisation DAM S',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='PL',@Code='GRUE10T',@Libelle='10T Grue ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='PL',@Code='GRUE15T',@Libelle='15T Grue',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='GY',@Code='GYROPODE',@Libelle='GYROPODE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='JUMPER',@Libelle='Jumper',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE2',@Code='JUMPY',@Libelle='Jumpy',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE1',@Code='KANGOO ',@Libelle='Kangoo',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='ENGINSPEC',@Code='LEVEPOTEAU',@Libelle='CAMION TARRIERE LEVE POTEAUX',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='LOGAN',@Libelle='DACIA LOGAN',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='MASCOTT',@Libelle='Mascott ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='MASTER',@Libelle='Master ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='BENNE',@Code='MAXITYBENN',@Libelle='Maxity Benne',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='MEGANE',@Libelle='MEGANE société',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='PL',@Code='NACELLEPL',@Libelle='Nacelle PL',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE1',@Code='NEMO',@Libelle='Nemo',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE1',@Code='PARTNER',@Libelle='Partner',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='PICASSO',@Libelle='Picasso',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='PICK UP ',@Libelle='Pick up ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='NACELLE',@Code='PLATEAU16',@Libelle='Plateau 16m',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='PL',@Code='PORTPOTEAU',@Libelle='Porte poteau',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VL',@Code='SAXO',@Libelle='Saxo',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE2',@Code='SCUDO',@Libelle='Scudo ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='BENNE',@Code='SPRINTBENN',@Libelle='Sprinter Benne ',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='FOURGON',@Code='SPRINTFOUR',@Libelle='Sprinter',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='BENNEGRUE',@Code='SPRINTGRUE',@Libelle='Sprinter benne grue',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='NACELLE',@Code='TOPY10',@Libelle='Topy 10',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='PL',@Code='TRACSEMI',@Libelle='TRACTEUR DE SEMI REMORQUE',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE2',@Code='TRAFIC',@Libelle='Traffic',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='TM',@Code='TRICYCLE',@Libelle='Tricycle à Moteur',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='CTTE2',@Code='VITO',@Libelle='VITO',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VP',@Code='VPBUDGET',@Libelle='VP Budget',@Type='Matériel'
EXEC Fred_ToolBox_Ressources @GroupeCode='GFES',@SousChapitreCode='VP',@Code='VPREGULE',@Libelle='VP régulé ',@Type='Matériel'

