-- --------------------------------------------------
-- INJECTION ABSENCE NIVEAU
-- --------------------------------------------------
DECLARE @GroupeId  INT;
Set @GroupeId = (SELECT GroupeId from FRED_GROUPE WHERE Code = 'GFES');

INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'ANA','Absence non autorisée',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'ANP','Absence autorisée non payée',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'AP','Absence payée',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'I','Absence intempérie',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'DEL','Absence délégation',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'PREAV','Préavis effectué payé',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'PNE','Préavis non effectué payé',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'VM','Visite médicale',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'CP','Conge paye',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'RC','Repos compensateur',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0); 
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'RT','RTT',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null,0);

INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'AJ','Accident de trajet',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'AT','Accident du travail',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'ML','Maladie non professionnelle',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'MP','Maladie professionnelle',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'MTHN','Mi-temps thérapeutique',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'CONV','Congé conventionnel',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'CPAR','Congé parental',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'CSAB','Congé sabbatique',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'CSS','Congé sans solde',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'MT','Maternité',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId,null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'PT','Paternité',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId, null, 0);
INSERT INTO FRED_CODE_ABSENCE (HoldingId, SocieteId, Code, Libelle, Intemperie, TauxDecote, NBHeuresDefautETAM, NBHeuresMinETAM, NBHeuresMaxETAM, NBHeuresDefautCO, NBHeuresMinCO, NBHeuresMaxCO, Actif, GroupeId, CodeAbsenceParentId, Niveau) VALUES(null,null,'RA','Repos autorisé',0, 1,7.5,1,7.5,7.5,1,7.5,1,@GroupeId, null, 0);
