
-- Activation des etablissements de paie FES



EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='75',@Code='09',@Libelle='SATELEC DG',@Adresse='24 ave du Général de Gaulle, 91170 VIRY-CHATILLON',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='10',@Libelle='SATELEC VIRY',@Adresse='24 ave du Général de Gaulle, 91170 VIRY-CHATILLON',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='11',@Libelle='SATELEC ANTONY',@Adresse='3 rue Henri Poincaré, 92160 ANTONY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='50',@Code='12',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='13',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='14',@Libelle='SATELEC BAGNOLET',@Adresse='73 rue des Rigondes, 93170 BAGNOLET',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='15',@Libelle='SATELEC BONNEUIL',@Adresse='4 ave des Marronniers, 94380 BONNEUIL SUR MARNE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='16',@Libelle='SATELEC CESSON',@Adresse='225 ave de l''Europe, 77240 VERT SAINT DENIS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='10',@Code='17',@Libelle='SATELEC NANTERRE',@Adresse='85 Rue des hautes Patures, 92000 NANTERRE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='50',@Code='18',@Libelle='SATELEC POWER NANT.',@Adresse='85 Rue des hautes Patures, 92000 NANTERRE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='20',@Libelle='SATELEC CUINCY',@Adresse='945 rue du Faubourg, 59553 CUINCY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='21',@Libelle='SATELEC TRITH',@Adresse='14  ZA Les Poutrelles, 59125 TRITH SAINT LEGER',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='22',@Libelle='SATELEC TOURCOING',@Adresse='59  Chaussée Berthelot, 59200 TOURCOING',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='23',@Libelle='SATELEC GDE SYNTHE',@Adresse='17 rue de l''Abbé Grégoire, 59760 GRANDE-SYNTHE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='24',@Libelle='SATELEC HENIN BT',@Adresse='141 bld Edouard Branly, 62110 HENIN-BEAUMONT',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='25',@Libelle='SATELEC MONTIGNY',@Adresse='4 rue Saussaies-aux-Dames, 57950 MONTIGNY-LES-METZ',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='26',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='27',@Libelle='SATELEC POULAINVILLE',@Adresse='0 rue Marius Morel, 80260 POULAINVILLE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='28',@Libelle='SATELEC ST ANDRE',@Adresse='10 RUE GUSTAVE EIFFEL, 10120 SAINT ANDRE LES VERGERS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='29',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='30',@Code='30',@Libelle='SATELEC PACA',@Adresse='68  Parc de l''Argile, 6370 MOUANS-SARTOUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='40',@Code='40',@Libelle='SATELEC AQUITAINE',@Adresse='27 rue de Fleurenne, 33290 BLANQUEFORT',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='50',@Code='41',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='40',@Code='42',@Libelle='SATELEC BISCARROSSE',@Adresse='175 rue Forestière, 40600 BISCARROSSE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@Code='69',@Libelle='SATELEC LYON',@Adresse='2  Chemin du Genie, 69200 VENISSIEUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='2A',@Libelle='SATELEC ALLONNE',@Adresse='115 rue des quarantes Mines, 60000 ALLONNE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E001',@AgenceRattachementCode='20',@Code='2B',@Libelle='SATELEC ST PAUL',@Adresse='3 Ave Piton Batard, 97460 SAINT PAUL',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='10',@Libelle='SEMERU VIRY',@Adresse='34 RUE CHARLES PIKETTY, 91170 VIRY CHATILLON',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='11',@Libelle='SEMERU ANTONY',@Adresse='3 RUE HENRI POINCARE, 92160 ANTONY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='12',@Libelle='SEMERU BONNEUIL',@Adresse='4 AVE DES MARRONNIERS, 94380 BONNEUIL SUR MARNE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='13',@Libelle='SEMERU RUNGIS',@Adresse='54 RUE D ARCUEIL, 94150 RUNGIS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@Code='20',@Libelle='SEMERU CUINCY',@Adresse='945 RUE DU FAUBOURG, 59553 CUINCY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='21',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='22',@Libelle='SEMERU TEMPLEMARS',@Adresse='0  PARC D''ACTIVITE B, 59175 TEMPLEMARS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='30',@Libelle='SEMERU PACA',@Adresse='68  PARC de L''ARGILE, 6370 MOUANS SARTOUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='40',@Libelle='SEMERU AQUITAINE',@Adresse='27 RUE DE FLEURENNE, 33290 BLANQUEFORT',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E002',@AgenceRattachementCode='1',@Code='50',@Libelle='SEMERU LYON',@Adresse='2  CHEMIN DU GENIE, 69200 VENISSIEUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='10',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='11',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='12',@Libelle='FARECO GENNEVILLIERS',@Adresse='223 RUE DES CABOEUFS, 92230 GENNEVILLIERS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='13',@Libelle='FARECO ASNIERES',@Adresse='250 Av DES GRESILLONS, 92600 ASNIERES',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E003',@AgenceRattachementCode='10',@Code='20',@Libelle='FARECO MEYREUIL',@Adresse='8  PARC TECHNOLOGIQUE, 13590 MEYREUIL',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E006',@AgenceRattachementCode='10',@Code='10',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E006',@AgenceRattachementCode='10',@Code='11',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E006',@AgenceRattachementCode='10',@Code='12',@Libelle='CITEPARK ANTONY',@Adresse='3 RUE HENRI POINCARE, 92160 ANTONY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E006',@AgenceRattachementCode='10',@Code='30',@Libelle='CITEPARK PACA',@Adresse='68  PARC DE l''ARGILE, 6370 MOUANS SARTOUX',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E007',@AgenceRattachementCode='31',@Code='10',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='10',@Libelle='ERS SAINT GREGOIRE',@Adresse='7  P.A. de Brocéliande, 35760 SAINT GREGOIRE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='11',@Libelle='ERS MELESSE',@Adresse='0 Rue de la Perrière, 35520 MELESSE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='20',@Libelle='ERS LAVAL',@Adresse='0  Allée de la Goberie, 53940 SAINT-BERTHEVIN',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='30',@Libelle='ERS COUTANCES',@Adresse='0  ZI Chateau de la Mare, 50200 COUTANCES',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='40',@Libelle='ERS ANGERS',@Adresse='15 rue Paul Langevin, 49240 AVRILLE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='50',@Libelle='ERS DINAN',@Adresse='2 rue de la Tramontane, 22100 TADEN',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='60',@Libelle='ERS CARQUEFOU',@Adresse='25  Allée des Sapins, 44470 CARQUEFOU',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='70',@Libelle='ERS SAINT AVE',@Adresse='30 rue Marcel Dassault, 56890 SAINT AVE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@Code='80',@Libelle='ERS ELLIANT',@Adresse='0  Impasse Penalen, 29370 ELLIANT',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E010',@AgenceRattachementCode='41',@Code='90',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E011',@AgenceRattachementCode='42',@Code='10',@Libelle='ERS MAINE',@Adresse='5  Allée du Perquoi, 72560 CHANGE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E011',@AgenceRattachementCode='42',@Code='20',@Libelle='ERS MAINE',@Adresse='3 rue de la Briaudière, 37510 Ballan-Mire',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E012',@AgenceRattachementCode='43',@Code='10',@Libelle='SR DHENNIN',@Adresse='0  Zone Industrielle, 28140 ORGERES EN BEAUCE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E012',@AgenceRattachementCode='43',@Code='20',@Libelle='SR DHENNIN GELLAINVI',@Adresse='12 ave Gustave Eiffel, 28630 GELLAINVILLE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E013',@AgenceRattachementCode='11',@Code='11',@Libelle='SODECLIM',@Adresse='56 RUE LOUIS AUROUX, 94120 FONTENAY SOUS BOIS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E014',@AgenceRattachementCode='20',@Code='20',@Libelle='F.E.S.I Cuincy',@Adresse='945 RUE DU FBG D ESQUERCHIN, 59553 CUINCY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E015',@AgenceRattachementCode='60',@Code='40',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E015',@AgenceRattachementCode='60',@Code='41',@Libelle='GABRIELLE AUCH',@Adresse='2 IMP D ENGACHIES, 32000 AUCH',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E015',@AgenceRattachementCode='60',@Code='42',@Libelle='GABRIELLE RIGNAC',@Adresse='0 ZA LES VIEILLES VIGNES, 46500 RIGNAC',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E015',@AgenceRattachementCode='60',@Code='43',@Libelle='GABRIELLE  BEAUZELLE',@Adresse='160 RUE DE LA SUR, 31700 BEAUZELLE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E015',@Code='44',@Libelle='GABRIELLE CADOURS',@Adresse='0  Route de Toulouse, 31480 CADOURS',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E016',@AgenceRattachementCode='13',@Code='13',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E016',@Code='14',@Libelle='AVEO NANTERRE',@Adresse='45 rue des hautes patures, 92000 NANTERRE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E017',@AgenceRattachementCode='974',@Code='97',@Libelle='SATELEC CENERGI',@Adresse='9 Rue Sully Prudhomme, 97420 Le Port',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E017',@AgenceRattachementCode='974',@Code='98',@Libelle='SATELEC CENERGI',@Adresse='22 Rue Pierre Brossolette, 97420 Le Port',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E018',@AgenceRattachementCode='14',@Code='14',@Libelle='SATCOMPTAGES SIEGE',@Adresse='24 Ave Gal de Gaulle, 91170 VIRY CHATILLON',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E018',@AgenceRattachementCode='14',@Code='27',@Libelle='SATCOMPTAGES VAUCH.',@Adresse='36 rue Rene Dingeon, 80132 VAUCHELLES LES QUESNOY',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E018',@AgenceRattachementCode='14',@Code='56',@Libelle='SATCOMPTAGES ST AVE',@Adresse='30 rue Marcel Dassault, 56890 SAINT AVE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E019',@AgenceRattachementCode='21',@Code='27',@Libelle='VALIANCE CATTENOM',@Adresse='17 RUE DE L ABBE GREGOIRE, 59760 GRANDE SYNTHE',@PaysCode='FR'
EXEC Fred_ToolBox_Etablissement_Paie @Actif='1', @GroupeCode='GFES',@SocieteCode='E019',@Code='23',@Libelle='VALIANCE GRDE SYNTHE',@Adresse='0 ZAC D HUSANGE, 57570 CATTENOM',@PaysCode='FR'

