-- GFES gestion des moyens
-- Alimentation de la table FRED_AFFECTATION_MOYEN_FAMILLE

CREATE PROCEDURE #SET_FRED_AFFECTATION_MOYEN_FAMILLE
	@Code NVARCHAR(MAX), 
	@Libelle NVARCHAR(MAX)

AS
BEGIN
	IF NOT EXISTS ( SELECT 1 FROM FRED_AFFECTATION_MOYEN_FAMILLE WHERE Code = @Code)
	BEGIN
		INSERT INTO FRED_AFFECTATION_MOYEN_FAMILLE (Code, Libelle)
		VALUES (@Code, @Libelle)
	END
END
GO

-- Insertion des données

EXEC #SET_FRED_AFFECTATION_MOYEN_FAMILLE @Code='AFFECT', @Libelle='Affectation';
EXEC #SET_FRED_AFFECTATION_MOYEN_FAMILLE @Code='DISP', @Libelle='Disponible';
EXEC #SET_FRED_AFFECTATION_MOYEN_FAMILLE @Code='LOC', @Libelle='Location';
EXEC #SET_FRED_AFFECTATION_MOYEN_FAMILLE @Code='MAINT', @Libelle='Maintenance';


-- Fin insertion

DROP PROCEDURE #SET_FRED_AFFECTATION_MOYEN_FAMILLE