-- Mise à jour des sociétés
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E001',@Active=1,@Libelle='SATELEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E002',@Active=1,@Libelle='SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E003',@Active=1,@Libelle='FARECO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E006',@Active=1,@Libelle='CITEPARK'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E007',@Active=1,@Libelle='TRAFIPARC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E010',@Active=1,@Libelle='ERS'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E011',@Active=1,@Libelle='ERS Maine'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E012',@Active=1,@Libelle='DHENNIN'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E013',@Active=1,@Libelle='SODECLIM'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E014',@Active=1,@Libelle='GROUPE FESI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E015',@Active=1,@Libelle='GABRIELLE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E016',@Active=1,@Libelle='AVEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E017',@Active=1,@Libelle='SATELEC-CENERGI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E018',@Active=1,@Libelle='SATCOMPTAGES'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E019',@Active=1,@Libelle='VALIANCE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EG01',@Active=1,@Libelle='GIE Lignes Souterraines'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EG02',@Active=1,@Libelle='GIE Fayat Postes HT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES01',@Active=1,@Libelle='SEP CHU NICE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES02',@Active=1,@Libelle='SEP DAI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES04',@Active=1,@Libelle='SEP SLT GRAND LYON'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES05',@Active=1,@Libelle='SEP - RADARS MEEDDAT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES06',@Active=1,@Libelle='SEP TUNNEL DU LANDY'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES07',@Active=1,@Libelle='SEP R-GTC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES08',@Active=1,@Libelle='SEP MAGES Maintenance'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES09',@Active=1,@Libelle='SEP LISA SATELEC - INEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES10',@Active=1,@Libelle='SEP TUNNEL DE NOGENT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES11',@Active=1,@Libelle='SEP GTC SEMERU / SPIE / INEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES12',@Active=1,@Libelle='SEP Seine Aval - ADEN/AXEAU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES13',@Active=1,@Libelle='SEP MESS SDEL / SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES14',@Active=1,@Libelle='SEP RFF - SATELEC / SNCF INGEN'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES15',@Active=1,@Libelle='SEP ETM - FARECO / SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES16',@Active=1,@Libelle='SEP SAT/INEO Maint. Radar Auto'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES17',@Active=1,@Libelle='SEP Ligne LMCU INEO - SATELEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES18',@Active=1,@Libelle='SEP CAC SATELEC-SDEL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES19',@Active=1,@Libelle='SEP BPNL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES20',@Active=1,@Libelle='SEP RN7 SATELEC SPIE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES21',@Active=1,@Libelle='SEP MEDTS SEMERU/SDEL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES22',@Active=1,@Libelle='SEP IP 13'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES23',@Active=1,@Libelle='SEP BPNL GTC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES24',@Active=1,@Libelle='SEP SATELEC-RAZEL BEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES25',@Active=1,@Libelle='SEP MAINTENANCE RADARS MOF'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX05',@Active=1,@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX06',@Active=1,@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX07',@Active=1,@Libelle='FESI - MAROC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX08',@Active=1,@Libelle='FESI - CAMEROUN'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E004',@Active=1,@Libelle='MULTIPHONE'