-- Mise à jour des sociétés
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E001',@CodeSocietePaye='001',@CodeSocieteComptable='E001',@Libelle='SATELEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E002',@CodeSocietePaye='002',@CodeSocieteComptable='E002',@Libelle='SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E003',@CodeSocietePaye='003',@CodeSocieteComptable='E003',@Libelle='FARECO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E006',@CodeSocietePaye='006',@CodeSocieteComptable='E006',@Libelle='CITEPARK'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E007',@CodeSocietePaye='007',@CodeSocieteComptable='E007',@Libelle='TRAFIPARC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E010',@CodeSocietePaye='101',@CodeSocieteComptable='E010',@Libelle='ERS'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E011',@CodeSocietePaye='102',@CodeSocieteComptable='E011',@Libelle='ERS Maine'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E012',@CodeSocietePaye='103',@CodeSocieteComptable='E012',@Libelle='DHENNIN'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E013',@CodeSocietePaye='013',@CodeSocieteComptable='E013',@Libelle='SODECLIM'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E014',@CodeSocietePaye='014',@CodeSocieteComptable='E014',@Libelle='GROUPE FESI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E015',@CodeSocietePaye='015',@CodeSocieteComptable='E015',@Libelle='GABRIELLE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E016',@CodeSocietePaye='016',@CodeSocieteComptable='E016',@Libelle='AVEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E017',@CodeSocietePaye='017',@CodeSocieteComptable='E017',@Libelle='SATELEC-CENERGI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E018',@CodeSocietePaye='018',@CodeSocieteComptable='E018',@Libelle='SATCOMPTAGES'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E019',@CodeSocietePaye='019',@CodeSocieteComptable='E019',@Libelle='VALIANCE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EG01',@CodeSocietePaye=null,@CodeSocieteComptable='EG01',@Libelle='GIE Lignes Souterraines'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EG02',@CodeSocietePaye=null,@CodeSocieteComptable='EG02',@Libelle='GIE Fayat Postes HT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES01',@CodeSocietePaye=null,@CodeSocieteComptable='ES01',@Libelle='SEP CHU NICE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES02',@CodeSocietePaye=null,@CodeSocieteComptable='ES02',@Libelle='SEP DAI'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES04',@CodeSocietePaye=null,@CodeSocieteComptable='ES04',@Libelle='SEP SLT GRAND LYON'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES05',@CodeSocietePaye=null,@CodeSocieteComptable='ES05',@Libelle='SEP - RADARS MEEDDAT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES06',@CodeSocietePaye=null,@CodeSocieteComptable='ES06',@Libelle='SEP TUNNEL DU LANDY'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES07',@CodeSocietePaye=null,@CodeSocieteComptable='ES07',@Libelle='SEP R-GTC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES08',@CodeSocietePaye=null,@CodeSocieteComptable='ES08',@Libelle='SEP MAGES Maintenance'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES09',@CodeSocietePaye=null,@CodeSocieteComptable='ES09',@Libelle='SEP LISA SATELEC - INEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES10',@CodeSocietePaye=null,@CodeSocieteComptable='ES10',@Libelle='SEP TUNNEL DE NOGENT'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES11',@CodeSocietePaye=null,@CodeSocieteComptable='ES11',@Libelle='SEP GTC SEMERU / SPIE / INEO'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES12',@CodeSocietePaye=null,@CodeSocieteComptable='ES12',@Libelle='SEP Seine Aval - ADEN/AXEAU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES13',@CodeSocietePaye=null,@CodeSocieteComptable='ES13',@Libelle='SEP MESS SDEL / SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES14',@CodeSocietePaye=null,@CodeSocieteComptable='ES14',@Libelle='SEP RFF - SATELEC / SNCF INGEN'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES15',@CodeSocietePaye=null,@CodeSocieteComptable='ES15',@Libelle='SEP ETM - FARECO / SEMERU'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES16',@CodeSocietePaye=null,@CodeSocieteComptable='ES16',@Libelle='SEP SAT/INEO Maint. Radar Auto'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES17',@CodeSocietePaye=null,@CodeSocieteComptable='ES17',@Libelle='SEP Ligne LMCU INEO - SATELEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES18',@CodeSocietePaye=null,@CodeSocieteComptable='ES18',@Libelle='SEP CAC SATELEC-SDEL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES19',@CodeSocietePaye=null,@CodeSocieteComptable='ES19',@Libelle='SEP BPNL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES20',@CodeSocietePaye=null,@CodeSocieteComptable='ES20',@Libelle='SEP RN7 SATELEC SPIE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES21',@CodeSocietePaye=null,@CodeSocieteComptable='ES21',@Libelle='SEP MEDTS SEMERU/SDEL'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES22',@CodeSocietePaye=null,@CodeSocieteComptable='ES22',@Libelle='SEP IP 13'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES23',@CodeSocietePaye=null,@CodeSocieteComptable='ES23',@Libelle='SEP BPNL GTC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES24',@CodeSocietePaye=null,@CodeSocieteComptable='ES24',@Libelle='SEP SATELEC-RAZEL BEC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='ES25',@CodeSocietePaye=null,@CodeSocieteComptable='ES25',@Libelle='SEP MAINTENANCE RADARS MOF'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX05',@CodeSocietePaye=null,@CodeSocieteComptable='EX05',@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX06',@CodeSocietePaye=null,@CodeSocieteComptable='EX06',@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX07',@CodeSocietePaye=null,@CodeSocieteComptable='EX07',@Libelle='FESI - MAROC'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='EX08',@CodeSocietePaye=null,@CodeSocieteComptable='EX08',@Libelle='FESI - CAMEROUN'
EXEC Fred_ToolBox_Societe @GroupeCode='GFES',@Code='E004',@CodeSocietePaye='004',@CodeSocieteComptable='E004',@Libelle='MULTIPHONE'

-- Mise à jour des établissements comptables
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0010',@Libelle='SATELEC PIDF'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0020',@Libelle='SATELEC France NORD'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0030',@Libelle='SATELEC PACA'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0040',@Libelle='SATELEC AQUITAINE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0050',@Libelle='SATELEC Grands Projets'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0075',@Libelle='SATELEC DG'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0090',@Libelle='FESI - NIGER'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0091',@Libelle='FESI - CAMEROUN'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0092',@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E001',@Code='0093',@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E002',@Code='0001',@Libelle='SEMERU PIDF'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E002',@Code='0002',@Libelle='SEMERU NORD'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E002',@Code='0003',@Libelle='SEMERU PACA'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E002',@Code='0004',@Libelle='SEMERU OUEST'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E003',@Code='0010',@Libelle='FARECO'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E004',@Code='0098',@Libelle='FARECO TUNISIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E006',@Code='0010',@Libelle='CITEPARK PIDF'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E006',@Code='0015',@Libelle='DSP Ville de Pré Saint Gervais'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E006',@Code='0016',@Libelle='DSP Melun'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E007',@Code='0031',@Libelle='SAM TRAFIPARC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E010',@Code='0041',@Libelle='ERS'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E011',@Code='0042',@Libelle='ERS Maine'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E012',@Code='0043',@Libelle='DHENNIN'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E013',@Code='0011',@Libelle='SODECLIM'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0020',@Libelle='FESI QUINCY'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0094',@Libelle='FESI - MOZAMBIQUE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0095',@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0096',@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E014',@Code='0097',@Libelle='FESI - MAROC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E015',@Code='0060',@Libelle='GABRIELLE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E016',@Code='0013',@Libelle='AVEO'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E017',@Code='0974',@Libelle='SATELEC-CENERGI'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E018',@Code='0014',@Libelle='SATCOMPTAGES'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='E019',@Code='0021',@Libelle='VALIANCE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EG01',@Code='EG01',@Libelle='GIE Lignes Souterraines'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EG02',@Code='EG02',@Libelle='GIE Fayat Postes HT'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES01',@Code='ES01',@Libelle='SEP CHU NICE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES02',@Code='ES02',@Libelle='SEP DAI'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES04',@Code='ES04',@Libelle='SEP SLT GRAND LYON'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES05',@Code='ES05',@Libelle='SEP - RADARS MEEDDAT'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES06',@Code='ES06',@Libelle='SEP TUNNEL DU LANDY'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES07',@Code='ES07',@Libelle='SEP R-GTC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES08',@Code='ES08',@Libelle='SEP MAGES Maintenance'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES09',@Code='ES09',@Libelle='SEP LISA SATELEC - INEO'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES10',@Code='ES10',@Libelle='SEP TUNNEL DE NOGENT'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES11',@Code='ES11',@Libelle='SEP GTC SEMERU / SPIE / INEO'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES12',@Code='ES12',@Libelle='SEP Seine Aval - ADEN/AXEAU'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES13',@Code='ES13',@Libelle='SEP MESS SDEL / SEMERU'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES14',@Code='ES14',@Libelle='SEP RFF - SATELEC / SNCF INGEN'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES15',@Code='ES15',@Libelle='SEP ETM - FARECO / SEMERU'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES16',@Code='ES16',@Libelle='SEP SAT/INEO Maint. Radar Auto'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES17',@Code='ES17',@Libelle='SEP Ligne LMCU INEO - SATELEC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES18',@Code='ES18',@Libelle='SEP CAC SATELEC-SDEL'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES19',@Code='ES19',@Libelle='SEP BPNL'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES20',@Code='ES20',@Libelle='SEP RN7 SATELEC SPIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES21',@Code='ES21',@Libelle='SEP MEDTS SEMERU/SDEL'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES22',@Code='ES22',@Libelle='SEP IP 13'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES23',@Code='ES23',@Libelle='SEP BPNL GTC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES24',@Code='ES24',@Libelle='SEP SATELEC-RAZEL BEC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='ES25',@Code='ES25',@Libelle='SEP MAINTENANCE RADARS MOF'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EX05',@Code='EX05',@Libelle='FESI - JORDANIE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EX06',@Code='EX06',@Libelle='FESI - COTE D IVOIRE'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EX07',@Code='EX07',@Libelle='FESI - MAROC'
EXEC Fred_ToolBox_Etablissement_Comptable @GroupeCode='GFES',@SocieteCode='EX08',@Code='EX08',@Libelle='FESI - CAMEROUN'