-- Suppression des associations Permissions / Fonctionnalités pour FES
DELETE FROM FRED_PERMISSION_FONCTIONNALITE
WHERE PermissionFonctionnaliteId in (
    SELECT DISTINCT pf.PermissionFonctionnaliteId
    from FRED_PERMISSION_FONCTIONNALITE pf inner join FRED_ROLE_FONCTIONNALITE rf on rf.FonctionnaliteId=pf.FonctionnaliteId
        inner join FRED_ROLE r on r.RoleId=rf.RoleId
        inner join FRED_SOCIETE s on r.SocieteId=s.SocieteId
        inner join FRED_GROUPE g on s.GroupeId=g.GroupeId
    WHERE g.Code='GFES')

-- MAJ / Ajout des modules
IF EXISTS (select ModuleId from FRED_MODULE where Code='10')   UPDATE FRED_MODULE set Libelle='Edition', DateSuppression=NULL, Description=NULL WHERE Code='10'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('10', 'Edition', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='11')   UPDATE FRED_MODULE set Libelle='Gestion des affaires', DateSuppression=NULL, Description=NULL WHERE Code='11'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('11', 'Gestion des affaires', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='12')   UPDATE FRED_MODULE set Libelle='Gestion budgetaire', DateSuppression=NULL, Description=NULL WHERE Code='12'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('12', 'Gestion budgetaire', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='14')   UPDATE FRED_MODULE set Libelle='Menu SI', DateSuppression=NULL, Description=NULL WHERE Code='14'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('14', 'Menu SI', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='15')   UPDATE FRED_MODULE set Libelle='Gestion des dépenses', DateSuppression=NULL, Description=NULL WHERE Code='15'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('15', 'Gestion des dépenses', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='3')   UPDATE FRED_MODULE set Libelle='Paramétrage Ressources Humaines', DateSuppression=NULL, Description=NULL WHERE Code='3'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('3', 'Paramétrage Ressources Humaines', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='4')   UPDATE FRED_MODULE set Libelle='Pointage', DateSuppression=NULL, Description=NULL WHERE Code='4'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('4', 'Pointage', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='5')   UPDATE FRED_MODULE set Libelle='Paramétrage des Habilitations', DateSuppression=NULL, Description=NULL WHERE Code='5'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('5', 'Paramétrage des Habilitations', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='51')   UPDATE FRED_MODULE set Libelle='Gestion des moyens', DateSuppression=NULL, Description='Module pour la gestion des moyens' WHERE Code='51'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('51', 'Gestion des moyens', NULL, 'Module pour la gestion des moyens')
IF EXISTS (select ModuleId from FRED_MODULE where Code='6')   UPDATE FRED_MODULE set Libelle='Paramétrage Organisation', DateSuppression=NULL, Description=NULL WHERE Code='6'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('6', 'Paramétrage Organisation', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='7')   UPDATE FRED_MODULE set Libelle='Paramétrage référentiel', DateSuppression=NULL, Description=NULL WHERE Code='7'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('7', 'Paramétrage référentiel', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='8')   UPDATE FRED_MODULE set Libelle='Achats', DateSuppression=NULL, Description=NULL WHERE Code='8'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('8', 'Achats', NULL, NULL)
IF EXISTS (select ModuleId from FRED_MODULE where Code='9')   UPDATE FRED_MODULE set Libelle='Exploitation', DateSuppression=NULL, Description=NULL WHERE Code='9'  ELSE  INSERT INTO FRED_MODULE (Code, Libelle, DateSuppression, [Description]) VALUES('9', 'Exploitation', NULL, NULL)

-- MAJ / Ajout des fonctionnalités
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1001')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='10'), Code='1001',    Libelle='Edition pointage personnel', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='1001'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='10'), '1001', 'Edition pointage personnel', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1002')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='10'), Code='1002',    Libelle='Edition du compte d''exploitation', HorsOrga=0,    DateSuppression='2019-01-19 15:57:18.017',    Description=NULL   WHERE Code='1002'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='10'), '1002', 'Edition du compte d''exploitation', 0, '2019-01-19 15:57:18.017', NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1100')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='11'), Code='1100',    Libelle='Centre d''imputation', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='1100'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='11'), '1100', 'Centre d''imputation', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1101')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='11'), Code='1101',    Libelle='Affichage des clôtures', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='1101'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='11'), '1101', 'Affichage des clôtures', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1102')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='11'), Code='1102',    Libelle='Bouton de clôture comptable', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='1102'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='11'), '1102', 'Bouton de clôture comptable', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1200')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='12'), Code='1200',    Libelle='Plan de tâches', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='1200'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='12'), '1200', 'Plan de tâches', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='12002')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='12'), Code='12002',    Libelle='Budget', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='12002'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='12'), '12002', 'Budget', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1201')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='1201',    Libelle='Validation de rapport', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='1201'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '1201', 'Validation de rapport', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1311')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1311',    Libelle='Affichage de toute la liste des affectations des moyens', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de toute la liste des affectations des moyens'   WHERE Code='1311'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1311', 'Affichage de toute la liste des affectations des moyens', 0, NULL, 'Affichage de toute la liste des affectations des moyens')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1312')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1312',    Libelle='Affichage de la liste des affectations moyens liées au personnels d''un manager', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de la liste des affectations moyens liées au personnels d''un manager'   WHERE Code='1312'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1312', 'Affichage de la liste des affectations moyens liées au personnels d''un manager', 0, NULL, 'Affichage de la liste des affectations moyens liées au personnels d''un manager')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1313')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1313',    Libelle='Affichage de la liste des affectations liées au CI d''un responsable CI', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de la liste des affectations liées au CI d''un responsable CI'   WHERE Code='1313'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1313', 'Affichage de la liste des affectations liées au CI d''un responsable CI', 0, NULL, 'Affichage de la liste des affectations liées au CI d''un responsable CI')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1314')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1314',    Libelle='Affichage de la liste des affectations moyens liées au CI d''un délégué', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de la liste des affectations moyens liées au CI d''un délégué'   WHERE Code='1314'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1314', 'Affichage de la liste des affectations moyens liées au CI d''un délégué', 0, NULL, 'Affichage de la liste des affectations moyens liées au CI d''un délégué')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1315')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1315',    Libelle='Affichage de toute la liste des CI', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de toute la liste des CI'   WHERE Code='1315'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1315', 'Affichage de toute la liste des CI', 0, NULL, 'Affichage de toute la liste des CI')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1316')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1316',    Libelle='Affichage de la liste des CI d''un responsable CI', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de la liste des CI d''un responsable CI'   WHERE Code='1316'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1316', 'Affichage de la liste des CI d''un responsable CI', 0, NULL, 'Affichage de la liste des CI d''un responsable CI')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1317')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1317',    Libelle='Affichage de la liste des CI d''un délégué', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de la liste des CI d''un délégué'   WHERE Code='1317'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1317', 'Affichage de la liste des CI d''un délégué', 0, NULL, 'Affichage de la liste des CI d''un délégué')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1318')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1318',    Libelle='Affichage de toute la liste des personnels', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de toute la liste des personnels'   WHERE Code='1318'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1318', 'Affichage de toute la liste des personnels', 0, NULL, 'Affichage de toute la liste des personnels')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1319')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1319',    Libelle='Affichage de la liste des personnels d''un manager', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de la liste des personnels d''un manager'   WHERE Code='1319'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1319', 'Affichage de la liste des personnels d''un manager', 0, NULL, 'Affichage de la liste des personnels d''un manager')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1320')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1320',    Libelle='Affichage de la liste des personnels affectés aux CI d''un responsable CI', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage de la liste des personnels affectés aux CI d''un responsable CI'   WHERE Code='1320'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1320', 'Affichage de la liste des personnels affectés aux CI d''un responsable CI', 0, NULL, 'Affichage de la liste des personnels affectés aux CI d''un responsable CI')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1350')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1350',    Libelle='Affichage du menu gestion des moyens', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage du menu gestion des moyens'   WHERE Code='1350'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1350', 'Affichage du menu gestion des moyens', 0, NULL, 'Affichage du menu gestion des moyens')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1351')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1351',    Libelle='Affichage du bouton d''affectation', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage du bouton d''affectation'   WHERE Code='1351'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1351', 'Affichage du bouton d''affectation', 0, NULL, 'Affichage du bouton d''affectation')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1352')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1352',    Libelle='Affichage du bouton de restitution', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage du bouton de restitution'   WHERE Code='1352'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1352', 'Affichage du bouton de restitution', 0, NULL, 'Affichage du bouton de restitution')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1353')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1353',    Libelle='Affichage du bouton de location', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage du bouton de location'   WHERE Code='1353'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1353', 'Affichage du bouton de location', 0, NULL, 'Affichage du bouton de location')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1354')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1354',    Libelle='Affichage du bouton de maintenance', HorsOrga=0,    DateSuppression=NULL,    Description='Affichage du bouton de maintenance'   WHERE Code='1354'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1354', 'Affichage du bouton de maintenance', 0, NULL, 'Affichage du bouton de maintenance')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1355')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1355',    Libelle='Recherche : Affichage du de la lookup de filtre par personnel', HorsOrga=0,    DateSuppression=NULL,    Description='Recherche : Affichage du de la lookup de filtre par personnel'   WHERE Code='1355'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1355', 'Recherche : Affichage du de la lookup de filtre par personnel', 0, NULL, 'Recherche : Affichage du de la lookup de filtre par personnel')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1356')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1356',    Libelle='Recherche : Affichage par personnel et Ci (Tous)', HorsOrga=0,    DateSuppression=NULL,    Description='Recherche : Affichage par personnel et Ci (Tous)'   WHERE Code='1356'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1356', 'Recherche : Affichage par personnel et Ci (Tous)', 0, NULL, 'Recherche : Affichage par personnel et Ci (Tous)')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1357')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1357',    Libelle='Affectation : séléction des moyens pour affectation', HorsOrga=0,    DateSuppression=NULL,    Description='Affectation : séléction des moyens pour affectation'   WHERE Code='1357'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1357', 'Affectation : séléction des moyens pour affectation', 0, NULL, 'Affectation : séléction des moyens pour affectation')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1358')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1358',    Libelle='Filtre : recherche avancée', HorsOrga=0,    DateSuppression=NULL,    Description='Filtre : recherche avancée (par site, statut, date de fin et moyens à rapatrier)'   WHERE Code='1358'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1358', 'Filtre : recherche avancée', 0, NULL, 'Filtre : recherche avancée (par site, statut, date de fin et moyens à rapatrier)')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1359')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1359',    Libelle='Validation ou annulation des affectations', HorsOrga=0,    DateSuppression=NULL,    Description='Validation ou annulation des affectations'   WHERE Code='1359'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1359', 'Validation ou annulation des affectations', 0, NULL, 'Validation ou annulation des affectations')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1360')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1360',    Libelle='Accès à la date de fin d''affectation', HorsOrga=0,    DateSuppression=NULL,    Description='Accès à la date de fin d''affectation'   WHERE Code='1360'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1360', 'Accès à la date de fin d''affectation', 0, NULL, 'Accès à la date de fin d''affectation')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1361')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1361',    Libelle='Recherche : Affichage de la lookup de filtre par Ci', HorsOrga=0,    DateSuppression=NULL,    Description='Recherche : Affichage de la lookup de filtre par Ci'   WHERE Code='1361'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1361', 'Recherche : Affichage de la lookup de filtre par Ci', 0, NULL, 'Recherche : Affichage de la lookup de filtre par Ci')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1362')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='51'), Code='1362',    Libelle='Recherche : Affichage du champs responsable ou manager', HorsOrga=0,    DateSuppression=NULL,    Description='Recherche : Affichage du champs responsable ou manager'   WHERE Code='1362'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='51'), '1362', 'Recherche : Affichage du champs responsable ou manager', 0, NULL, 'Recherche : Affichage du champs responsable ou manager')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1401')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='14'), Code='1401',    Libelle='Admin SI', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='1401'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='14'), '1401', 'Admin SI', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='1501')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='15'), Code='1501',    Libelle='Gestion des dépenses', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='1501'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='15'), '1501', 'Gestion des dépenses', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='300')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='3'), Code='300',    Libelle='Affichage des menus Administration RH', HorsOrga=0,    DateSuppression=NULL,    Description='Affiche les menus des différentes fenêtre de code lié à la gestion des ressources humaines'   WHERE Code='300'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='3'), '300', 'Affichage des menus Administration RH', 0, NULL, 'Affiche les menus des différentes fenêtre de code lié à la gestion des ressources humaines')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='301')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='3'), Code='301',    Libelle='Affichage de la liste des personnels', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='301'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='3'), '301', 'Affichage de la liste des personnels', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='302')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='3'), Code='302',    Libelle='Gestion du personnel', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='302'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='3'), '302', 'Gestion du personnel', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='400')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='400',    Libelle='Affichage du menu ''Liste des rapports''', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='400'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '400', 'Affichage du menu ''Liste des rapports''', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='401')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='401',    Libelle='Affichage de la page ''Nouveau rapport''', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='401'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '401', 'Affichage de la page ''Nouveau rapport''', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='402')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='402',    Libelle='Affichage de la page ''Liste des  pointages personnel''', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='402'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '402', 'Affichage de la page ''Liste des  pointages personnel''', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='403')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='403',    Libelle='Affichage de la page ''Validation lots de pointage''', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='403'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '403', 'Affichage de la page ''Validation lots de pointage''', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='404')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='404',    Libelle='Affichage de la page ''Détail d''un rapport''', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='404'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '404', 'Affichage de la page ''Détail d''un rapport''', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='405')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='405',    Libelle='Remontée Vrac', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='405'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '405', 'Remontée Vrac', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='406')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='406',    Libelle='Affichage du Rapport par ouvrier', HorsOrga=0,    DateSuppression='2018-10-08 19:02:36.833',    Description='Saisie du Rapport hebdomadaire par ouvrier'   WHERE Code='406'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '406', 'Affichage du Rapport par ouvrier', 0, '2018-10-08 19:02:36.833', 'Saisie du Rapport hebdomadaire par ouvrier')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='407')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='407',    Libelle='Affichage du Rapport ETAM IAC', HorsOrga=0,    DateSuppression='2019-01-24 10:54:36.967',    Description='Saisie du Rapport hebdomadaire ETAM IAC'   WHERE Code='407'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '407', 'Affichage du Rapport ETAM IAC', 0, '2019-01-24 10:54:36.967', 'Saisie du Rapport hebdomadaire ETAM IAC')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='408')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='408',    Libelle='Affichage de la synthèse mensuelle', HorsOrga=0,    DateSuppression='2018-10-08 19:02:42.467',    Description='Affichage de la synthèse mensuelle pour les ETAM IAC'   WHERE Code='408'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '408', 'Affichage de la synthèse mensuelle', 0, '2018-10-08 19:02:42.467', 'Affichage de la synthèse mensuelle pour les ETAM IAC')
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='409')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='409',    Libelle='Affichage des rapports primes mensuelles', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='409'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '409', 'Affichage des rapports primes mensuelles', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='410')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='410',    Libelle='Rapport hebdomadaire Ouvrier', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='410'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '410', 'Rapport hebdomadaire Ouvrier', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='411')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='411',    Libelle='Rapport hebdomadaire Etam/IAC', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='411'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '411', 'Rapport hebdomadaire Etam/IAC', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='412')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='412',    Libelle='Gestion du calendrier des affectations', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='412'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '412', 'Gestion du calendrier des affectations', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='413')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='4'), Code='413',    Libelle='Gestion du calendrier des affectations - Délégation', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='413'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='4'), '413', 'Gestion du calendrier des affectations - Délégation', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='500')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='5'), Code='500',    Libelle='Affichage des menus ''Habilitation''', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='500'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='5'), '500', 'Affichage des menus ''Habilitation''', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='501')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='5'), Code='501',    Libelle='Affichage du journal de connexion', HorsOrga=0,    DateSuppression='2018-10-08 18:49:29.503',    Description=NULL   WHERE Code='501'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='5'), '501', 'Affichage du journal de connexion', 0, '2018-10-08 18:49:29.503', NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='600')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='6'), Code='600',    Libelle='Gestion des établissements comptables', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='600'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='6'), '600', 'Gestion des établissements comptables', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='601')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='6'), Code='601',    Libelle='Gestion des sociétés', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='601'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='6'), '601', 'Gestion des sociétés', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='602')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='6'), Code='602',    Libelle='Gestion des établissements de paie', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='602'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='6'), '602', 'Gestion des établissements de paie', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='603')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='6'), Code='603',    Libelle='Gestion des fournisseurs', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='603'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='6'), '603', 'Gestion des fournisseurs', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='700')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='7'), Code='700',    Libelle='Gestion des devises', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='700'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='7'), '700', 'Gestion des devises', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='701')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='7'), Code='701',    Libelle='Gestion des codes de natures analytiques', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='701'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='7'), '701', 'Gestion des codes de natures analytiques', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='702')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='7'), Code='702',    Libelle='Gestion du plan de ressources', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='702'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='7'), '702', 'Gestion du plan de ressources', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='703')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='7'), Code='703',    Libelle='Gestion des natures analytiques / ressources', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='703'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='7'), '703', 'Gestion des natures analytiques / ressources', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='704')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='7'), Code='704',    Libelle='Gestion du matériel', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='704'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='7'), '704', 'Gestion du matériel', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='705')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='7'), Code='705',    Libelle='Gestion des journaux comptables', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='705'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='7'), '705', 'Gestion des journaux comptables', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='800')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='8'), Code='800',    Libelle='Gestion des commandes', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='800'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='8'), '800', 'Gestion des commandes', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='801')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='8'), Code='801',    Libelle='Nouvelle commande', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='801'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='8'), '801', 'Nouvelle commande', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='802')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='8'), Code='802',    Libelle='Gestion des réceptions', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='802'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='8'), '802', 'Gestion des réceptions', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='803')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='8'), Code='803',    Libelle='Accès au tableau des réceptions', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='803'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='8'), '803', 'Accès au tableau des réceptions', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='900')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='9'), Code='900',    Libelle='Barème CI', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='900'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='9'), '900', 'Barème CI', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='901')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='9'), Code='901',    Libelle='Barème organisation', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='901'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='9'), '901', 'Barème organisation', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='902')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='9'), Code='902',    Libelle='OD', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='902'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='9'), '902', 'OD', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='903')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='9'), Code='903',    Libelle='Bilan flash', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='903'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='9'), '903', 'Bilan flash', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='904')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='9'), Code='904',    Libelle='Explorateur de dépenses', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='904'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='9'), '904', 'Explorateur de dépenses', 0, NULL, NULL)
IF EXISTS (select FonctionnaliteId from FRED_FONCTIONNALITE where Code='905')   UPDATE FRED_FONCTIONNALITE SET ModuleId=(select m.ModuleId from FRED_MODULE m where m.Code='9'), Code='905',    Libelle='Compte d''exploitation', HorsOrga=0,    DateSuppression=NULL,    Description=NULL   WHERE Code='905'  ELSE INSERT INTO FRED_FONCTIONNALITE (ModuleId, Code, Libelle, HorsOrga, DateSuppression, [Description]) VALUES ((select m.ModuleId from FRED_MODULE m where m.Code='9'), '905', 'Compte d''exploitation', 0, NULL, NULL)

-- Ajout des relations permissions - fonctionnalités
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1100' and p.Code='0002'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1100' and p.Code='0036'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1101' and p.Code='0009'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1102' and p.Code='0047'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1200' and p.Code='0031'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1201' and p.Code='0053'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1311' and p.Code='0101'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1312' and p.Code='0102'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1313' and p.Code='0103'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1314' and p.Code='0104'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1315' and p.Code='0105'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1316' and p.Code='0106'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1317' and p.Code='0107'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1318' and p.Code='0108'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1319' and p.Code='0109'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1320' and p.Code='0110'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1350' and p.Code='0100'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1351' and p.Code='0111'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1352' and p.Code='0112'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1353' and p.Code='0113'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1354' and p.Code='0114'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1355' and p.Code='0115'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1356' and p.Code='0116'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1357' and p.Code='0117'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1358' and p.Code='0118'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1358' and p.Code='0119'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1358' and p.Code='0120'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1358' and p.Code='0121'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1359' and p.Code='0122'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1359' and p.Code='0123'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1360' and p.Code='0124'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1361' and p.Code='0125'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='1362' and p.Code='0126'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='300' and p.Code='0003'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='300' and p.Code='0004'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='300' and p.Code='0005'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='300' and p.Code='0006'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='300' and p.Code='0026'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='301' and p.Code='0022'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='302' and p.Code='0039'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='400' and p.Code='0024'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='402' and p.Code='0025'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='403' and p.Code='0034'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='404' and p.Code='0023'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='405' and p.Code='0048'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='410' and p.Code='0057'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='411' and p.Code='0058'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='412' and p.Code='0049'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='413' and p.Code='0050'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='500' and p.Code='0020'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='500' and p.Code='0032'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='600' and p.Code='0013'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='601' and p.Code='0033'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='602' and p.Code='0008'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='602' and p.Code='0014'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='701' and p.Code='0019'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='702' and p.Code='0030'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='703' and p.Code='0029'
INSERT INTO FRED_PERMISSION_FONCTIONNALITE SELECT p.PermissionId, f.FonctionnaliteId FROM FRED_PERMISSION p, FRED_FONCTIONNALITE f WHERE f.Code='704' and p.Code='0017'