
SET IDENTITY_INSERT [importExport].[TranspoCodeEmploiToRessource] ON 
IF EXISTS(SELECT 1 FROM [importExport].[TranspoCodeEmploiToRessource] WHERE [TranspoCodeEmploiToRessourceId]=419)
BEGIN
    DELETE FROM [importExport].[TranspoCodeEmploiToRessource] WHERE [TranspoCodeEmploiToRessourceId]=419
END
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (419,N'MTP', N'OA005     ', N'MO-20')
IF EXISTS(SELECT 1 FROM [importExport].[TranspoCodeEmploiToRessource] WHERE [TranspoCodeEmploiToRessourceId]=420)
BEGIN
    DELETE FROM [importExport].[TranspoCodeEmploiToRessource] WHERE [TranspoCodeEmploiToRessourceId]=420
END
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (420,N'MTP', N'EA010     ', N'ENCA-35')
IF EXISTS(SELECT 1 FROM [importExport].[TranspoCodeEmploiToRessource] WHERE [TranspoCodeEmploiToRessourceId]=421)
BEGIN
    DELETE FROM [importExport].[TranspoCodeEmploiToRessource] WHERE [TranspoCodeEmploiToRessourceId]=421
END
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (421,N'MTP', N'EA020     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (422,N'MTP', N'EA030     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (423,N'MTP', N'OA010     ', N'MO-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (424,N'MTP', N'EA040     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (425,N'MTP', N'OA020     ', N'MO-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (426,N'MTP', N'OA030     ', N'MO-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (427,N'MTP', N'EA050     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (428,N'MTP', N'OA040     ', N'MO-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (429,N'MTP', N'OA050     ', N'MO-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (430,N'MTP', N'OA060     ', N'MO-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (431,N'MTP', N'EA060     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (432,N'MTP', N'OA070     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (433,N'MTP', N'CA015     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (434,N'MTP', N'CA020     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (435,N'MTP', N'EA070     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (436,N'MTP', N'CA030     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (437,N'MTP', N'OA080     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (438,N'MTP', N'EA080     ', N'MO-45')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (439,N'MTP', N'OA090     ', N'MO-45')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (440,N'MTP', N'EA090     ', N'ENCA-45')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (441,N'MTP', N'EA100     ', N'MO-45')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (442,N'MTP', N'EA110     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (443,N'MTP', N'EA120     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (444,N'MTP', N'EA130     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (445,N'MTP', N'EA140     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (446,N'MTP', N'CA040     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (447,N'MTP', N'EA150     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (448,N'MTP', N'EA160     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (449,N'MTP', N'EA170     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (450,N'MTP', N'EA180     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (451,N'MTP', N'EA190     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (452,N'MTP', N'EA195     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (453,N'MTP', N'EA200     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (454,N'MTP', N'EA210     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (455,N'MTP', N'EA220     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (456,N'MTP', N'EA230     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (457,N'MTP', N'EA240     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (458,N'MTP', N'EA250     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (459,N'MTP', N'EA260     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (460,N'MTP', N'OB010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (461,N'MTP', N'CC010     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (462,N'MTP', N'CC020     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (463,N'MTP', N'CC030     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (464,N'MTP', N'CC040     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (465,N'MTP', N'CC050     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (466,N'MTP', N'CC070     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (467,N'MTP', N'CC080     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (468,N'MTP', N'OC010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (469,N'MTP', N'OC030     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (470,N'MTP', N'OC040     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (471,N'MTP', N'CC090     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (472,N'MTP', N'CC100     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (473,N'MTP', N'CC110     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (474,N'MTP', N'CC120     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (475,N'MTP', N'EC010     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (476,N'MTP', N'CC130     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (477,N'MTP', N'CC140     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (478,N'MTP', N'CC160     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (479,N'MTP', N'EC020     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (480,N'MTP', N'CC170     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (481,N'MTP', N'CC172     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (482,N'MTP', N'OC050     ', N'MO-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (483,N'MTP', N'EC030     ', N'MO-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (484,N'MTP', N'OC060     ', N'MO-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (485,N'MTP', N'OC061     ', N'MO-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (486,N'MTP', N'OC062     ', N'MO-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (487,N'MTP', N'CC180     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (488,N'MTP', N'EC035     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (489,N'MTP', N'CC190     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (490,N'MTP', N'EC040     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (491,N'MTP', N'EC047     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (492,N'MTP', N'EC050     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (493,N'MTP', N'CC200     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (494,N'MTP', N'CC210     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (495,N'MTP', N'EC060     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (496,N'MTP', N'EC070     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (497,N'MTP', N'EC080     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (498,N'MTP', N'EC090     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (499,N'MTP', N'EC100     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (500,N'MTP', N'CC230     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (501,N'MTP', N'CC240     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (502,N'MTP', N'CC250     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (503,N'MTP', N'CC260     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (504,N'MTP', N'CC270     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (505,N'MTP', N'EC110     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (506,N'MTP', N'EC120     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (507,N'MTP', N'OC072     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (508,N'MTP', N'OC174     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (509,N'MTP', N'OC091     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (510,N'MTP', N'EC130     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (511,N'MTP', N'OC070     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (512,N'MTP', N'OC080     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (513,N'MTP', N'EC140     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (514,N'MTP', N'OC090     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (515,N'MTP', N'OC100     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (516,N'MTP', N'OC110     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (517,N'MTP', N'OC120     ', N'MO-01 ')
GO
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (518,N'MTP', N'CC280     ', N'ENCA-30')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (519,N'MTP', N'EC150     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (520,N'MTP', N'CC290     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (521,N'MTP', N'EC160     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (522,N'MTP', N'CC300     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (523,N'MTP', N'EC170     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (524,N'MTP', N'EC180     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (525,N'MTP', N'OC130     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (526,N'MTP', N'CC310     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (527,N'MTP', N'EC190     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (528,N'MTP', N'CC345     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (529,N'MTP', N'CC330     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (530,N'MTP', N'EC200     ', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (531,N'MTP', N'CC340     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (532,N'MTP', N'EC210     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (533,N'MTP', N'CC336     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (534,N'MTP', N'CC335     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (535,N'MTP', N'CC341     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (536,N'MTP', N'CC350     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (537,N'MTP', N'CC360     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (538,N'MTP', N'CC370     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (539,N'MTP', N'CC375     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (540,N'MTP', N'EC220     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (541,N'MTP', N'OC140     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (542,N'MTP', N'OC150     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (543,N'MTP', N'OC160     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (544,N'MTP', N'OC161     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (545,N'MTP', N'OC165     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (546,N'MTP', N'OC168     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (547,N'MTP', N'OC170     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (548,N'MTP', N'OC175     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (549,N'MTP', N'EC225     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (550,N'MTP', N'OC180     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (551,N'MTP', N'EC230     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (552,N'MTP', N'OC190     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (553,N'MTP', N'OC200     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (554,N'MTP', N'OC210     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (555,N'MTP', N'OC220     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (556,N'MTP', N'OC230     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (557,N'MTP', N'OC240     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (558,N'MTP', N'OC250     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (559,N'MTP', N'OC270     ', N'MO-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (560,N'MTP', N'OC280     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (561,N'MTP', N'OC290     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (562,N'MTP', N'OC300     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (563,N'MTP', N'OC310     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (564,N'MTP', N'OC320     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (565,N'MTP', N'OC330     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (566,N'MTP', N'CC380     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (567,N'MTP', N'EC240     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (568,N'MTP', N'CC390     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (569,N'MTP', N'OC340     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (570,N'MTP', N'EC250     ', N'MO-45')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (571,N'MTP', N'OC350     ', N'MO-45')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (572,N'MTP', N'EC260     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (573,N'MTP', N'CC420     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (574,N'MTP', N'CC400     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (575,N'MTP', N'CC410     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (576,N'MTP', N'EC270     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (577,N'MTP', N'CC430     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (578,N'MTP', N'CC440     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (579,N'MTP', N'EC275     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (580,N'MTP', N'EC280     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (581,N'MTP', N'EC290     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (582,N'MTP', N'CC450     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (583,N'MTP', N'CC460     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (584,N'MTP', N'EC295     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (585,N'MTP', N'EC296     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (586,N'MTP', N'EC300     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (587,N'MTP', N'OC360     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (588,N'MTP', N'OD010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (589,N'MTP', N'ED010     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (590,N'MTP', N'CD010     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (591,N'MTP', N'ED020     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (592,N'MTP', N'CD020     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (593,N'MTP', N'CD030     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (594,N'MTP', N'CD040     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (595,N'MTP', N'CD050     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (596,N'MTP', N'CD045     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (597,N'MTP', N'CD060     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (598,N'MTP', N'CD070     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (599,N'MTP', N'CD080     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (600,N'MTP', N'CD090     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (601,N'MTP', N'CD100     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (602,N'MTP', N'CD115     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (603,N'MTP', N'CD120     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (604,N'MTP', N'CD160     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (605,N'MTP', N'CD140     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (606,N'MTP', N'CD150     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (607,N'MTP', N'CD170     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (608,N'MTP', N'CD180     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (609,N'MTP', N'CD205     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (610,N'MTP', N'CD190     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (611,N'MTP', N'CD200     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (612,N'MTP', N'CD220     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (613,N'MTP', N'CD230     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (614,N'MTP', N'CD240     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (615,N'MTP', N'CD250     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (616,N'MTP', N'CD260     ', N'ENCA-01')
GO
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (617,N'MTP', N'CD270     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (618,N'MTP', N'CD279     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (619,N'MTP', N'CD280     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (620,N'MTP', N'CD320     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (621,N'MTP', N'CD330     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (622,N'MTP', N'CD340     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (623,N'MTP', N'CD290     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (624,N'MTP', N'CD300     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (625,N'MTP', N'CD310     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (626,N'MTP', N'CD345     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (627,N'MTP', N'CD350     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (628,N'MTP', N'CD370     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (629,N'MTP', N'CD360     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (630,N'MTP', N'CD379     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (631,N'MTP', N'CD380     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (632,N'MTP', N'CD390     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (633,N'MTP', N'CD400     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (634,N'MTP', N'CD410     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (635,N'MTP', N'CD420     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (636,N'MTP', N'CD430     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (637,N'MTP', N'CD440     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (638,N'MTP', N'CD450     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (639,N'MTP', N'CD460     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (640,N'MTP', N'CD461     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (641,N'MTP', N'CD470     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (642,N'MTP', N'CD471     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (643,N'MTP', N'CD480     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (644,N'MTP', N'ED030     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (645,N'MTP', N'ED040     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (646,N'MTP', N'CD490     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (647,N'MTP', N'CD500     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (648,N'MTP', N'CD510     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (649,N'MTP', N'CD520     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (650,N'MTP', N'CE001     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (651,N'MTP', N'EE005     ', N'MO-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (652,N'MTP', N'OE010     ', N'MO-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (653,N'MTP', N'EE010     ', N'MO-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (654,N'MTP', N'EE020     ', N'MO-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (655,N'MTP', N'EE030     ', N'MO-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (656,N'MTP', N'EE040     ', N'MO-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (657,N'MTP', N'OE020     ', N'MO-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (658,N'MTP', N'OE030     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (659,N'MTP', N'EE050     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (660,N'MTP', N'EE060     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (661,N'MTP', N'EE065     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (662,N'MTP', N'OF010     ', N'MO-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (663,N'MTP', N'OF020     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (664,N'MTP', N'EG010     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (665,N'MTP', N'EG020     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (666,N'MTP', N'EG030     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (667,N'MTP', N'EG040     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (668,N'MTP', N'EG050     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (669,N'MTP', N'EG060     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (670,N'MTP', N'EG070     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (671,N'MTP', N'CG010     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (672,N'MTP', N'EG080     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (673,N'MTP', N'EG090     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (674,N'MTP', N'EG110     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (675,N'MTP', N'EG100     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (676,N'MTP', N'EG115     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (677,N'MTP', N'OG010     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (678,N'MTP', N'OG012     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (679,N'MTP', N'EH010     ', N'MO-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (680,N'MTP', N'EH020     ', N'MO-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (681,N'MTP', N'CI180     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (682,N'MTP', N'CI010     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (683,N'MTP', N'CI020     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (684,N'MTP', N'CI030     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (685,N'MTP', N'CI040     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (686,N'MTP', N'CI050     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (687,N'MTP', N'CI060     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (688,N'MTP', N'CI070     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (689,N'MTP', N'CI080     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (690,N'MTP', N'CI090     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (691,N'MTP', N'CI100     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (692,N'MTP', N'CI110     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (693,N'MTP', N'CI120     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (694,N'MTP', N'CI130     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (695,N'MTP', N'CI140     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (696,N'MTP', N'CI150     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (697,N'MTP', N'CI160     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (698,N'MTP', N'CI170     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (699,N'MTP', N'CI190     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (700,N'MTP', N'CI200     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (701,N'MTP', N'CJ010     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (702,N'MTP', N'CL010     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (703,N'MTP', N'OL010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (704,N'MTP', N'EL010     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (705,N'MTP', N'OM010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (706,N'MTP', N'OM020     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (707,N'MTP', N'OM030     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (708,N'MTP', N'OM040     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (709,N'MTP', N'OM050     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (710,N'MTP', N'EM010     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (711,N'MTP', N'OM059     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (712,N'MTP', N'CM010     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (713,N'MTP', N'CM011     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (714,N'MTP', N'OM060     ', N'MO-01 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (715,N'MTP', N'OM070     ', N'MO-20')
GO
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (716,N'MTP', N'OM080     ', N'MO-30')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (717,N'MTP', N'OM090     ', N'MO-30')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (718,N'MTP', N'OM100     ', N'MO-30')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (719,N'MTP', N'OM110     ', N'MO-30')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (720,N'MTP', N'OM130     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (721,N'MTP', N'EM060     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (722,N'MTP', N'EM040     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (723,N'MTP', N'OM140     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (724,N'MTP', N'OM150     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (725,N'MTP', N'OM160     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (726,N'MTP', N'OM170     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (727,N'MTP', N'EM050     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (728,N'MTP', N'OM180     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (729,N'MTP', N'OO010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (730,N'MTP', N'OO020     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (731,N'MTP', N'OO030     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (732,N'MTP', N'EO020     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (733,N'MTP', N'OO040     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (734,N'MTP', N'OO050     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (735,N'MTP', N'OO060     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (736,N'MTP', N'OO070     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (737,N'MTP', N'OO080     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (738,N'MTP', N'OO090     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (739,N'MTP', N'OO100     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (740,N'MTP', N'OO110     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (741,N'MTP', N'OO120     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (742,N'MTP', N'EP010     ', N'MO-05 ')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (743,N'MTP', N'OP010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (744,N'MTP', N'OP020     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (745,N'MTP', N'CP010     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (746,N'MTP', N'EP020     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (747,N'MTP', N'OP030     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (748,N'MTP', N'CP020     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (749,N'MTP', N'EP030     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (750,N'MTP', N'CP030     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (751,N'MTP', N'EP035     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (752,N'MTP', N'EP040     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (753,N'MTP', N'OR020     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (754,N'MTP', N'OR010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (755,N'MTP', N'CR010     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (756,N'MTP', N'CR030     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (757,N'MTP', N'CR020     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (758,N'MTP', N'CR040     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (759,N'MTP', N'ER010     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (760,N'MTP', N'CR050     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (761,N'MTP', N'CR060     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (762,N'MTP', N'CR080     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (763,N'MTP', N'CR070     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (764,N'MTP', N'CR090     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (765,N'MTP', N'CR100     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (766,N'MTP', N'CR110     ', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (767,N'MTP', N'CR120     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (768,N'MTP', N'CR132     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (769,N'MTP', N'CR135     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (770,N'MTP', N'CR131     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (771,N'MTP', N'CR105     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (772,N'MTP', N'CR140     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (773,N'MTP', N'CR150     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (774,N'MTP', N'CR160     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (775,N'MTP', N'CR170     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (776,N'MTP', N'CR180     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (777,N'MTP', N'CR190     ', N'ENCA-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (778,N'MTP', N'CR200     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (779,N'MTP', N'ER020     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (780,N'MTP', N'CR210     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (781,N'MTP', N'CR215     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (782,N'MTP', N'CR220     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (783,N'MTP', N'CR230     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (784,N'MTP', N'CR240     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (785,N'MTP', N'CR252     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (786,N'MTP', N'CR250     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (787,N'MTP', N'ER030     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (788,N'MTP', N'CR260     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (789,N'MTP', N'CR270     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (790,N'MTP', N'CR280     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (791,N'MTP', N'ER040     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (792,N'MTP', N'CR290     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (793,N'MTP', N'CR300     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (794,N'MTP', N'CR320     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (795,N'MTP', N'ER050     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (796,N'MTP', N'CR340     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (797,N'MTP', N'CR351     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (798,N'MTP', N'CR359     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (799,N'MTP', N'CR370     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (800,N'MTP', N'CR376     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (801,N'MTP', N'CR380     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (802,N'MTP', N'CR390     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (803,N'MTP', N'CR330     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (804,N'MTP', N'CR327     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (805,N'MTP', N'CR400     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (806,N'MTP', N'CR405     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (807,N'MTP', N'CR415     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (808,N'MTP', N'CR325     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (809,N'MTP', N'CR420     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (810,N'MTP', N'CR422     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (811,N'MTP', N'CR430     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (812,N'MTP', N'ES010     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (813,N'MTP', N'ES020     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (814,N'MTP', N'ES030     ', N'ENCA-35')
GO
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (815,N'MTP', N'ES035     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (816,N'MTP', N'CS010     ', N'ENCA-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (817,N'MTP', N'OS010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (818,N'MTP', N'SS010     ', N'MO-45')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (819,N'MTP', N'ET010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (820,N'MTP', N'ET020     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (821,N'MTP', N'ET030     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (822,N'MTP', N'ET105     ', N'MO-30')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (823,N'MTP', N'ET040     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (824,N'MTP', N'ET050     ', N'ENCA-20')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (825,N'MTP', N'ET060     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (826,N'MTP', N'ET070     ', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (827,N'MTP', N'ET080     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (828,N'MTP', N'ET100     ', N'ENCA-30')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (829,N'MTP', N'ET090     ', N'ENCA-30')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (830,N'MTP', N'ET110     ', N'ENCA-40')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (831,N'MTP', N'ET120     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (832,N'MTP', N'ET130     ', N'ENCA-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (833,N'MTP', N'OT010     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (834,N'MTP', N'OT050     ', N'MO-15')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (835,N'MTP', N'CT010     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (836,N'MTP', N'CT020     ', N'ENCA-35')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (837,N'MTP', N'OA008', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (838,N'MTP', N'OC051', N'MO-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (839,N'MTP', N'CC218', N'ENCA-10')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (840,N'MTP', N'CC188', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (841,N'MTP', N'CC308', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (842,N'MTP', N'OC275', N'MO-05')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (843,N'MTP', N'OC400', N'MO-01')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (844,N'MTP', N'CG005', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (845,N'MTP', N'CO001', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (846,N'MTP', N'CR009', N'ENCA-07')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (847,N'MTP', N'CR305', N'ENCA-90')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (848,N'MTP', N'CR398', N'ENCA-25')
INSERT INTO [importExport].[TranspoCodeEmploiToRessource] ([TranspoCodeEmploiToRessourceId], [CodeSocieteImport], [CodeEmploi], [CodeRessource]) VALUES (849,N'MTP', N'CR253', N'ENCA-90')

SET IDENTITY_INSERT [importExport].[TranspoCodeEmploiToRessource] OFF
