SET IDENTITY_INSERT FRED_EXTERNALDIRECTORY ON;
INSERT INTO FRED_EXTERNALDIRECTORY (FayatAccessDirectoryId,MotDePasse,DateExpiration,IsActived) VALUES ('1','FR20ed12!1970','01/01/2030','1'); 
INSERT INTO FRED_EXTERNALDIRECTORY (FayatAccessDirectoryId,MotDePasse,DateExpiration,IsActived) VALUES ('2','FR20ed12!1970','01/01/2030','1'); 
SET IDENTITY_INSERT FRED_EXTERNALDIRECTORY OFF;


