-- --------------------------------------------------
-- FRED 2017 - INJECTION DES DONNES
-- --------------------------------------------------

SET IDENTITY_INSERT FRED_PERSONNEL ON;
INSERT INTO FRED_PERSONNEL (PersonnelId,SocieteId,Matricule,IsInterimaire,IsInterne,Nom,Prenom,Statut,CategoriePerso,DateEntree,DateSortie,Adresse1,Adresse2,Adresse3,CodePostal,Ville,PaysId,LongitudeDomicile,LatitudeDomicile,Tel1,Tel2,Email,TypeRattachement,DateCreation,DateModification,DateSuppression,UtilisateurIdCreation,UtilisateurIdModification,UtilisateurIdSuppression,RessourceId,EtablissementPayeId,EtablissementRattachementId) VALUES ('1','2','S_ADM','0','0','SuperAdmin FCI',NULL,NULL,NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'fred.admin@fci.fayat.com',NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO FRED_PERSONNEL (PersonnelId,SocieteId,Matricule,IsInterimaire,IsInterne,Nom,Prenom,Statut,CategoriePerso,DateEntree,DateSortie,Adresse1,Adresse2,Adresse3,CodePostal,Ville,PaysId,LongitudeDomicile,LatitudeDomicile,Tel1,Tel2,Email,TypeRattachement,DateCreation,DateModification,DateSuppression,UtilisateurIdCreation,UtilisateurIdModification,UtilisateurIdSuppression,RessourceId,EtablissementPayeId,EtablissementRattachementId) VALUES ('2','3','039','0','1','Rouyer','Emmanuel',NULL,NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'e.rouyer@fci.fayat.com',NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO FRED_PERSONNEL (PersonnelId,SocieteId,Matricule,IsInterimaire,IsInterne,Nom,Prenom,Statut,CategoriePerso,DateEntree,DateSortie,Adresse1,Adresse2,Adresse3,CodePostal,Ville,PaysId,LongitudeDomicile,LatitudeDomicile,Tel1,Tel2,Email,TypeRattachement,DateCreation,DateModification,DateSuppression,UtilisateurIdCreation,UtilisateurIdModification,UtilisateurIdSuppression,RessourceId,EtablissementPayeId,EtablissementRattachementId) VALUES ('3','3','071','0','1','Escudero','Loic',NULL,NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'l.escudero@fci.fayat.com',NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO FRED_PERSONNEL (PersonnelId,SocieteId,Matricule,IsInterimaire,IsInterne,Nom,Prenom,Statut,CategoriePerso,DateEntree,DateSortie,Adresse1,Adresse2,Adresse3,CodePostal,Ville,PaysId,LongitudeDomicile,LatitudeDomicile,Tel1,Tel2,Email,TypeRattachement,DateCreation,DateModification,DateSuppression,UtilisateurIdCreation,UtilisateurIdModification,UtilisateurIdSuppression,RessourceId,EtablissementPayeId,EtablissementRattachementId) VALUES ('4','3','078','0','1','Peytour','Bruno',NULL,NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'b.peytour@fci.fayat.com',NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO FRED_PERSONNEL (PersonnelId,SocieteId,Matricule,IsInterimaire,IsInterne,Nom,Prenom,Statut,CategoriePerso,DateEntree,DateSortie,Adresse1,Adresse2,Adresse3,CodePostal,Ville,PaysId,LongitudeDomicile,LatitudeDomicile,Tel1,Tel2,Email,TypeRattachement,DateCreation,DateModification,DateSuppression,UtilisateurIdCreation,UtilisateurIdModification,UtilisateurIdSuppression,RessourceId,EtablissementPayeId,EtablissementRattachementId) VALUES ('5','3','107','0','1','Defay','Yannick',NULL,NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'y.defay@fci.fayat.com',NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO FRED_PERSONNEL (PersonnelId,SocieteId,Matricule,IsInterimaire,IsInterne,Nom,Prenom,Statut,CategoriePerso,DateEntree,DateSortie,Adresse1,Adresse2,Adresse3,CodePostal,Ville,PaysId,LongitudeDomicile,LatitudeDomicile,Tel1,Tel2,Email,TypeRattachement,DateCreation,DateModification,DateSuppression,UtilisateurIdCreation,UtilisateurIdModification,UtilisateurIdSuppression,RessourceId,EtablissementPayeId,EtablissementRattachementId) VALUES ('6','3','MARTA','0','0','Martageix','Carine',NULL,NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'c.martageix.sqli@fci.fayat.com',NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO FRED_PERSONNEL (PersonnelId,SocieteId,Matricule,IsInterimaire,IsInterne,Nom,Prenom,Statut,CategoriePerso,DateEntree,DateSortie,Adresse1,Adresse2,Adresse3,CodePostal,Ville,PaysId,LongitudeDomicile,LatitudeDomicile,Tel1,Tel2,Email,TypeRattachement,DateCreation,DateModification,DateSuppression,UtilisateurIdCreation,UtilisateurIdModification,UtilisateurIdSuppression,RessourceId,EtablissementPayeId,EtablissementRattachementId) VALUES ('7','3','069','0','1','Michel','Anthony',NULL,NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'a.michel@fci.fayat.com',NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
--INSERT INTO FRED_PERSONNEL (PersonnelId,SocieteId,Matricule,IsInterimaire,IsInterne,Nom,Prenom,Statut,CategoriePerso,DateEntree,DateSortie,Adresse1,Adresse2,Adresse3,CodePostal,Ville,PaysId,LongitudeDomicile,LatitudeDomicile,Tel1,Tel2,Email,TypeRattachement,DateCreation,DateModification,DateSuppression,UtilisateurIdCreation,UtilisateurIdModification,UtilisateurIdSuppression,RessourceId,EtablissementPayeId,EtablissementRattachementId) VALUES ('8','3','DEV','0','0','Developpeur','Dev',NULL,NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'dummy@fci.fayat.com',NULL,'01/01/2017',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

SET IDENTITY_INSERT FRED_PERSONNEL OFF;




-- --------------------------------------------------
-- MEP AVRIL 2018 - INJECTION DES DONNES
-- N/A
-- --------------------------------------------------