
-- --------------------------------------------------
-- FRED 2017 - INJECTION DES DONNES
-- --------------------------------------------------

SET IDENTITY_INSERT [dbo].[FRED_IMAGE] ON
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (1, N'/medias/app/societe/logotype/BOMAG_1.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (2, N'/medias/app/societe/logotype/Breining1.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (3, N'/medias/app/societe/logotype/CASTEL_ALU1.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (4, N'/medias/app/societe/logotype/CENERGIA_PNv_2015.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (5, N'/medias/app/societe/logotype/CHARLATTE_Mantention_1.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (6, N'/medias/app/societe/logotype/DARRAS-JOUANIN.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (7, N'/medias/app/societe/logotype/DEFAULT.png', N'', 2, 1)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (8, N'/medias/app/societe/logotype/FAYAT_BATIMENT.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (9, N'/medias/app/societe/logotype/FAYAT_TP.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (10, N'/medias/app/societe/logotype/FRANKI.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (12, N'/medias/app/societe/logotype/MARINI_1.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (13, N'/medias/app/societe/logotype/NORD_FRANCE_CONSTRUCTIONS_PNv.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (14, N'/medias/app/societe/logotype/RAVO1.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (15, N'/medias/app/societe/logotype/RAZEL-BEC.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (16, N'/medias/app/societe/logotype/RAZEL_BEC_1.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (17, N'/medias/app/societe/logotype/ReservoirsXP1.jpg', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (18, N'/medias/app/societe/logotype/SEFI-INTRAFOR.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (19, N'/medias/app/societe/logotype/SEG.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (20, N'/medias/app/societe/logotype/SEP_EOLE.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (21, N'/medias/app/societe/logotype/URBAINE_DE_TRAVAUX.png', N'', 2, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (22, N'/medias/app/societe/screenLogin/0.jpg', N'', 1, 1)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (23, N'/medias/app/societe/screenLogin/1.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (24, N'/medias/app/societe/screenLogin/3.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (25, N'/medias/app/societe/screenLogin/4.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (26, N'/medias/app/societe/screenLogin/5.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (27, N'/medias/app/societe/screenLogin/6.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (28, N'/medias/app/societe/screenLogin/7.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (29, N'/medias/app/societe/screenLogin/8.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (30, N'/medias/app/societe/screenLogin/9.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (31, N'/medias/app/societe/screenLogin/10.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (32, N'/medias/app/societe/screenLogin/11.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (33, N'/medias/app/societe/screenLogin/13.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (34, N'/medias/app/societe/screenLogin/14.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (35, N'/medias/app/societe/screenLogin/15.png', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (36, N'/medias/app/societe/screenLogin/16.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (37, N'/medias/app/societe/screenLogin/17.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (38, N'/medias/app/societe/screenLogin/18.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (39, N'/medias/app/societe/screenLogin/19.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (40, N'/medias/app/societe/screenLogin/20.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (41, N'/medias/app/societe/screenLogin/21.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (42, N'/medias/app/societe/screenLogin/22.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (43, N'/medias/app/societe/screenLogin/23.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (44, N'/medias/app/societe/screenLogin/25.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (45, N'/medias/app/societe/screenLogin/26.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (46, N'/medias/app/societe/screenLogin/27.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (47, N'/medias/app/societe/screenLogin/29.jpg', N'', 1, 0)
INSERT INTO [dbo].[FRED_IMAGE] ([ImageId], [Path], [Credit], [Type], [IsDefault]) VALUES (48, N'/medias/app/societe/screenLogin/30.jpg', N'', 1, 0)
SET IDENTITY_INSERT [dbo].[FRED_IMAGE] OFF