-- Insert les libellés et codes des motifs de remplacement pour les intérimaires :

IF EXISTS(
SELECT ct.Code
FROM	FRED_COMMANDE_TYPE ct
WHERE ct.Code = 'I'
)
BEGIN
DELETE FROM FRED_COMMANDE_CONTRAT_INTERIMAIRE WHERE CommandeId IN (SELECT CommandeId FROM FRED_COMMANDE WHERE TypeId IN (SELECT CommandeTypeId FROM FRED_COMMANDE_TYPE WHERE Code = 'I'));
DELETE FROM FRED_COMMANDE_LIGNE WHERE CommandeId IN (SELECT CommandeId FROM FRED_COMMANDE WHERE TypeId IN (SELECT CommandeTypeId FROM FRED_COMMANDE_TYPE WHERE Code = 'I'));
DELETE FROM FRED_COMMANDE WHERE TypeId IN (SELECT CommandeTypeId FROM FRED_COMMANDE_TYPE WHERE Code = 'I');
DELETE FROM FRED_COMMANDE_TYPE WHERE Code = 'I';
END




IF NOT EXISTS(
SELECT ct.Code
FROM	FRED_COMMANDE_TYPE ct
WHERE ct.Code = 'I'
)
BEGIN	
SET IDENTITY_INSERT  FRED_COMMANDE_TYPE ON;
INSERT INTO FRED_COMMANDE_TYPE (CommandeTypeId, Code, Libelle) VALUES (4, 'I', 'Interimaire');
SET IDENTITY_INSERT  FRED_COMMANDE_TYPE OFF;
END