IF EXISTS(
SELECT s.Code
FROM FRED_SOCIETE s
WHERE s.Code = '_FES' AND s.Libelle ='_SATELEC'
)
BEGIN	
UPDATE FRED_SOCIETE SET Active = 0, CodeSocietePaye = NULL WHERE Code = '_FES' AND Libelle ='_SATELEC'
END

IF EXISTS(
SELECT s.Code
FROM FRED_SOCIETE s
WHERE s.Code = '_SEM' AND s.Libelle ='_SEMERU'
)
BEGIN	
UPDATE FRED_SOCIETE SET Active = 0, CodeSocietePaye = NULL WHERE Code = '_SEM' AND Libelle ='_SEMERU'
END

IF EXISTS(
SELECT s.Code
FROM FRED_SOCIETE s
WHERE s.Code = 'E001' AND s.Libelle ='SATELEC'
)
BEGIN	
UPDATE FRED_SOCIETE SET CodeSocietePaye = '001' WHERE Code = 'E001' AND Libelle ='SATELEC'
END


IF EXISTS(
SELECT s.Code
FROM FRED_SOCIETE s
WHERE s.Code = 'E002' AND s.Libelle ='SEMERU'
)
BEGIN	
UPDATE FRED_SOCIETE SET CodeSocietePaye = '002' WHERE Code = 'E002' AND Libelle ='SEMERU'
END


IF EXISTS(
SELECT s.Code
FROM FRED_SOCIETE s
WHERE s.Code = 'E003' AND s.Libelle ='FARECO'
)
BEGIN	
UPDATE FRED_SOCIETE SET CodeSocietePaye = '003' WHERE Code = 'E003' AND Libelle ='FARECO'
END


IF EXISTS(
SELECT s.Code
FROM FRED_SOCIETE s
WHERE s.Code = 'E006' AND s.Libelle ='CITEPARK'
)
BEGIN	
UPDATE FRED_SOCIETE SET CodeSocietePaye = '006' WHERE Code = 'E006' AND Libelle ='CITEPARK'
END

IF EXISTS(
SELECT s.Code
FROM FRED_SOCIETE s
WHERE s.Code = 'E007' AND s.Libelle ='TRAFIPARC'
)
BEGIN	
UPDATE FRED_SOCIETE SET CodeSocietePaye = '007' WHERE Code = 'E007' AND Libelle ='TRAFIPARC'
END
