SET IDENTITY_INSERT [dbo].[FRED_INDEMNITE_DEPLACEMENT_CALCUL_TYPE] ON;

INSERT INTO [dbo].[FRED_INDEMNITE_DEPLACEMENT_CALCUL_TYPE] ([IndemniteDeplacementCalculTypeId], [Libelle])
VALUES(1, 'Vol d''oiseau'),(2, 'Routier'),(3, 'Réel')

SET IDENTITY_INSERT [dbo].[FRED_INDEMNITE_DEPLACEMENT_CALCUL_TYPE] OFF;