BEGIN TRANSACTION

BEGIN TRY

    DELETE FROM FRED_RAPPORT_LIGNE_PRIME WHERE RapportLigneId 
	in (1232433, 1232434)

    UPDATE FRED_RAPPORT_LIGNE SET DateSuppression = GETUTCDATE() WHERE RapportLigneId 
	in (1232433, 1232434)

END TRY  
BEGIN CATCH  
	SELECT   
		ERROR_NUMBER() AS ErrorNumber,
		ERROR_SEVERITY() AS ErrorSeverity,
		ERROR_STATE() AS ErrorState,
		ERROR_PROCEDURE() AS ErrorProcedure,
		ERROR_LINE() AS ErrorLine,
		ERROR_MESSAGE() AS ErrorMessage

	IF @@TRANCOUNT > 0 
		ROLLBACK TRANSACTION;
END CATCH
  
IF @@TRANCOUNT > 0  
	COMMIT TRANSACTION
GO