IF EXISTS (SELECT pf.PermissionId FROM FRED_PERMISSION_FONCTIONNALITE pf INNER JOIN FRED_PERMISSION p ON pf.PermissionId = p.PermissionId WHERE p.Code = '0021') 
	DELETE FRED_PERMISSION_FONCTIONNALITE WHERE PermissionId IN (SELECT PermissionId FROM FRED_PERMISSION WHERE Code = '0021')

IF EXISTS (SELECT PermissionId FROM FRED_PERMISSION WHERE Code = '0021') 
	DELETE FRED_PERMISSION WHERE Code = '0021'