IF OBJECT_ID('FRED_Get_Ressources', 'V') IS NOT NULL
    DROP VIEW FRED_Get_Ressources
GO

CREATE VIEW FRED_Get_Ressources
	AS 
		SELECT	FRED_RESSOURCE.*, 
				FRED_CHAPITRE.GroupeId
		FROM	FRED_CHAPITRE INNER JOIN
                FRED_SOUS_CHAPITRE ON FRED_CHAPITRE.ChapitreId = FRED_SOUS_CHAPITRE.ChapitreId INNER JOIN
                FRED_RESSOURCE ON FRED_SOUS_CHAPITRE.SousChapitreId = FRED_RESSOURCE.SousChapitreId
