-- --------------------------------------------------
-- FRED 2017 - R3 - AOUT 2018 
-- INJECTION DES DONNES POUR FRED - FAYAT ENERGIES SERVICES
-- CREATION DES ETABLISSEMENTS POUR SATELEC et SEMERU
-- --------------------------------------------------

-- Champs génériques pour la gestion des organisations
DECLARE @ORGA_GENE_TYPE int;
DECLARE @ORGA_GENE_PERE int;

-- ***************************************
-- ETABLISSEMENT COMPTABLE
-- ***************************************
--------------------
-- SATELEC
--------------------
DECLARE @ETABL_ORGANISATION_ID int;
DECLARE @SOCIETE_ID_GENE int;

DECLARE @SOCIETE_CODE_GENE varchar(200)='FES'
SELECT @SOCIETE_ID_GENE=(SELECT SOCIETEID FROM FRED_SOCIETE WHERE CODE=@SOCIETE_CODE_GENE)

SELECT @ORGA_GENE_TYPE='7'	-- TYPE D'ORGANISATION ETABLISSEMENT
SELECT @ORGA_GENE_PERE=(SELECT FRED_ORGANISATION.OrganisationId from FRED_ORGANISATION
inner join FRED_SOCIETE on FRED_SOCIETE.OrganisationId=FRED_ORGANISATION.OrganisationId and FRED_SOCIETE.Code=@SOCIETE_CODE_GENE)	-- PERE = SOCIETE SATELEC

IF NOT EXISTS (SELECT EtablissementComptableId FROM FRED_ETABLISSEMENT_COMPTABLE WHERE Code = '0010')
BEGIN
  -- 0010
  -- Création de l'établissement COMPTABLE dans la table FRED_ORGANISATION
  INSERT INTO FRED_ORGANISATION (TypeOrganisationId,PereId) VALUES (@ORGA_GENE_TYPE,@ORGA_GENE_PERE); 
  SET @ETABL_ORGANISATION_ID = @@IDENTITY;

  DECLARE
             @ETABL_SOCIETEID int = @SOCIETE_ID_GENE
             ,@ETABL_CODE varchar(500) = '0010'
             ,@ETABL_LIBELLE varchar(500) = 'SATELEC PIDF'
             ,@ETABL_ADRESSE varchar(500) = '24 Avenue du Général de Gaulle'
             ,@ETABL_VILLE varchar(500) = 'Viry-Châtillon'
             ,@ETABL_CODEPOSTAL varchar(500)= '91170'
             ,@ETABL_MODULECOMMANDEENABLED bit=0
             ,@ETABL_MODULEPRODUCTIONENABLED bit=0
             ,@ETABL_DATECREATION datetime=(SELECT GETDATE())
             ,@ETABL_DATEMODIFICATION datetime=NULL
             ,@ETABL_DATESUPPRESSION datetime=NULL
             ,@ETABL_AUTEURCREATIONID int=NULL
             ,@ETABL_AUTEURMODIFICATIONID int=NULL
             ,@ETABL_AUTEURSUPPRESSIONID int=NULL
             ,@ETABL_ISDELETED bit=0
             ,@ETABL_ORGANISATIONID int=@ETABL_ORGANISATION_ID
             ,@ETABL_PAYSID int=1

  insert into FRED_ETABLISSEMENT_COMPTABLE (SocieteId,Code,Libelle,Adresse,Ville,CodePostal,ModuleCommandeEnabled,ModuleProductionEnabled,DateCreation,DateModification,DateSuppression,AuteurCreationId,AuteurModificationId,AuteurSuppressionId,IsDeleted,OrganisationId,PaysId) 
  VALUES (@ETABL_SOCIETEID, @ETABL_CODE, @ETABL_LIBELLE, @ETABL_ADRESSE, @ETABL_VILLE, @ETABL_CODEPOSTAL,@ETABL_MODULECOMMANDEENABLED,@ETABL_MODULEPRODUCTIONENABLED,@ETABL_DATECREATION,@ETABL_DATEMODIFICATION,@ETABL_DATESUPPRESSION,@ETABL_AUTEURCREATIONID,@ETABL_AUTEURMODIFICATIONID,@ETABL_AUTEURSUPPRESSIONID,@ETABL_ISDELETED,@ETABL_ORGANISATIONID,@ETABL_PAYSID);

  -- 0020
  -- Création de l'établissement COMPTABLE dans la table FRED_ORGANISATION
  INSERT INTO FRED_ORGANISATION (TypeOrganisationId,PereId) VALUES (@ORGA_GENE_TYPE,@ORGA_GENE_PERE); 
  SET @ETABL_ORGANISATION_ID = @@IDENTITY;

  SELECT
             @ETABL_SOCIETEID = @SOCIETE_ID_GENE
             ,@ETABL_CODE = '0020'
             ,@ETABL_LIBELLE = 'SATELEC FRANCE NORD'
             ,@ETABL_ADRESSE  = '945, rue du faubourg d''Esquerchin'
             ,@ETABL_VILLE = 'Cuincy'
             ,@ETABL_CODEPOSTAL = '59553'
             ,@ETABL_MODULECOMMANDEENABLED =0
             ,@ETABL_MODULEPRODUCTIONENABLED =0
             ,@ETABL_DATECREATION =(SELECT GETDATE())
             ,@ETABL_DATEMODIFICATION =NULL
             ,@ETABL_DATESUPPRESSION =NULL
             ,@ETABL_AUTEURCREATIONID =NULL
             ,@ETABL_AUTEURMODIFICATIONID =NULL
             ,@ETABL_AUTEURSUPPRESSIONID =NULL
             ,@ETABL_ISDELETED =0
             ,@ETABL_ORGANISATIONID =@ETABL_ORGANISATION_ID
             ,@ETABL_PAYSID =1

  insert into FRED_ETABLISSEMENT_COMPTABLE (SocieteId,Code,Libelle,Adresse,Ville,CodePostal,ModuleCommandeEnabled,ModuleProductionEnabled,DateCreation,DateModification,DateSuppression,AuteurCreationId,AuteurModificationId,AuteurSuppressionId,IsDeleted,OrganisationId,PaysId) 
  VALUES (@ETABL_SOCIETEID, @ETABL_CODE, @ETABL_LIBELLE, @ETABL_ADRESSE, @ETABL_VILLE, @ETABL_CODEPOSTAL,@ETABL_MODULECOMMANDEENABLED,@ETABL_MODULEPRODUCTIONENABLED,@ETABL_DATECREATION,@ETABL_DATEMODIFICATION,@ETABL_DATESUPPRESSION,@ETABL_AUTEURCREATIONID,@ETABL_AUTEURMODIFICATIONID,@ETABL_AUTEURSUPPRESSIONID,@ETABL_ISDELETED,@ETABL_ORGANISATIONID,@ETABL_PAYSID);

  -- 0030
  -- Création de l'établissement COMPTABLE dans la table FRED_ORGANISATION
  INSERT INTO FRED_ORGANISATION (TypeOrganisationId,PereId) VALUES (@ORGA_GENE_TYPE,@ORGA_GENE_PERE); 
  SET @ETABL_ORGANISATION_ID = @@IDENTITY;

  SELECT
             @ETABL_SOCIETEID = @SOCIETE_ID_GENE
             ,@ETABL_CODE = '0030'
             ,@ETABL_LIBELLE = 'SATELEC PACA'
             ,@ETABL_ADRESSE  = '68 Parc de l’Argile'
             ,@ETABL_VILLE = 'Mouans-Sartoux'
             ,@ETABL_CODEPOSTAL = '06370'
             ,@ETABL_MODULECOMMANDEENABLED =0
             ,@ETABL_MODULEPRODUCTIONENABLED =0
             ,@ETABL_DATECREATION =(SELECT GETDATE())
             ,@ETABL_DATEMODIFICATION =NULL
             ,@ETABL_DATESUPPRESSION =NULL
             ,@ETABL_AUTEURCREATIONID =NULL
             ,@ETABL_AUTEURMODIFICATIONID =NULL
             ,@ETABL_AUTEURSUPPRESSIONID =NULL
             ,@ETABL_ISDELETED =0
             ,@ETABL_ORGANISATIONID =@ETABL_ORGANISATION_ID
             ,@ETABL_PAYSID =1

  insert into FRED_ETABLISSEMENT_COMPTABLE (SocieteId,Code,Libelle,Adresse,Ville,CodePostal,ModuleCommandeEnabled,ModuleProductionEnabled,DateCreation,DateModification,DateSuppression,AuteurCreationId,AuteurModificationId,AuteurSuppressionId,IsDeleted,OrganisationId,PaysId) 
  VALUES (@ETABL_SOCIETEID, @ETABL_CODE, @ETABL_LIBELLE, @ETABL_ADRESSE, @ETABL_VILLE, @ETABL_CODEPOSTAL,@ETABL_MODULECOMMANDEENABLED,@ETABL_MODULEPRODUCTIONENABLED,@ETABL_DATECREATION,@ETABL_DATEMODIFICATION,@ETABL_DATESUPPRESSION,@ETABL_AUTEURCREATIONID,@ETABL_AUTEURMODIFICATIONID,@ETABL_AUTEURSUPPRESSIONID,@ETABL_ISDELETED,@ETABL_ORGANISATIONID,@ETABL_PAYSID);

  -- 0040
  -- Création de l'établissement COMPTABLE dans la table FRED_ORGANISATION
  INSERT INTO FRED_ORGANISATION (TypeOrganisationId,PereId) VALUES (@ORGA_GENE_TYPE,@ORGA_GENE_PERE); 
  SET @ETABL_ORGANISATION_ID = @@IDENTITY;

  SELECT
             @ETABL_SOCIETEID = @SOCIETE_ID_GENE
             ,@ETABL_CODE = '0040'
             ,@ETABL_LIBELLE = 'SATELEC AQUITAINE'
             ,@ETABL_ADRESSE  = '27 Rue de Fleurenne'
             ,@ETABL_VILLE = 'Blanquefort'
             ,@ETABL_CODEPOSTAL = '33290'
             ,@ETABL_MODULECOMMANDEENABLED =0
             ,@ETABL_MODULEPRODUCTIONENABLED =0
             ,@ETABL_DATECREATION =(SELECT GETDATE())
             ,@ETABL_DATEMODIFICATION =NULL
             ,@ETABL_DATESUPPRESSION =NULL
             ,@ETABL_AUTEURCREATIONID =NULL
             ,@ETABL_AUTEURMODIFICATIONID =NULL
             ,@ETABL_AUTEURSUPPRESSIONID =NULL
             ,@ETABL_ISDELETED =0
             ,@ETABL_ORGANISATIONID =@ETABL_ORGANISATION_ID
             ,@ETABL_PAYSID =1

  insert into FRED_ETABLISSEMENT_COMPTABLE (SocieteId,Code,Libelle,Adresse,Ville,CodePostal,ModuleCommandeEnabled,ModuleProductionEnabled,DateCreation,DateModification,DateSuppression,AuteurCreationId,AuteurModificationId,AuteurSuppressionId,IsDeleted,OrganisationId,PaysId) 
  VALUES (@ETABL_SOCIETEID, @ETABL_CODE, @ETABL_LIBELLE, @ETABL_ADRESSE, @ETABL_VILLE, @ETABL_CODEPOSTAL,@ETABL_MODULECOMMANDEENABLED,@ETABL_MODULEPRODUCTIONENABLED,@ETABL_DATECREATION,@ETABL_DATEMODIFICATION,@ETABL_DATESUPPRESSION,@ETABL_AUTEURCREATIONID,@ETABL_AUTEURMODIFICATIONID,@ETABL_AUTEURSUPPRESSIONID,@ETABL_ISDELETED,@ETABL_ORGANISATIONID,@ETABL_PAYSID);

  -- 0050
  -- Création de l'établissement COMPTABLE dans la table FRED_ORGANISATION
  INSERT INTO FRED_ORGANISATION (TypeOrganisationId,PereId) VALUES (@ORGA_GENE_TYPE,@ORGA_GENE_PERE); 
  SET @ETABL_ORGANISATION_ID = @@IDENTITY;

  SELECT
             @ETABL_SOCIETEID = @SOCIETE_ID_GENE
             ,@ETABL_CODE = '0050'
             ,@ETABL_LIBELLE  = 'SATELEC PIDF'
             ,@ETABL_ADRESSE = '24 Avenue du Général de Gaulle'
             ,@ETABL_VILLE  = 'Viry-Châtillon'
             ,@ETABL_CODEPOSTAL = '91170'
             ,@ETABL_MODULECOMMANDEENABLED =0
             ,@ETABL_MODULEPRODUCTIONENABLED =0
             ,@ETABL_DATECREATION =(SELECT GETDATE())
             ,@ETABL_DATEMODIFICATION =NULL
             ,@ETABL_DATESUPPRESSION =NULL
             ,@ETABL_AUTEURCREATIONID =NULL
             ,@ETABL_AUTEURMODIFICATIONID =NULL
             ,@ETABL_AUTEURSUPPRESSIONID =NULL
             ,@ETABL_ISDELETED =0
             ,@ETABL_ORGANISATIONID =@ETABL_ORGANISATION_ID
             ,@ETABL_PAYSID =1

  insert into FRED_ETABLISSEMENT_COMPTABLE (SocieteId,Code,Libelle,Adresse,Ville,CodePostal,ModuleCommandeEnabled,ModuleProductionEnabled,DateCreation,DateModification,DateSuppression,AuteurCreationId,AuteurModificationId,AuteurSuppressionId,IsDeleted,OrganisationId,PaysId) 
  VALUES (@ETABL_SOCIETEID, @ETABL_CODE, @ETABL_LIBELLE, @ETABL_ADRESSE, @ETABL_VILLE, @ETABL_CODEPOSTAL,@ETABL_MODULECOMMANDEENABLED,@ETABL_MODULEPRODUCTIONENABLED,@ETABL_DATECREATION,@ETABL_DATEMODIFICATION,@ETABL_DATESUPPRESSION,@ETABL_AUTEURCREATIONID,@ETABL_AUTEURMODIFICATIONID,@ETABL_AUTEURSUPPRESSIONID,@ETABL_ISDELETED,@ETABL_ORGANISATIONID,@ETABL_PAYSID);

  -- 0075
  -- Création de l'établissement COMPTABLE dans la table FRED_ORGANISATION
  INSERT INTO FRED_ORGANISATION (TypeOrganisationId,PereId) VALUES (@ORGA_GENE_TYPE,@ORGA_GENE_PERE); 
  SET @ETABL_ORGANISATION_ID = @@IDENTITY;

  SELECT
             @ETABL_SOCIETEID = @SOCIETE_ID_GENE
             ,@ETABL_CODE = '0075'
             ,@ETABL_LIBELLE  = 'SATELEC PIDF'
             ,@ETABL_ADRESSE = '24 Avenue du Général de Gaulle'
             ,@ETABL_VILLE  = 'Viry-Châtillon'
             ,@ETABL_CODEPOSTAL = '91170'
             ,@ETABL_MODULECOMMANDEENABLED =0
             ,@ETABL_MODULEPRODUCTIONENABLED =0
             ,@ETABL_DATECREATION =(SELECT GETDATE())
             ,@ETABL_DATEMODIFICATION =NULL
             ,@ETABL_DATESUPPRESSION =NULL
             ,@ETABL_AUTEURCREATIONID =NULL
             ,@ETABL_AUTEURMODIFICATIONID =NULL
             ,@ETABL_AUTEURSUPPRESSIONID =NULL
             ,@ETABL_ISDELETED =0
             ,@ETABL_ORGANISATIONID =@ETABL_ORGANISATION_ID
             ,@ETABL_PAYSID =1

  insert into FRED_ETABLISSEMENT_COMPTABLE (SocieteId,Code,Libelle,Adresse,Ville,CodePostal,ModuleCommandeEnabled,ModuleProductionEnabled,DateCreation,DateModification,DateSuppression,AuteurCreationId,AuteurModificationId,AuteurSuppressionId,IsDeleted,OrganisationId,PaysId) 
  VALUES (@ETABL_SOCIETEID, @ETABL_CODE, @ETABL_LIBELLE, @ETABL_ADRESSE, @ETABL_VILLE, @ETABL_CODEPOSTAL,@ETABL_MODULECOMMANDEENABLED,@ETABL_MODULEPRODUCTIONENABLED,@ETABL_DATECREATION,@ETABL_DATEMODIFICATION,@ETABL_DATESUPPRESSION,@ETABL_AUTEURCREATIONID,@ETABL_AUTEURMODIFICATIONID,@ETABL_AUTEURSUPPRESSIONID,@ETABL_ISDELETED,@ETABL_ORGANISATIONID,@ETABL_PAYSID);

  --------------------
  -- SEMERU
  --------------------
  SELECT @SOCIETE_CODE_GENE ='SEM'
  SELECT @SOCIETE_ID_GENE=(SELECT SOCIETEID FROM FRED_SOCIETE WHERE CODE=@SOCIETE_CODE_GENE)

  SELECT @ORGA_GENE_TYPE='7'	-- TYPE D'ORGANISATION ETABLISSEMENT
  SELECT @ORGA_GENE_PERE=(SELECT FRED_ORGANISATION.OrganisationId from FRED_ORGANISATION
  inner join FRED_SOCIETE on FRED_SOCIETE.OrganisationId=FRED_ORGANISATION.OrganisationId and FRED_SOCIETE.Code=@SOCIETE_CODE_GENE)	-- PERE = SOCIETE SATELEC

  -- 0001
  -- Création de l'établissement COMPTABLE dans la table FRED_ORGANISATION
  INSERT INTO FRED_ORGANISATION (TypeOrganisationId,PereId) VALUES (@ORGA_GENE_TYPE,@ORGA_GENE_PERE); 
  SET @ETABL_ORGANISATION_ID = @@IDENTITY;

  SELECT
             @ETABL_SOCIETEID = @SOCIETE_ID_GENE
             ,@ETABL_CODE = '0001'
             ,@ETABL_LIBELLE  = 'SEMERU PIDF'
             ,@ETABL_ADRESSE = '56 Rue d''Arcueil'
             ,@ETABL_VILLE  = 'Rungis'
             ,@ETABL_CODEPOSTAL = '94150'
             ,@ETABL_MODULECOMMANDEENABLED =0
             ,@ETABL_MODULEPRODUCTIONENABLED =0
             ,@ETABL_DATECREATION =(SELECT GETDATE())
             ,@ETABL_DATEMODIFICATION =NULL
             ,@ETABL_DATESUPPRESSION =NULL
             ,@ETABL_AUTEURCREATIONID =NULL
             ,@ETABL_AUTEURMODIFICATIONID =NULL
             ,@ETABL_AUTEURSUPPRESSIONID =NULL
             ,@ETABL_ISDELETED =0
             ,@ETABL_ORGANISATIONID =@ETABL_ORGANISATION_ID
             ,@ETABL_PAYSID =1

  insert into FRED_ETABLISSEMENT_COMPTABLE (SocieteId,Code,Libelle,Adresse,Ville,CodePostal,ModuleCommandeEnabled,ModuleProductionEnabled,DateCreation,DateModification,DateSuppression,AuteurCreationId,AuteurModificationId,AuteurSuppressionId,IsDeleted,OrganisationId,PaysId) 
  VALUES (@ETABL_SOCIETEID, @ETABL_CODE, @ETABL_LIBELLE, @ETABL_ADRESSE, @ETABL_VILLE, @ETABL_CODEPOSTAL,@ETABL_MODULECOMMANDEENABLED,@ETABL_MODULEPRODUCTIONENABLED,@ETABL_DATECREATION,@ETABL_DATEMODIFICATION,@ETABL_DATESUPPRESSION,@ETABL_AUTEURCREATIONID,@ETABL_AUTEURMODIFICATIONID,@ETABL_AUTEURSUPPRESSIONID,@ETABL_ISDELETED,@ETABL_ORGANISATIONID,@ETABL_PAYSID);

END