//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.DataAccess.ExternalService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebApiEndPoints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApiEndPoints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.DataAccess.ExternalService.WebApiEndPoints", typeof(WebApiEndPoints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/oauth/token.
        /// </summary>
        internal static string Authenticate_Post_Token {
            get {
                return ResourceManager.GetString("Authenticate_Post_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/CI/UpdateCis.
        /// </summary>
        internal static string CI_UpdateCis {
            get {
                return ResourceManager.GetString("CI_UpdateCis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Commande/ExportCommandAvenantToSap.
        /// </summary>
        internal static string Commande_Get_ExportCommandeAvenantToSap {
            get {
                return ResourceManager.GetString("Commande_Get_ExportCommandeAvenantToSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Commande/ExportCommandToSap.
        /// </summary>
        internal static string Commande_Get_ExportCommandeToSap {
            get {
                return ResourceManager.GetString("Commande_Get_ExportCommandeToSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/CommandeLigne/ExportManualLockLigneDeCommandeToSap.
        /// </summary>
        internal static string CommandeLigne_Lock {
            get {
                return ResourceManager.GetString("CommandeLigne_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/CommandeLigne/ExportManualUnLockLigneDeCommandeToSap.
        /// </summary>
        internal static string CommandeLigne_UnLock {
            get {
                return ResourceManager.GetString("CommandeLigne_UnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/Depense/TransfertDepense/.
        /// </summary>
        internal static string Depense_Get_TransfertDepense {
            get {
                return ResourceManager.GetString("Depense_Get_TransfertDepense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/Depense/.
        /// </summary>
        internal static string Depense_Post {
            get {
                return ResourceManager.GetString("Depense_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/Depense/TransfertDepense/.
        /// </summary>
        internal static string Depense_Post_TransfertDepense {
            get {
                return ResourceManager.GetString("Depense_Post_TransfertDepense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/Depense/TransfertDepense/Statut/.
        /// </summary>
        internal static string Depense_Post_TransfertDepenseStatut {
            get {
                return ResourceManager.GetString("Depense_Post_TransfertDepenseStatut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/EcritureComptable/CheckImport/{1}/{2}/{3}/{4}.
        /// </summary>
        internal static string EcritureComptable_Get_Check_Import {
            get {
                return ResourceManager.GetString("EcritureComptable_Get_Check_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/EcritureComptable/ImportEcrituresComptablesFromAnael.
        /// </summary>
        internal static string EcritureComptable_ImportEcrituresComptablesFromAnael {
            get {
                return ResourceManager.GetString("EcritureComptable_ImportEcrituresComptablesFromAnael", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/EcritureComptable/Import/{1}/{2}/{3}/{4}.
        /// </summary>
        internal static string EcritureComptable_Post_Import {
            get {
                return ResourceManager.GetString("EcritureComptable_Post_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/EcritureComptable/Import/{1}/{2}/{3}/{4}/{5}/{6}.
        /// </summary>
        internal static string EcritureComptable_Post_ImportRange {
            get {
                return ResourceManager.GetString("EcritureComptable_Post_ImportRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExportPointagePersonnelToSap {
            get {
                return ResourceManager.GetString("ExportPointagePersonnelToSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/Fournisseur/Import/.
        /// </summary>
        internal static string Import_Get_Fournisseur {
            get {
                return ResourceManager.GetString("Import_Get_Fournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Moyen/ExportPointageMoyen.
        /// </summary>
        internal static string Moyen_Envoi_Pointage {
            get {
                return ResourceManager.GetString("Moyen_Envoi_Pointage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/personnel/ExportReceptionInterimairesByCisToSap/{1}.
        /// </summary>
        internal static string Personnel_Post_ExportReceptionInterimairesByCisToSap {
            get {
                return ResourceManager.GetString("Personnel_Post_ExportReceptionInterimairesByCisToSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/personnel/ExportReceptionInterimairesToSap/{1}.
        /// </summary>
        internal static string Personnel_Post_ExportReceptionInterimairesToSap {
            get {
                return ResourceManager.GetString("Personnel_Post_ExportReceptionInterimairesToSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/Personnel/UpdatePersonnels.
        /// </summary>
        internal static string Personnel_UpdatePersonnels {
            get {
                return ResourceManager.GetString("Personnel_UpdatePersonnels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Materiel/ExportPointageMaterielToStorm.
        /// </summary>
        internal static string Rapport_Get_ExportPointageMaterielToStorm {
            get {
                return ResourceManager.GetString("Rapport_Get_ExportPointageMaterielToStorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Rapport/ExportPointagePersonnelToSap.
        /// </summary>
        internal static string Rapport_Get_ExportPointagePersonnelToSap {
            get {
                return ResourceManager.GetString("Rapport_Get_ExportPointagePersonnelToSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Materiel/ExportPointageMaterielToStorm.
        /// </summary>
        internal static string Rapport_Post_ExportPointageMaterielToStorm {
            get {
                return ResourceManager.GetString("Rapport_Post_ExportPointageMaterielToStorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Rapport/ExportPointagePersonnelToSap.
        /// </summary>
        internal static string Rapport_Post_ExportPointagePersonnelToSap {
            get {
                return ResourceManager.GetString("Rapport_Post_ExportPointagePersonnelToSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/?userId={1}&amp;simulation={2}&amp;periode={3}&amp;type_periode={4}&amp;societe={5}&amp;etabs={6}.
        /// </summary>
        internal static string Rapport_Post_ExportPointagePersonnelToTibco {
            get {
                return ResourceManager.GetString("Rapport_Post_ExportPointagePersonnelToTibco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Reception/ExportReceptions/.
        /// </summary>
        internal static string Reception_Post_ExportReceptionListToSap {
            get {
                return ResourceManager.GetString("Reception_Post_ExportReceptionListToSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/ValidationPointage/ControleVrac/.
        /// </summary>
        internal static string ValidationPointage_Post_ExecuteControleVrac {
            get {
                return ResourceManager.GetString("ValidationPointage_Post_ExecuteControleVrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/ValidationPointage/RemonteePrimes/.
        /// </summary>
        internal static string ValidationPointage_Post_ExecuteRemonteePrime {
            get {
                return ResourceManager.GetString("ValidationPointage_Post_ExecuteRemonteePrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/api/ValidationPointage/RemonteeVrac/.
        /// </summary>
        internal static string ValidationPointage_Post_ExecuteRemonteeVrac {
            get {
                return ResourceManager.GetString("ValidationPointage_Post_ExecuteRemonteeVrac", resourceCulture);
            }
        }
    }
}
