-- --------------------------------------------------
-- FRED 2017 - INJECTION DES DONNES
-- --------------------------------------------------

--SET IDENTITY_INSERT FRED_ROLE ON;
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('2','1','ARH','Admin Paye','0','0','1','0','6','0'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('3','1','GSP','Gestionnaire Paye','0','0','1','0','5','0'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('4','1','CSP','Correspondant Paye','0','0','1','0','4','0'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('5','1','ACP','Admin Compta','0','0','1','0','3','10'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('6','1','RAG','Responsable Admin Gestion','15000','0','1','0','3','9'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('7','1','CDT','Conducteur travaux','5000','0','1','0','2','2'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('8','1','DRA','Directeur d''agence','9999999','0','1','0','3','5'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('9','1','CDC','Chef de Chantier','1500','0','1','0','1','1'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('10','1','CDS','Chef de secteur','15000','0','1','0','3','4'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('11','1','DRC','Directeur de chantier','15000','0','1','0','3','3'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('101','1','ADM','Admin Appli','0','0','1','1','999','999'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('102','1','ARC','Architecte SI','0','0','1','0','3','3'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('103','1','BAN','Business Analyst','0','0','1','0','2','2'); 
--INSERT INTO FRED_ROLE (RoleId,SocieteId,Code,Libelle,CommandeSeuilDefaut,ModeLecture,Actif,SuperAdmin,NiveauPaie,NiveauCompta) VALUES ('104','1','DEV','Développeur','0','0','1','0','1','1'); 
--SET IDENTITY_INSERT FRED_ROLE OFF;
