-- --------------------------------------------------
-- FRED 2017 - INJECTION DES DONNES
-- --------------------------------------------------

--SET IDENTITY_INSERT FRED_CODE_ABSENCE ON;
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('1','1','01','Visite Médicale','0','0','1.00','1.00','7.40','1.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('2','1','02','Form Econo.& syndicale','0','0','7.40','1.00','10.00','7.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('3','1','03','Congé Formation','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('4','1','04','Heures de réunions','0','0','7.40','1.00','10.00','7.00','1.00','10.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('5','1','05','Heures de délégation','0','0','7.40','1.00','10.00','7.00','1.00','10.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('6','1','07','Récupération','0','0','7.40','3.70','7.40','7.00','3.50','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('7','1','08','Amplitude','0','0','0.50','0.10','7.40','0.50','0.10','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('8','1','10','Congé Naissance','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('9','1','11','Congé Mariage','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('10','1','12','Congé Décès','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('11','1','13','Congé PACS','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('12','1','14','Formation Prof Continue','0','0','7.40','1.00','7.40','7.00','1.00','10.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('13','1','15','Repos Samedi CP','0','0','0.00','0.00','0.00','0.00','0.00','0.00','0'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('14','1','16','Jours Fériés Payés','0','0','7.40','7.00','8.00','7.00','7.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('15','1','18','Préavis Non Effectué PAYE','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('16','1','19','Recherche Emploi','0','0','7.40','1.00','7.40','7.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('17','1','20','Accident Travail','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('18','1','21','Maladie Professionnelle','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('19','1','22','Absence Autorisée non pay','0','0','7.40','1.00','10.00','7.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('20','1','23','Congé Payé','0','0','7.40','3.70','8.00','7.00','3.50','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('21','1','24','Maternité','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('22','1','25','Maladie','0','0','7.40','0.00','7.40','7.00','0.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('23','1','26','Repos A.R.T.T.','0','0','7.40','3.70','8.00','7.00','3.50','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('24','1','27','Jours Fériés Non Payés','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('25','1','28','Absence Non Autorisée','0','0','7.40','3.50','7.40','7.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('26','1','29','Absence autorisée payée','0','0','7.40','3.70','7.40','7.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('27','1','30','Modul ouv + ETAM Chantier','0','0','7.40','3.70','7.40','7.00','0.50','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('28','1','31','Accident de trajet','0','0','7.40','0.00','7.40','7.00','0.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('29','1','32','Congé Sans Solde','0','0','7.40','7.00','8.00','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('30','1','33','Congé Parental Education','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('31','1','34','Mise à Pied non payée','0','0','7.40','3.70','7.40','7.00','3.50','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('32','1','35','Congé Sabatique','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('33','1','36','Congé Création Entreprise','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('34','1','37','Repos hebdo en semaine','0','0','7.40','3.70','7.40','7.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('35','1','38','Congé Création Entreprise','0','0','7.40','3.70','7.40','7.00','3.50','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('36','1','39','Formation en chomage part','0','0','7.40','3.70','8.00','7.00','1.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('37','1','40','Chômage Partiel','0','0','7.40','1.00','8.00','7.00','1.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('38','1','42','Chômage ASSEDIC','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('39','1','43','Congé paternité','0','0','7.40','0.00','7.40','7.00','0.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('40','1','44','Ecole en alternance','0','0','7.40','0.00','8.00','7.00','0.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('41','1','46','Retard Prise du Travail','0','0','1.00','0.50','3.70','1.00','0.50','3.50','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('42','1','47','CP Fractionnement','0','0','7.40','7.00','8.00','7.00','7.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('43','1','48','CP ancienneté','0','0','7.40','3.00','8.00','7.00','3.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('44','1','49','Heures de DIF','0','0','7.40','7.00','8.00','7.00','7.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('45','1','50','Formati continue matériel','0','0','7.40','7.00','8.00','7.00','7.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('46','1','51','Formation Hors Plan','0','0','7.40','0.00','8.00','7.00','0.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('47','1','52','Transfert','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('48','1','53','Ferie Travaillé','0','0','7.40','7.00','12.00','7.00','1.00','12.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('49','1','54','Préavis Non efft non payé','0','0','7.40','7.00','8.00','7.00','7.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('50','1','55','Pont payé','0','0','7.40','7.00','8.00','7.00','7.00','8.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('51','1','56','Mise à pieds payée','0','0','7.40','7.00','8.00','7.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('52','1','57','Attente d''''affectation','0','0','7.40','7.00','8.00','7.00','1.00','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('53','1','58','Formation R- B','0','0','7.40','1.00','10.00','7.00','1.00','10.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('54','1','65','Heures Temps Partiel','0','0','7.40','3.40','7.40','7.00','3.50','7.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('55','1','95','Travail de nuit 100 %','0','0','7.40','0.00','10.00','7.00','0.00','10.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('56','1','96','Intempéries à la Maison','1','0.75','7.00','2.00','9.00','7.00','2.00','9.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('57','1','99','Intempéries','1','0.75','0.00','2.00','9.00','0.00','0.50','9.00','1'); 
--INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES ('58','1','XX','Absence non paramétrée','0','0','7.40','7.40','7.40','7.00','7.00','7.00','1'); 
--SET IDENTITY_INSERT FRED_CODE_ABSENCE OFF;




-- --------------------------------------------------
-- MEP AVRIL 2018 - INJECTION DES DONNES
-- S7 - Codes_Absences
-- --------------------------------------------------
SET IDENTITY_INSERT FRED_CODE_ABSENCE ON
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (1, NULL, 1, '1', 'Visite Médicale', 0, 0, 1, 1, 7, 1, 1, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (2, NULL, 1, '2', 'Form Econo.& syndicale', 0, 0, 7, 1, 7, 7.4, 1, 10, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (3, NULL, 1, '3', 'Congé Formation', 0, 0, 7, 7, 7, 7.4, 3.5, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (4, NULL, 1, '4', 'Heures de réunions', 0, 0, 7, 1, 10, 7.4, 1, 10, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (5, NULL, 1, '5', 'Heures de délégation', 0, 0, 7, 1, 10, 7.4, 1, 10, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (6, NULL, 1, '7', 'Récupération', 0, 0, 7, 3.5, 7, 7.4, 3.7, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (7, NULL, 1, '8', 'Amplitude', 0, 0, 0.5, 0.1, 7, 0.5, 0.1, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (8, NULL, 1, '10', 'Congé Naissance', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (9, NULL, 1, '11', 'Congé Mariage', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (10, NULL, 1, '12', 'Congé Décès', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (11, NULL, 1, '13', 'Congé PACS', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (12, NULL, 1, '14', 'Formation Prof Continue', 0, 0, 7, 1, 10, 7.4, 1, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (14, NULL, 1, '16', 'Jours Fériés Payés', 0, 0, 7, 7, 8, 7.4, 7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (15, NULL, 1, '18', 'Préavis Non Effectué PAYE', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (16, NULL, 1, '19', 'Recherche Emploi', 0, 0, 7, 1, 7, 7.4, 1, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (17, NULL, 1, '20', 'Accident Travail', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (18, NULL, 1, '21', 'Maladie Professionnelle', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (19, NULL, 1, '22', 'Absence Autorisée non pay', 0, 0, 7, 1, 7, 7.4, 1, 10, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (20, NULL, 1, '23', 'Congé Payé', 0, 0, 7, 3.5, 8, 7.4, 3.5, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (21, NULL, 1, '24', 'Maternité', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (22, NULL, 1, '25', 'Maladie', 0, 0, 7, 0, 7, 7.4, 0, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (23, NULL, 1, '26', 'Repos A.R.T.T.', 0, 0, 7, 3.5, 8, 7.4, 3.5, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (24, NULL, 1, '27', 'Jours Fériés Non Payés', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (25, NULL, 1, '28', 'Absence Non Autorisée', 0, 0, 7, 1, 7, 7.4, 3.5, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (26, NULL, 1, '29', 'Absence autorisée payée', 0, 0, 7, 1, 7, 7.4, 3.5, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (27, NULL, 1, '30', 'Modul ouv + ETAM Chantier', 0, 0, 7, 0.5, 8, 7.4, 3.7, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (28, NULL, 1, '31', 'Accident de trajet', 0, 0, 7, 0, 8, 7.4, 0, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (29, NULL, 1, '32', 'Congé Sans Solde', 0, 0, 7, 7, 7, 7.4, 7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (30, NULL, 1, '33', 'Congé Parental Education', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (31, NULL, 1, '34', 'Mise à Pied non payée', 0, 0, 7, 3.5, 7, 7.4, 3.7, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (32, NULL, 1, '35', 'Congé Sabatique', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (33, NULL, 1, '36', 'Congé Création Entreprise', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (34, NULL, 1, '37', 'Repos hebdo en semaine', 0, 0, 7, 1, 7, 7.4, 3.7, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (35, NULL, 1, '38', 'MI TEMPS THERAPEUTIQUE', 0, 0, 7, 3.5, 7, 7.4, 3.7, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (36, NULL, 1, '39', 'Formation en chomage part', 0, 0, 7, 1, 8, 7.4, 3.7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (37, NULL, 1, '40', 'Chômage Partiel', 0, 0, 7, 1, 8, 7.4, 1, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (39, NULL, 1, '42', 'Chômage ASSEDIC', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (40, NULL, 1, '43', 'Congé paternité', 0, 0, 7, 0, 7, 7.4, 0, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (41, NULL, 1, '44', 'Ecole en alternance', 0, 0, 7, 0, 8, 7.4, 0, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (43, NULL, 1, '46', 'Retard Prise du Travail', 0, 0, 1, 0.5, 3.5, 1, 0.5, 3.7, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (44, NULL, 1, '47', 'CP Fractionnement', 0, 0, 7, 7, 8, 7.4, 7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (45, NULL, 1, '48', 'CP ancienneté', 0, 0, 7, 3, 8, 7.4, 3, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (46, NULL, 1, '49', 'Heures de DIF', 0, 0, 7, 7, 8, 7.4, 7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (47, NULL, 1, '50', 'Formati continue matériel', 0, 0, 7, 7, 8, 7.4, 7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (48, NULL, 1, '51', 'Formation Hors Plan', 0, 0, 7, 0, 8, 7.4, 0, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (49, NULL, 1, '52', 'Transfert', 0, 0, 7, 7, 7, 7.4, 7.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (50, NULL, 1, '53', 'Ferie Travaillé', 0, 0, 7, 1, 12, 7.4, 7, 12, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (51, NULL, 1, '54', 'Préavis Non efft non payé', 0, 0, 7, 7, 8, 7.4, 7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (52, NULL, 1, '55', 'Pont payé', 0, 0, 7, 7, 8, 7.4, 7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (53, NULL, 1, '56', 'Mise à pieds payée', 0, 0, 7, 1, 7, 7.4, 7, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (54, NULL, 1, '57', 'Attente d affectation', 0, 0, 7, 1, 7, 7.4, 3.5, 8, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (55, NULL, 1, '58', 'Formation R- B', 0, 0, 7, 1, 10, 7.4, 1, 10, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (57, NULL, 1, '60', 'Compte Epargne Temps', 0, 0, 7, 0, 7, 7.4, 0, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (58, NULL, 1, '65', 'Heures Temps Partiel', 0, 0, 7, 3.5, 7, 7.4, 3.4, 7.4, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (59, NULL, 1, '96', 'Intempéries à la Maison', 1, 0.75, 7, 2, 9, 7, 2, 9, 1)
INSERT INTO FRED_CODE_ABSENCE (CodeAbsenceId,HoldingId,SocieteId,Code,Libelle,Intemperie,TauxDecote,NBHeuresDefautETAM,NBHeuresMinETAM,NBHeuresMaxETAM,NBHeuresDefautCO,NBHeuresMinCO,NBHeuresMaxCO,Actif) VALUES (60, NULL, 1, '99', 'Intempéries', 1, 0.75, 0, 0.5, 9, 0, 2, 9, 1)
SET IDENTITY_INSERT FRED_CODE_ABSENCE OFF
