-- --------------------------------------------------
-- MEP 2018 - Correction des données Code 
-- --------------------------------------------------
UPDATE FRED_CODE_ABSENCE SET CODE = '01' WHERE CODE = '1';
UPDATE FRED_CODE_ABSENCE SET CODE = '02' WHERE CODE = '2';
UPDATE FRED_CODE_ABSENCE SET CODE = '03' WHERE CODE = '3';
UPDATE FRED_CODE_ABSENCE SET CODE = '04' WHERE CODE = '4';
UPDATE FRED_CODE_ABSENCE SET CODE = '05' WHERE CODE = '5';
UPDATE FRED_CODE_ABSENCE SET CODE = '06' WHERE CODE = '6';
UPDATE FRED_CODE_ABSENCE SET CODE = '07' WHERE CODE = '7';
UPDATE FRED_CODE_ABSENCE SET CODE = '08' WHERE CODE = '8';
UPDATE FRED_CODE_ABSENCE SET CODE = '09' WHERE CODE = '9';