-- --------------------------------------------------
-- FRED 2017 - INJECTION DES DONNES
-- --------------------------------------------------

--SET IDENTITY_INSERT FRED_ETABLISSEMENT_PAIE ON;
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('1','00','DRN SIÈGE','3 rue rené razel, 91892 orsay','48.7335470','2.1650389','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('2','01','DRN IDF EST','526 AVENUE ALBERT EINSTEIN, 77555 MOISSY CRAMAYEL','48.6240343','2.5691465','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('3','02','GTTP VOUVRAY 35H',NULL,NULL,NULL,'1',NULL,'0','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('4','03','DRN IDF OUEST','route des gatines, 78990 elancourt','48.7849504','1.9612359','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('5','04','DRN PAYS DE LOIRE','7 chemin de la maladrie, 49070 saint jean de linieres','47.4619528','-0.6567003','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('6','05','DRN IDF GDS CHANTIER','3 rue rené razel, 91892 orsay','48.7335470','2.1650389','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('7','06','DRN NORD','143 rue gabriel peri, 59840 premesques','50.6611731','2.9567457','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('8','08','DRN MATÉRIEL','3 rue rené razel, 91892 orsay','48.7335470','2.1650389','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('9','10','DIR.INFRA.LINÉAIRES',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('10','11','DIR.GCOA BAGNOLS',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('11','12','DIR.GC/OA',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('12','14','Réunion GCOA',NULL,NULL,NULL,'1',NULL,'0','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('13','16','TRAVAUX SOUTERRAINS',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('14','19','DIR. GPE',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('15','22','DGPE BARRAGES',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('16','29','DRS TRX MAR.ET FLUV.',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('17','30','DRS SIÈGE','1111 AVENUE JUSTIN BEC, 34680 SAINT GEORGES D''ORQUES','43.6257065','3.7687788','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('18','31','DRS MIDI PYRÉNÉES','12 CHEMIN DE GARRABOT, 31771 COLOMIERS','43.5984101','1.3046460','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('19','32','DRS GDS CHANTIERS','33 AVENUE GEORGES 5, 06000 NICE','43.7116165','7.2687422','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('20','33','DRS ROUSSILLON','2470 AVENUE JULIEN PANCHOT, 66011 PERPIGNAN','42.6823567','2.8609686','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('21','34','DRS PROVENCE','1 RUE DE LISBONNE, 13744 VITROLLES','43.4264206','5.2476944','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('22','35','DRS LANGUEDOC','1111 AVENUE JUSTIN BEC, 34680 SAINT GEORGES D ORQUES','43.6257065','3.7687788','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('23','35L','LUNEL','ROUTE DE SOMMIERES, 34400 LUNEL','43.6934600','4.1403570','0','22','1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('24','36','3DOT MATÉRIAUX',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('25','37','DRS CÔTE D''AZUR','33 AVENUE GEORGES 5, 06000 NICE','43.7116165','7.2687422','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('26','38','DRS MATÉRIEL','1111 AVENUE JUSTIN BEC, 34680 SAINT GEORGES D''ORQUES','43.6257065','3.7687788','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('27','39','DRS RA DEPOT CHASSIEU','34 RUE AMPERE, 69680 CHASSIEU','45.7280227','4.9747749','1',NULL,'1','0','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('28','40','Dir.Intern.Afrique',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('29','50','3DOT',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('30','51','3DOT EBL','1111 AVENUE JUSTIN BEC, 34680 SAINT GEORGES D''ORQUES','43.6257065','3.7687788','1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('31','52','3DOT Matx.Sablières',NULL,NULL,NULL,'1',NULL,'0','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('32','90','Dir.Générale',NULL,NULL,NULL,'1',NULL,'1','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('33','B0','Dir.Infra.Linéaires',NULL,NULL,NULL,'1',NULL,'0','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('34','B1','Dir.Infra.Linéaires',NULL,NULL,NULL,'1',NULL,'0','1','1','1'); 
--INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId) VALUES ('35','B3','Dir.GC/OA',NULL,NULL,NULL,'1',NULL,'0','1','1','1'); 
--SET IDENTITY_INSERT FRED_ETABLISSEMENT_PAIE OFF;




-- --------------------------------------------------
-- MEP AVRIL 2018 - INJECTION DES DONNES
-- S16 - Etablissement_Paie
-- --------------------------------------------------
SET IDENTITY_INSERT dbo.FRED_ETABLISSEMENT_PAIE ON
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (1,'0', 'DRN SIÈGE', NULL, NULL, NULL, 1,NULL,1,0,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (2,'1', 'DRN IDF EST', '526 AVENUE ALBERT EINSTEIN', 48.6240343, 2.5691465, 1,NULL,1,0,1,1,NULL,NULL,'MOISSY CRAMAYEL','77555',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (3,'2', 'GTTP VOUVRAY 35H', NULL, NULL, NULL, 1,NULL,1,0,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (4,'3', 'DRN IDF OUEST', 'route des gatines', 48.7849504, 1.9612359, 1,NULL,1,0,1,1,NULL,NULL,'ELANCOURT','78990',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (5,'4', 'DRN PAYS DE LOIRE', '7 chemin de la maladrie', 47.4619528, -0.6567003, 1,NULL,1,0,1,1,NULL,NULL,'SAINT JEAN DE LINIERES','49070',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (6,'5', 'DRN IDF GDS CHANTIER', '3 rue rené razel', 48.733547, 2.1650389, 1,NULL,1,0,1,1,NULL,NULL,'ORSAY','91892',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (7,'6', 'DRN NORD', '143 rue gabriel peri', 50.6611731, 2.9567457, 1,NULL,1,0,1,1,NULL,NULL,'PREMESQUES','59840',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (8,'8', 'DRN MATÉRIEL', '3 rue rené razel', 48.733547, 2.1650389, 1,NULL,1,0,1,1,NULL,NULL,'ORSAY','91892',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (9,'10', 'DIR.INFRA.LINÉAIRES', NULL, NULL, NULL, 1,NULL,1,0,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (10,'11', 'DIR.GCOA BAGNOLS', 'ROUTE MICHEL LEDRAPPIER', 44.114078, 4.612165, 1,NULL,1,1,1,1,NULL,NULL,'TRESQUES','30330',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (11,'12', 'DIR.GC/OA', NULL, NULL, NULL, 1,NULL,1,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (12,'14', 'Réunion GCOA', NULL, NULL, NULL, 1,NULL,0,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (13,'16', 'TRAVAUX SOUTERRAINS', NULL, NULL, NULL, 1,NULL,1,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (14,'19', 'DIR. GPE', NULL, NULL, NULL, 1,NULL,1,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (15,'22', 'DGPE BARRAGES', NULL, NULL, NULL, 1,NULL,1,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (16,'29', 'DRS TRX MAR.ET FLUV.', NULL, NULL, NULL, 1,NULL,0,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (17,'30', 'DRS SIÈGE', '1111 AVENUE JUSTIN BEC', 43.6257065, 3.7687788, 1,NULL,1,0,1,1,NULL,NULL,'SAINT GEORGES D''ORQUES','34680',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (18,'31', 'DRS MIDI PYRÉNÉES', '12 CHEMIN DE GARRABOT', 43.5984101, 1.304646, 1,NULL,1,0,1,1,NULL,NULL,'COLOMIERS','31771',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (19,'32', 'DRS GDS CHANTIERS', '33 AVENUE GEORGES 5', 43.7116165, 7.2687422, 1,NULL,1,0,1,1,NULL,NULL,'NICE','06000',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (20,'33', 'DRS ROUSSILLON', '2470 AVENUE JULIEN PANCHOT', 42.6825103, 2.8589862, 1,NULL,1,0,1,1,NULL,NULL,'PERPIGNAN','66011',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (21,'34', 'DRS PROVENCE', '1 RUE DE LISBONNE', 43.4264206, 5.2476944, 1,NULL,1,0,1,1,NULL,NULL,'VITROLLES','13744',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (22,'35', 'DRS LANGUEDOC', '1111 AVENUE JUSTIN BEC', 43.6257065, 3.7687788, 1,NULL,1,0,1,1,NULL,NULL,'SAINT GEORGES D’ORQUES','34680',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (23,'35L', 'LUNEL', 'ROUTE DE SOMMIERES', 43.69346, 4.140357, 0,22,1,0,1,1,NULL,NULL,'LUNEL','34400',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (24,'36', '3DOT MATÉRIAUX', NULL, NULL, NULL, 1,NULL,1,0,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (25,'37', 'DRS CÔTE D AZUR', '33 AVENUE GEORGES 5', 43.7116165, 7.2687422, 1,NULL,1,0,1,1,NULL,NULL,'NICE','06000',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (26,'38', 'DRS MATÉRIEL', '1111 AVENUE JUSTIN BEC', 43.6257065, 3.7687788, 1,NULL,1,0,1,1,NULL,NULL,'SAINT GEORGES D''ORQUES','34680',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (27,'39', 'DRS RA DEPOT CHASSIEU', '34 RUE AMPERE', 45.7278681, 4.9740491, 1,NULL,1,0,1,1,NULL,NULL,'CHASSIEU','69680',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (28,'40', 'Dir.Intern.Afrique', NULL, NULL, NULL, 1,NULL,0,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (29,'50', '3DOT', NULL, NULL, NULL, 1,NULL,0,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (30,'51', '3DOT EBL', '1111 AVENUE JUSTIN BEC', 43.6257065, 3.7687788, 1,NULL,0,1,1,1,NULL,NULL,'SAINT GEORGES D''ORQUES','34680',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (31,'52', '3DOT Matx.Sablières', NULL, NULL, NULL, 1,NULL,0,1,1,1,NULL,NULL,NULL,NULL,1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (32,'53', 'GEO BIO Siège', '6 avenue des Andes', 48.6741256, 2.1455482, 1,NULL,1,1,1,1,NULL,NULL,'LES ULIS','91940',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (33,'54', 'GEOBIO Montpelllier', '1111 avenue Saint Georges d''Orques', 43.6272575, 3.7672484, 1,NULL,1,1,1,1,NULL,NULL,'SAINT GEORGES D''ORQUES','34680',1)
INSERT INTO FRED_ETABLISSEMENT_PAIE (EtablissementPaieId,Code,Libelle,Adresse,Latitude,Longitude,IsAgenceRattachement,AgenceRattachementId,GestionIndemnites,HorsRegion,Actif,SocieteId,Adresse2,Adresse3,Ville,CodePostal,PaysId) VALUES (34,'90', 'Dir.Générale', NULL, NULL, NULL, 1,NULL,0,1,1,1,NULL,NULL,NULL,NULL,1)
SET IDENTITY_INSERT dbo.FRED_ETABLISSEMENT_PAIE OFF
