DELETE A FROM (
SELECT SOCIETEDEVISEID,SOCIETEID,DEVISEID,DEVISEDEREFERENCE ,ROW_NUMBER()   OVER
(PARTITION BY  SOCIETEID,DEVISEID,DEVISEDEREFERENCE ORDER BY SOCIETEID,DEVISEID,DEVISEDEREFERENCE)AS NBDUPLICATED
FROM FRED_SOCIETE_DEVISE) AS A
WHERE A.NBDUPLICATED> 1