BEGIN 
		DECLARE @CIID int, @ParentTache int
		DECLARE C CURSOR FOR

		SELECT CIID FROM FRED_CI WHERE SOCIETEID = 1
		OPEN C
		FETCH NEXT FROM C  INTO @CIID	

		WHILE @@FETCH_STATUS = 0
		BEGIN
				SELECT  @ParentTache = TacheId FROM FRED_TACHE WHERE Code = '9999' AND CIID = @CIID
				IF NOT EXISTS(SELECT * FROM FRED_TACHE WHERE CIID = @CIID AND Code = '999998')
				BEGIN
						INSERT INTO FRED_TACHE(Code,Libelle, TacheParDefaut,Niveau,Active,CIID,ParentId,TacheType)
						VALUES('999998','ECART MATERIEL IMMOBILISE',0,3,1,@CIID,@ParentTache,9)
				END
				FETCH NEXT FROM C 
				INTO @CIID
		END
		CLOSE C
		DEALLOCATE C
END