BEGIN

    UPDATE FRED_FAMILLE_OPERATION_DIVERSE SET FRED_FAMILLE_OPERATION_DIVERSE.IsAccrued = 1
    
    UPDATE FRED_FAMILLE_OPERATION_DIVERSE SET FRED_FAMILLE_OPERATION_DIVERSE.IsAccrued = 0 WHERE Code IN ('MI','OTH')

END