BEGIN TRAN
UPDATE DESTINATION SET DESTINATION.PARENTFAMILYODWITHORDER = SRC.PARENTFAMILYODWITHORDER, DESTINATION.PARENTFAMILYODWITHOUTORDER = SRC.PARENTFAMILYODWITHOUTORDER   
FROM FRED_JOURNAL DESTINATION
INNER JOIN FRED_JOURNAL SRC ON SRC.CODE = 'SAP' AND DESTINATION.CODE = 'FRS'

COMMIT