SELECT * 
INTO #DELETE
FROM
(
    SELECT EC.ECRITURECOMPTABLEID, EC.NUMEROPIECE, EC.FAMILLEOPERATIONDIVERSEID,EC.DATECOMPTABLE,EC.LIBELLE,EC.CIID, EC.MONTANT,EC.DATECREATION ,
    ROW_NUMBER() OVER (PARTITION BY EC.NUMEROPIECE, EC.FAMILLEOPERATIONDIVERSEID,EC.DATECOMPTABLE,EC.LIBELLE,EC.CIID, EC.MONTANT ORDER BY EC.DATECREATION, EC.LIBELLE) AS DUPLICATECOUNT
    FROM FRED_ECRITURE_COMPTABLE EC
    WHERE 1=1
    AND NUMEROPIECE IS NOT NULL
) AS A
    WHERE A.DUPLICATECOUNT > 1

    DELETE EC FROM FRED_ECRITURE_COMPTABLE EC
    INNER JOIN  #DELETE D ON D.ECRITURECOMPTABLEID = EC.ECRITURECOMPTABLEID