IF  EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[FRED_saveCommande_fromBUYER]') 
AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[FRED_saveCommande_fromBUYER]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Stephen MILLER
-- Create date: 10/08/2016
-- Description:	SP d'insertion des commandes dans FRED depuis BUYER
-- =============================================
CREATE PROCEDURE FRED_saveCommande_fromBUYER
  @iCiId						INT,
  @sNumero					NVARCHAR(20),  						
  @sLibelle					NVARCHAR(250),            			
  @dtDate						DATETIME,                			
  @sTypeId					INT,        			
  @iFournisseurId				INT,	      			
  @sDelaiLivraison			NVARCHAR(100),       			
  @dtDateMiseADispo			DATETIME,      			
  @iStatutCommandeId			INT,            			
  @bMOConduite				BIT,           			
  @bEntretienMecanique		BIT,		
  @bEntretienJournalier		BIT,  			
  @bCarburant					BIT,            			
  @bLubrifiant				BIT,           			
  @bFraisAmortissement		BIT,   			
  @bFraisAssurance			BIT,      			
  @sConditionSociete			VARCHAR(500),     			
  @sConditionPrestation		VARCHAR(500),  				     	
  @sContactId					INT,       				
  @sContactTel				VARCHAR(20),						
  @sSuiviId					INT,         				      	
  @sAuteurCreationId			INT,        		        	
  @sValideurId				INT,         			
  @dtDateSaisie				DATETIME,        					
  @dtDateModification			DATETIME,    			
  @dtDateValidation			DATETIME,      			
  @sLivraisonAdresse			VARCHAR(500),	   			
  @sLivraisonVille			VARCHAR(250),					
  @sLivraisonCPostale			VARCHAR(10), 				
  @sFacturationAdresse		VARCHAR(500),				
  @sFacturationVille			VARCHAR(250),	   			
  @sFacturationCPostale		VARCHAR(10),				
  @dtDateSuppression			DATETIME,      			
  @dtDateCloture				DATETIME,	        		 		
  @sJustificatif				VARCHAR(250),          			
  @sCommentaireFournisseur	VARCHAR(500),			
  @sCommentaireInterne    	VARCHAR(500),
  @bCommandeManuelle BIT, 
  @iDeviseId INT,
  @bAccordCadre BIT,
  @CommandeId					INT OUTPUT

AS
BEGIN
  INSERT INTO dbo.FRED_COMMANDE(
    TypeId,
    FournisseurId,
    CiId,
    StatutCommandeId,
    ContactId,
    SuiviId,
    Numero,
    Libelle,
    "Date",
    DelaiLivraison,
    DateMiseADispo,
    MOConduite,
    EntretienMecanique,
    EntretienJournalier,
    Carburant,
    Lubrifiant,
    FraisAmortissement,
    FraisAssurance,
    ConditionSociete,
    ConditionPrestation,
    ContactTel,
    ValideurId,
    DateValidation,
    LivraisonAdresse,
    LivraisonVille,
    LivraisonCPostale,
    FacturationAdresse,
    FacturationVille,
    FacturationCPostale,
    DateCloture,
    Justificatif,
    CommentaireFournisseur,
    CommentaireInterne,
    CommandeManuelle,
    DeviseId,
    AuteurCreationId,
    DateCreation,
    AuteurModificationId,
    DateModification,
    AuteurSuppressionId,
    DateSuppression,
    AccordCadre)
  SELECT
    @sTypeId,
    @iFournisseurId,
    @iCiId,
    @iStatutCommandeId,
    @sContactId,
    @sSuiviId,
    @sNumero,
    @sLibelle,
    @dtDate,
    @sDelaiLivraison,
    @dtDateMiseADispo,
    @bMOConduite,
    @bEntretienMecanique,
    @bEntretienJournalier,
    @bCarburant,
    @bLubrifiant,
    @bFraisAmortissement,
    @bFraisAssurance,
    @sConditionSociete,
    @sConditionPrestation,
    @sContactTel,
    @sValideurId,
    @dtDateValidation,
    @sLivraisonAdresse,
    @sLivraisonVille,
    @sLivraisonCPostale,
    @sFacturationAdresse,
    @sFacturationVille,
    @sFacturationCPostale,
    @dtDateCloture,
    @sJustificatif,
    @sCommentaireFournisseur,
    @sCommentaireInterne,
    @bCommandeManuelle,
    @iDeviseId,
    @sAuteurCreationId,
    @dtDateSaisie,
    NULL,
    @dtDateModification,
    NULL,
    @dtDateSuppression,
    @bAccordCadre;

  SET @CommandeId = @@IDENTITY;
END
GO