// <auto-generated />
namespace Fred.ImportExport.Database.ImportExport.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTranspoCodeEmploiToRessourceEnt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTranspoCodeEmploiToRessourceEnt));
        
        string IMigrationMetadata.Id
        {
            get { return "201801151629254_AddTranspoCodeEmploiToRessourceEnt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
