// <auto-generated />
namespace Fred.ImportExport.Database.ImportExport.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FakeAddTableNlog2Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FakeAddTableNlog2Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201910052133425_FakeAddTableNlog2Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
