//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureBudget {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureBudget() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Models.App_LocalResources.FeatureBudget", typeof(FeatureBudget).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur du budget :.
        /// </summary>
        public static string BudgetDetailTpl_autheur {
            get {
                return ResourceManager.GetString("BudgetDetailTpl_autheur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crée le :.
        /// </summary>
        public static string BudgetDetailTpl_cree_le {
            get {
                return ResourceManager.GetString("BudgetDetailTpl_cree_le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de la dernière modification :.
        /// </summary>
        public static string BudgetDetailTpl_date_modif {
            get {
                return ResourceManager.GetString("BudgetDetailTpl_date_modif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière modification par :.
        /// </summary>
        public static string BudgetDetailTpl_modificateur {
            get {
                return ResourceManager.GetString("BudgetDetailTpl_modificateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant Total.
        /// </summary>
        public static string BudgetDetailTpl_montant_total {
            get {
                return ResourceManager.GetString("BudgetDetailTpl_montant_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recette.
        /// </summary>
        public static string BudgetDetailTpl_recette {
            get {
                return ResourceManager.GetString("BudgetDetailTpl_recette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valideur :.
        /// </summary>
        public static string BudgetDetailTpl_valideur {
            get {
                return ResourceManager.GetString("BudgetDetailTpl_valideur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors du chargement des taches..
        /// </summary>
        public static string BudgetRessourcesComponent_actionLoadError {
            get {
                return ResourceManager.GetString("BudgetRessourcesComponent_actionLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code_lb {
            get {
                return ResourceManager.GetString("Code_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la sauvegarde de la ressource..
        /// </summary>
        public static string CreateBudgetRessourceCpt_saveError {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceCpt_saveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la mise a jour de la ressource..
        /// </summary>
        public static string CreateBudgetRessourceCpt_updateError {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceCpt_updateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string CreateBudgetRessourceTpl_annulation {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_annulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string CreateBudgetRessourceTpl_creation {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une ressource.
        /// </summary>
        public static string CreateBudgetRessourceTpl_creer_ressource {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_creer_ressource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise.
        /// </summary>
        public static string CreateBudgetRessourceTpl_devise {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code de la ressource doit être renseignée..
        /// </summary>
        public static string CreateBudgetRessourceTpl_error_code_required {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_error_code_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le libellé de la ressource doit être renseigné..
        /// </summary>
        public static string CreateBudgetRessourceTpl_error_libelle_required {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_error_libelle_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le montant ne peux pas dépassé 999 999 999 999,99.
        /// </summary>
        public static string CreateBudgetRessourceTpl_error_max {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_error_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La recette doit être strictement positif..
        /// </summary>
        public static string CreateBudgetRessourceTpl_error_min {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_error_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le montant doit être un nombre..
        /// </summary>
        public static string CreateBudgetRessourceTpl_error_number {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_error_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le montant doit avoir une précision de 2 chiffres aprés la virgule..
        /// </summary>
        public static string CreateBudgetRessourceTpl_error_precision {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_error_precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prix est requis..
        /// </summary>
        public static string CreateBudgetRessourceTpl_error_price_required {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_error_price_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;unité de la ressource doit être renseigné..
        /// </summary>
        public static string CreateBudgetRessourceTpl_error_unite_required {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_error_unite_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour.
        /// </summary>
        public static string CreateBudgetRessourceTpl_mise_a_jour {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_mise_a_jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mise à jour d&apos;une ressource.
        /// </summary>
        public static string CreateBudgetRessourceTpl_mise_a_jour_ressource {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_mise_a_jour_ressource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string CreateBudgetRessourceTpl_prix {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource.
        /// </summary>
        public static string CreateBudgetRessourceTpl_ressource {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_ressource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource parent.
        /// </summary>
        public static string CreateBudgetRessourceTpl_ressource_parent {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_ressource_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité.
        /// </summary>
        public static string CreateBudgetRessourceTpl_unite {
            get {
                return ResourceManager.GetString("CreateBudgetRessourceTpl_unite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string index_Annuler {
            get {
                return ResourceManager.GetString("index_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string index_Annuler2 {
            get {
                return ResourceManager.GetString("index_Annuler2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Index_Budget {
            get {
                return ResourceManager.GetString("Index_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coller.
        /// </summary>
        public static string index_Coller {
            get {
                return ResourceManager.GetString("index_Coller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copier.
        /// </summary>
        public static string index_Copier {
            get {
                return ResourceManager.GetString("index_Copier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de validation.
        /// </summary>
        public static string index_Demande_de_validation {
            get {
                return ResourceManager.GetString("index_Demande_de_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string index_Enregistrer {
            get {
                return ResourceManager.GetString("index_Enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string index_Enregistrer2 {
            get {
                return ResourceManager.GetString("index_Enregistrer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramétrage budgétaire du CI.
        /// </summary>
        public static string Index_Parametrage {
            get {
                return ResourceManager.GetString("Index_Parametrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Référentiel des CI.
        /// </summary>
        public static string Index_picklist_display_label {
            get {
                return ResourceManager.GetString("Index_picklist_display_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI....
        /// </summary>
        public static string Index_picklist_placeholder {
            get {
                return ResourceManager.GetString("Index_picklist_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI....
        /// </summary>
        public static string Index_picklist_search_placeholder {
            get {
                return ResourceManager.GetString("Index_picklist_search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans des tâches.
        /// </summary>
        public static string index_Plans_des_taches {
            get {
                return ResourceManager.GetString("index_Plans_des_taches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour refermer le panneau.
        /// </summary>
        public static string index_refermer_le_panneau {
            get {
                return ResourceManager.GetString("index_refermer_le_panneau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refermer le panneau.
        /// </summary>
        public static string index_Refermer_le_panneau2 {
            get {
                return ResourceManager.GetString("index_Refermer_le_panneau2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rejeter le Budget.
        /// </summary>
        public static string index_rejeter_le_Budget {
            get {
                return ResourceManager.GetString("index_rejeter_le_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources.
        /// </summary>
        public static string index_Ressources {
            get {
                return ResourceManager.GetString("index_Ressources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour au budget.
        /// </summary>
        public static string index_Retour_au_budget {
            get {
                return ResourceManager.GetString("index_Retour_au_budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâches.
        /// </summary>
        public static string Index_Taches {
            get {
                return ResourceManager.GetString("Index_Taches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider le Budget.
        /// </summary>
        public static string index_Valider_le_Budget {
            get {
                return ResourceManager.GetString("index_Valider_le_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libelle.
        /// </summary>
        public static string Libelle_lb {
            get {
                return ResourceManager.GetString("Libelle_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string SavePriceRessourceDialogTemplate_annuler {
            get {
                return ResourceManager.GetString("SavePriceRessourceDialogTemplate_annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string SavePriceRessourceDialogTemplate_confirmation {
            get {
                return ResourceManager.GetString("SavePriceRessourceDialogTemplate_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string SavePriceRessourceDialogTemplate_non {
            get {
                return ResourceManager.GetString("SavePriceRessourceDialogTemplate_non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string SavePriceRessourceDialogTemplate_oui {
            get {
                return ResourceManager.GetString("SavePriceRessourceDialogTemplate_oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez vous étendre la modification au referentiel ?.
        /// </summary>
        public static string SavePriceRessourceDialogTemplate_titre {
            get {
                return ResourceManager.GetString("SavePriceRessourceDialogTemplate_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En modifiant la recette de cette tache, vous mettez à zero la recette sur les niveaux inferieurs et vous modifiez les recettes parentes. Voulez vous continuer ?.
        /// </summary>
        public static string TacheBudgetComponent_message_dialog {
            get {
                return ResourceManager.GetString("TacheBudgetComponent_message_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avancement.
        /// </summary>
        public static string TacheBudgetTemplate_AVANCEMENT {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_AVANCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infos.
        /// </summary>
        public static string TacheBudgetTemplate_iNFOS {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_iNFOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string TacheBudgetTemplate_MONTANT {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_MONTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix Unitaire.
        /// </summary>
        public static string TacheBudgetTemplate_PRIX_UNITAIRE {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_PRIX_UNITAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string TacheBudgetTemplate_QUANTITE {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_QUANTITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le montant ne peux pas dépasser 999 999 999 999,99..
        /// </summary>
        public static string TacheBudgetTemplate_quantiteARealise_error_max {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_quantiteARealise_error_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le montant doit être un nombre..
        /// </summary>
        public static string TacheBudgetTemplate_quantiteARealise_error_number {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_quantiteARealise_error_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le montant doit avoir une précision de 2 chiffres aprés la virgule..
        /// </summary>
        public static string TacheBudgetTemplate_quantiteARealise_error_pattern {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_quantiteARealise_error_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recette.
        /// </summary>
        public static string TacheBudgetTemplate_RECETTE {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_RECETTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La recette ne peux pas dépassé 999 999 999 999,99.
        /// </summary>
        public static string TacheBudgetTemplate_recette_error_max {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_recette_error_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La recette doit être un nombre..
        /// </summary>
        public static string TacheBudgetTemplate_recette_error_number {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_recette_error_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La recette doit avoir une précision de 2 chiffres aprés la virgule..
        /// </summary>
        public static string TacheBudgetTemplate_recette_error_pattern {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_recette_error_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ressources non parametrées.
        /// </summary>
        public static string TacheBudgetTemplate_RNP {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_RNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;Avancement.
        /// </summary>
        public static string TacheBudgetTemplate_TYPE_AVANCEMENT {
            get {
                return ResourceManager.GetString("TacheBudgetTemplate_TYPE_AVANCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification du référentiel réussie..
        /// </summary>
        public static string TacheDetailComponent_createParameterSuccess {
            get {
                return ResourceManager.GetString("TacheDetailComponent_createParameterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de l&apos;enregistrement de la tache..
        /// </summary>
        public static string TacheDetailComponent_saveTaskError {
            get {
                return ResourceManager.GetString("TacheDetailComponent_saveTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement réussi..
        /// </summary>
        public static string TacheDetailComponent_saveTaskSuccess {
            get {
                return ResourceManager.GetString("TacheDetailComponent_saveTaskSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la sauvegarde du référentiel..
        /// </summary>
        public static string TacheDetailComponent_updateRessourceError {
            get {
                return ResourceManager.GetString("TacheDetailComponent_updateRessourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapitre.
        /// </summary>
        public static string TacheDetailTemplate_chapitre {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_chapitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formule.
        /// </summary>
        public static string TacheDetailTemplate_Formule {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Formule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures MO par unité.
        /// </summary>
        public static string TacheDetailTemplate_Heures_MO_par_unite {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Heures_MO_par_unite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé Ressource.
        /// </summary>
        public static string TacheDetailTemplate_Libelle_Ressource {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Libelle_Ressource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string TacheDetailTemplate_Montant {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Montant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix Total QB.
        /// </summary>
        public static string TacheDetailTemplate_Prix_Total_QB {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Prix_Total_QB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix Total T4.
        /// </summary>
        public static string TacheDetailTemplate_Prix_Total_T4 {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Prix_Total_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix Unitaire.
        /// </summary>
        public static string TacheDetailTemplate_Prix_Unitaire {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Prix_Unitaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix unitaire QB.
        /// </summary>
        public static string TacheDetailTemplate_Prix_unitaire_QB {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Prix_unitaire_QB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix unitaire T4.
        /// </summary>
        public static string TacheDetailTemplate_Prix_unitaire_T4 {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Prix_unitaire_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string TacheDetailTemplate_Quantite {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Quantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité à réaliser.
        /// </summary>
        public static string TacheDetailTemplate_Quantite_a_realiser {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Quantite_a_realiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité de base.
        /// </summary>
        public static string TacheDetailTemplate_Quantite_de_base {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Quantite_de_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource.
        /// </summary>
        public static string TacheDetailTemplate_Ressource {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Ressource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-Chapitre.
        /// </summary>
        public static string TacheDetailTemplate_Sous_Chapitre {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Sous_Chapitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous détail.
        /// </summary>
        public static string TacheDetailTemplate_Sous_detail {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Sous_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string TacheDetailTemplate_Supprimer {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Heures MO.
        /// </summary>
        public static string TacheDetailTemplate_Total_Heures_MO {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Total_Heures_MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total heures MO T4.
        /// </summary>
        public static string TacheDetailTemplate_Total_heures_MO_T4 {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Total_heures_MO_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité.
        /// </summary>
        public static string TacheDetailTemplate_Unite {
            get {
                return ResourceManager.GetString("TacheDetailTemplate_Unite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors du chargement du budget..
        /// </summary>
        public static string TachesBudgetComponent_getBudgetError {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_getBudgetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors du chargement des taches..
        /// </summary>
        public static string TachesBudgetComponent_getBudgetRevisionTachesError {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_getBudgetRevisionTachesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors du passage du budget à l&apos;état brouillon..
        /// </summary>
        public static string TachesBudgetComponent_updateBudgetRevisionForDaftError {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_updateBudgetRevisionForDaftError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le budget est à l&apos;état brouillon..
        /// </summary>
        public static string TachesBudgetComponent_updateBudgetRevisionForDaftSuccess {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_updateBudgetRevisionForDaftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la soumission du budget..
        /// </summary>
        public static string TachesBudgetComponent_updateBudgetRevisionForDoValidationError {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_updateBudgetRevisionForDoValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soumission pour validation réussie..
        /// </summary>
        public static string TachesBudgetComponent_updateBudgetRevisionForDoValidationSuccess {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_updateBudgetRevisionForDoValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la validation du budget..
        /// </summary>
        public static string TachesBudgetComponent_updateBudgetRevisionForValidationError {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_updateBudgetRevisionForValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation du budget réussie..
        /// </summary>
        public static string TachesBudgetComponent_updateBudgetRevisionForValidationSuccess {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_updateBudgetRevisionForValidationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la sauvegarde des taches..
        /// </summary>
        public static string TachesBudgetComponent_updateBudgetRevisionTachesError {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_updateBudgetRevisionTachesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement réussi..
        /// </summary>
        public static string TachesBudgetComponent_updateBudgetRevisionTachesSuccess {
            get {
                return ResourceManager.GetString("TachesBudgetComponent_updateBudgetRevisionTachesSuccess", resourceCulture);
            }
        }
    }
}
