//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureOrganisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureOrganisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Models.App_LocalResources.FeatureOrganisation", typeof(FeatureOrganisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un seuil.
        /// </summary>
        public static string AjouterSeuil_lb {
            get {
                return ResourceManager.GetString("AjouterSeuil_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les seuils de commande par organisation.
        /// </summary>
        public static string GererSeuilOrganisation_lb {
            get {
                return ResourceManager.GetString("GererSeuilOrganisation_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des devises.
        /// </summary>
        public static string ListeDevises_lb {
            get {
                return ResourceManager.GetString("ListeDevises_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des rôles.
        /// </summary>
        public static string ListeRoles_lb {
            get {
                return ResourceManager.GetString("ListeRoles_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier un seuil.
        /// </summary>
        public static string ModifierSeuil_lb {
            get {
                return ResourceManager.GetString("ModifierSeuil_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une organisation.
        /// </summary>
        public static string SelectionnerOrga_lb {
            get {
                return ResourceManager.GetString("SelectionnerOrga_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour modifier le seuil.
        /// </summary>
        public static string SeuilEditer_lb {
            get {
                return ResourceManager.GetString("SeuilEditer_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to définie(s) sur ce rôle.
        /// </summary>
        public static string TooltipTuileDevise_lb {
            get {
                return ResourceManager.GetString("TooltipTuileDevise_lb", resourceCulture);
            }
        }
    }
}
