//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureCommande {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureCommande() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Models.App_LocalResources.FeatureCommande", typeof(FeatureCommande).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour afficher le détail de la commande en priorité.
        /// </summary>
        public static string Commande_Detail_AffichageDetailPrioritaire {
            get {
                return ResourceManager.GetString("Commande_Detail_AffichageDetailPrioritaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour afficher les lignes de la commande sur le côté.
        /// </summary>
        public static string Commande_Detail_AffichageLignePrioritaire {
            get {
                return ResourceManager.GetString("Commande_Detail_AffichageLignePrioritaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dupliquer.
        /// </summary>
        public static string Commande_Detail_Bouton_Dupliquer {
            get {
                return ResourceManager.GetString("Commande_Detail_Bouton_Dupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregister Brouillon.
        /// </summary>
        public static string Commande_Detail_Bouton_EnregistrerBrouillon {
            get {
                return ResourceManager.GetString("Commande_Detail_Bouton_EnregistrerBrouillon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de commande et libellé obligatoires.
        /// </summary>
        public static string Commande_Detail_Bouton_EnregistrerBrouillon_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Detail_Bouton_EnregistrerBrouillon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer Commande.
        /// </summary>
        public static string Commande_Detail_Bouton_EnregistrerCommande {
            get {
                return ResourceManager.GetString("Commande_Detail_Bouton_EnregistrerCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de commande et libellé obligatoires.
        /// </summary>
        public static string Commande_Detail_Bouton_EnregistrerCommande_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Detail_Bouton_EnregistrerCommande_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoi par mail.
        /// </summary>
        public static string Commande_Detail_Bouton_EnvoiMail {
            get {
                return ResourceManager.GetString("Commande_Detail_Bouton_EnvoiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        public static string Commande_Detail_Bouton_Imprimer {
            get {
                return ResourceManager.GetString("Commande_Detail_Bouton_Imprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viser.
        /// </summary>
        public static string Commande_Detail_Bouton_Viser {
            get {
                return ResourceManager.GetString("Commande_Detail_Bouton_Viser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des erreurs.
        /// </summary>
        public static string Commande_Detail_ListeErreurs {
            get {
                return ResourceManager.GetString("Commande_Detail_ListeErreurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant HT.
        /// </summary>
        public static string Commande_Detail_MontantHT {
            get {
                return ResourceManager.GetString("Commande_Detail_MontantHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner à la liste des commandes.
        /// </summary>
        public static string Commande_Detail_RetourListeCommande {
            get {
                return ResourceManager.GetString("Commande_Detail_RetourListeCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour retourner à la liste des commandes.
        /// </summary>
        public static string Commande_Detail_RetourListeCommande_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Detail_RetourListeCommande_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaires.
        /// </summary>
        public static string Commande_Detail_SectionCommentaire {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCommentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire fournisseur.
        /// </summary>
        public static string Commande_Detail_SectionCommentaire_Fournisseur {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCommentaire_Fournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire fournisseur.
        /// </summary>
        public static string Commande_Detail_SectionCommentaire_Fournisseur_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCommentaire_Fournisseur_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire interne.
        /// </summary>
        public static string Commande_Detail_SectionCommentaire_Interne {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCommentaire_Interne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire interne.
        /// </summary>
        public static string Commande_Detail_SectionCommentaire_Interne_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCommentaire_Interne_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordonnées.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de facturation.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_Facturation {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_Facturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de facturation.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_FacturationAdresse_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_FacturationAdresse_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_FacturationCodePostal_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_FacturationCodePostal_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_FacturationVille_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_FacturationVille_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de livraison.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_Livraison {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_Livraison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse de livraison.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_LivraisonAdresse_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_LivraisonAdresse_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_LivraisonCodePostal_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_LivraisonCodePostal_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entête.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_LivraisonEntete_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_LivraisonEntete_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string Commande_Detail_SectionCoordonnee_LivraisonVille_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionCoordonnee_LivraisonVille_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail de la commande.
        /// </summary>
        public static string Commande_Detail_SectionDetail {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achat &gt; 15k €.
        /// </summary>
        public static string Commande_Detail_SectionDetail_AccordCadre {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_AccordCadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chantier.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Chantier {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Chantier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande manuelle.
        /// </summary>
        public static string Commande_Detail_SectionDetail_CommandeManuelle {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_CommandeManuelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Date {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Devise {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Fournisseur {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Fournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUSTIFICATIF.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Justificatif {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Justificatif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé de la commande.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Libelle {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé de la commande.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Libelle_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Libelle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Type {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de commande.
        /// </summary>
        public static string Commande_Detail_SectionDetail_Type_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionDetail_Type_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations spécifiques.
        /// </summary>
        public static string Commande_Detail_SectionInfo {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le carburant.
        /// </summary>
        public static string Commande_Detail_SectionInfo_Carburant {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_Carburant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITIONS CLIENT.
        /// </summary>
        public static string Commande_Detail_SectionInfo_ConditionClient {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_ConditionClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITIONS CLIENT.
        /// </summary>
        public static string Commande_Detail_SectionInfo_ConditionClient_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_ConditionClient_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITIONS PRESTATAIRE.
        /// </summary>
        public static string Commande_Detail_SectionInfo_ConditionPresta {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_ConditionPresta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITIONS PRESTATAIRE.
        /// </summary>
        public static string Commande_Detail_SectionInfo_ConditionPresta_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_ConditionPresta_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entretien journalier, vidange, graissage, filtres.
        /// </summary>
        public static string Commande_Detail_SectionInfo_EntretienJournalier {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_EntretienJournalier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;entretetien mécanique (pièces, main d&apos;oeuvre).
        /// </summary>
        public static string Commande_Detail_SectionInfo_EntretienMecanique {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_EntretienMecanique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les frais d&apos;amortissemnt.
        /// </summary>
        public static string Commande_Detail_SectionInfo_FraisAmortissement {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_FraisAmortissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les impôts et assurances toutes natures.
        /// </summary>
        public static string Commande_Detail_SectionInfo_FraisAssurance {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_FraisAssurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le lubrifiant.
        /// </summary>
        public static string Commande_Detail_SectionInfo_Lubrifiant {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_Lubrifiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La main d&apos;oeuvre de conduite.
        /// </summary>
        public static string Commande_Detail_SectionInfo_MOConduite {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_MOConduite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclu(s) dans le tarif de location.
        /// </summary>
        public static string Commande_Detail_SectionInfo_TarifLocation {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionInfo_TarifLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi de la commande.
        /// </summary>
        public static string Commande_Detail_SectionSuivi {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionSuivi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Livraison.
        /// </summary>
        public static string Commande_Detail_SectionSuivi_Contact {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionSuivi_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Téléphonique.
        /// </summary>
        public static string Commande_Detail_SectionSuivi_ContactTelephonique {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionSuivi_ContactTelephonique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Téléphonique.
        /// </summary>
        public static string Commande_Detail_SectionSuivi_ContactTelephonique_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionSuivi_ContactTelephonique_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de dispo.
        /// </summary>
        public static string Commande_Detail_SectionSuivi_DateDispo {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionSuivi_DateDispo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délai de livraison.
        /// </summary>
        public static string Commande_Detail_SectionSuivi_DelaiLivraison {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionSuivi_DelaiLivraison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délai de livraison.
        /// </summary>
        public static string Commande_Detail_SectionSuivi_DelaiLivraison_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionSuivi_DelaiLivraison_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi.
        /// </summary>
        public static string Commande_Detail_SectionSuivi_Suivi {
            get {
                return ResourceManager.GetString("Commande_Detail_SectionSuivi_Suivi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En-tête de la commande.
        /// </summary>
        public static string Commande_Detail_SousTitre_Detail {
            get {
                return ResourceManager.GetString("Commande_Detail_SousTitre_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail de la commande.
        /// </summary>
        public static string Commande_Detail_Titre {
            get {
                return ResourceManager.GetString("Commande_Detail_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commande(s).
        /// </summary>
        public static string Commande_Index_NbrCommande {
            get {
                return ResourceManager.GetString("Commande_Index_NbrCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle commande.
        /// </summary>
        public static string Commande_Index_NouvelleCommande {
            get {
                return ResourceManager.GetString("Commande_Index_NouvelleCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour créer une nouvelle commande.
        /// </summary>
        public static string Commande_Index_NouvelleCommande_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Index_NouvelleCommande_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une Commande ....
        /// </summary>
        public static string Commande_Index_Rechercher_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Index_Rechercher_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des commandes.
        /// </summary>
        public static string Commande_Index_SousTitre_ListeCommande {
            get {
                return ResourceManager.GetString("Commande_Index_SousTitre_ListeCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, aucune réception disponible pour cette commande.
        /// </summary>
        public static string Commande_Index_Table_AucuneReception_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Index_Table_AucuneReception_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre d&apos;imputation.
        /// </summary>
        public static string Commande_Index_Table_CI {
            get {
                return ResourceManager.GetString("Commande_Index_Table_CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloturée manuellement.
        /// </summary>
        public static string Commande_Index_Table_ClotureManuelle {
            get {
                return ResourceManager.GetString("Commande_Index_Table_ClotureManuelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Commande_Index_Table_Date {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date d&apos;émission.
        /// </summary>
        public static string Commande_Index_Table_DateEmission {
            get {
                return ResourceManager.GetString("Commande_Index_Table_DateEmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de validation.
        /// </summary>
        public static string Commande_Index_Table_DateValidation {
            get {
                return ResourceManager.GetString("Commande_Index_Table_DateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandeur.
        /// </summary>
        public static string Commande_Index_Table_Demandeur {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Demandeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière actualisation le {0} par {1}.
        /// </summary>
        public static string Commande_Index_Table_DerniereModification {
            get {
                return ResourceManager.GetString("Commande_Index_Table_DerniereModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail de la commande.
        /// </summary>
        public static string Commande_Index_Table_Detail {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour visualiser le détail de la commande.
        /// </summary>
        public static string Commande_Index_Table_Detail_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Detail_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devise:.
        /// </summary>
        public static string Commande_Index_Table_Devise {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Devise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fournisseur.
        /// </summary>
        public static string Commande_Index_Table_Fournisseur {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Fournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant commandé.
        /// </summary>
        public static string Commande_Index_Table_MontantCommande {
            get {
                return ResourceManager.GetString("Commande_Index_Table_MontantCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant commandé par l&apos;utilisateur.
        /// </summary>
        public static string Commande_Index_Table_MontantCommande_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Index_Table_MontantCommande_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant réceptionné.
        /// </summary>
        public static string Commande_Index_Table_MontantReception {
            get {
                return ResourceManager.GetString("Commande_Index_Table_MontantReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant réceptionné par l&apos;utilisateur.
        /// </summary>
        public static string Commande_Index_Table_MontantReception_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Index_Table_MontantReception_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa(s).
        /// </summary>
        public static string Commande_Index_Table_NbrVisa {
            get {
                return ResourceManager.GetString("Commande_Index_Table_NbrVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapprochée.
        /// </summary>
        public static string Commande_Index_Table_Rapprochee {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Rapprochee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les réceptions.
        /// </summary>
        public static string Commande_Index_Table_Reception {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour visualiser les réceptions liées à cette commande.
        /// </summary>
        public static string Commande_Index_Table_Reception_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Reception_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solde.
        /// </summary>
        public static string Commande_Index_Table_Solde {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Solde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restant à réceptionner de la commande.
        /// </summary>
        public static string Commande_Index_Table_Solde_placeholder {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Solde_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valideur.
        /// </summary>
        public static string Commande_Index_Table_Valideur {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Valideur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string Commande_Index_Table_Visa {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez pour visualiser les visas.
        /// </summary>
        public static string Commande_Index_Table_Visa_Tooltip {
            get {
                return ResourceManager.GetString("Commande_Index_Table_Visa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer les commandes.
        /// </summary>
        public static string Commande_Index_Titre {
            get {
                return ResourceManager.GetString("Commande_Index_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout sélectionner.
        /// </summary>
        public static string Commande_Index_ToutSelectionner {
            get {
                return ResourceManager.GetString("Commande_Index_ToutSelectionner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;une ligne.
        /// </summary>
        public static string Commande_LignesCommande_Bouton_Ajouter {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Bouton_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désignation.
        /// </summary>
        public static string Commande_LignesCommande_Entete_Libelle {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Entete_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant HT.
        /// </summary>
        public static string Commande_LignesCommande_Entete_MontantHT {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Entete_MontantHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PU HT.
        /// </summary>
        public static string Commande_LignesCommande_Entete_PUHT {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Entete_PUHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string Commande_LignesCommande_Entete_Quantite {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Entete_Quantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource.
        /// </summary>
        public static string Commande_LignesCommande_Entete_Ressource {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Entete_Ressource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâche.
        /// </summary>
        public static string Commande_LignesCommande_Entete_Tache {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Entete_Tache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unité.
        /// </summary>
        public static string Commande_LignesCommande_Entete_Unite {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Entete_Unite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dupliquer la ligne.
        /// </summary>
        public static string Commande_LignesCommande_Table_Bouton_Dupliquer {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Table_Bouton_Dupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la ligne.
        /// </summary>
        public static string Commande_LignesCommande_Table_Bouton_Supprimer {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Table_Bouton_Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lignes de la commande.
        /// </summary>
        public static string Commande_LignesCommande_Titre {
            get {
                return ResourceManager.GetString("Commande_LignesCommande_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de l&apos;envoie du message électronique. Veuillez consulter la liste des erreurs à l&apos;aide de l&apos;icone d&apos;erreur..
        /// </summary>
        public static string Commande_Notification_EmailEnvoyer_Error {
            get {
                return ResourceManager.GetString("Commande_Notification_EmailEnvoyer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message électronique envoyé avec succés..
        /// </summary>
        public static string Commande_Notification_EmailEnvoyer_Success {
            get {
                return ResourceManager.GetString("Commande_Notification_EmailEnvoyer_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seul le créateur de cette commande peut la supprimer.
        /// </summary>
        public static string Commande_Notification_ErreurBadUser_Error {
            get {
                return ResourceManager.GetString("Commande_Notification_ErreurBadUser_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreurs de saisie détectées : veuillez consulter la liste des erreurs à l&apos;aide de l&apos;icone d&apos;erreur..
        /// </summary>
        public static string Commande_Notification_Saisie_Error {
            get {
                return ResourceManager.GetString("Commande_Notification_Saisie_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Choisir Statut.
        /// </summary>
        public static string Commande_Search_ChoixStatut {
            get {
                return ResourceManager.GetString("Commande_Search_ChoixStatut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Choisir Type.
        /// </summary>
        public static string Commande_Search_ChoixType {
            get {
                return ResourceManager.GetString("Commande_Search_ChoixType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De ....
        /// </summary>
        public static string Commande_Search_DateDebut_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Search_DateDebut_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ....
        /// </summary>
        public static string Commande_Search_DateFin_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Search_DateFin_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seulement mes commandes.
        /// </summary>
        public static string Commande_Search_MesCommandes {
            get {
                return ResourceManager.GetString("Commande_Search_MesCommandes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant Total HT max..
        /// </summary>
        public static string Commande_Search_MontantMax_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Search_MontantMax_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant Total HT min..
        /// </summary>
        public static string Commande_Search_MontantMin_Placeholder {
            get {
                return ResourceManager.GetString("Commande_Search_MontantMin_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début.
        /// </summary>
        public static string Commande_Search_Tuile_DateDebut {
            get {
                return ResourceManager.GetString("Commande_Search_Tuile_DateDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin.
        /// </summary>
        public static string Commande_Search_Tuile_DateFin {
            get {
                return ResourceManager.GetString("Commande_Search_Tuile_DateFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes Commandes.
        /// </summary>
        public static string Commande_Search_Tuile_MesCommandes {
            get {
                return ResourceManager.GetString("Commande_Search_Tuile_MesCommandes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant &lt; .
        /// </summary>
        public static string Commande_Search_Tuile_MontantMax {
            get {
                return ResourceManager.GetString("Commande_Search_Tuile_MontantMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant &gt; .
        /// </summary>
        public static string Commande_Search_Tuile_MontantMin {
            get {
                return ResourceManager.GetString("Commande_Search_Tuile_MontantMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut : .
        /// </summary>
        public static string Commande_Search_Tuile_Statut {
            get {
                return ResourceManager.GetString("Commande_Search_Tuile_Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de commande : .
        /// </summary>
        public static string Commande_Search_Tuile_Type {
            get {
                return ResourceManager.GetString("Commande_Search_Tuile_Type", resourceCulture);
            }
        }
    }
}
