//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureModule {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureModule() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Models.App_LocalResources.FeatureModule", typeof(FeatureModule).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création.
        /// </summary>
        public static string ActionCreation_lb {
            get {
                return ResourceManager.GetString("ActionCreation_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        public static string ActionModification_lb {
            get {
                return ResourceManager.GetString("ActionModification_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un module.
        /// </summary>
        public static string Button_AddModule_lb {
            get {
                return ResourceManager.GetString("Button_AddModule_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fonctionnalité.
        /// </summary>
        public static string Button_Feature_lb {
            get {
                return ResourceManager.GetString("Button_Feature_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer cette fonctionnalité ?.
        /// </summary>
        public static string ConfirmDeleteFeature_lb {
            get {
                return ResourceManager.GetString("ConfirmDeleteFeature_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer ce module ?.
        /// </summary>
        public static string ConfirmDeleteModule_lb {
            get {
                return ResourceManager.GetString("ConfirmDeleteModule_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonctionnalité.
        /// </summary>
        public static string Fonctionnalite_lb {
            get {
                return ResourceManager.GetString("Fonctionnalite_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string FonctionnaliteAnnuler_lb {
            get {
                return ResourceManager.GetString("FonctionnaliteAnnuler_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code doit être renseigné.
        /// </summary>
        public static string FonctionnaliteCode_Error_lb {
            get {
                return ResourceManager.GetString("FonctionnaliteCode_Error_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string FonctionnaliteCode_lb {
            get {
                return ResourceManager.GetString("FonctionnaliteCode_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string FonctionnaliteEnregistrer_lb {
            get {
                return ResourceManager.GetString("FonctionnaliteEnregistrer_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hors Organisation.
        /// </summary>
        public static string FonctionnaliteHorsOrganisation_lb {
            get {
                return ResourceManager.GetString("FonctionnaliteHorsOrganisation_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le libellé doit être renseigné.
        /// </summary>
        public static string FonctionnaliteLibelle_Error_lb {
            get {
                return ResourceManager.GetString("FonctionnaliteLibelle_Error_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string FonctionnaliteLibelle_lb {
            get {
                return ResourceManager.GetString("FonctionnaliteLibelle_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur la fonctionnalité sélectionnée.
        /// </summary>
        public static string InfosFonctionnalite_lb {
            get {
                return ResourceManager.GetString("InfosFonctionnalite_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur le module sélectionné.
        /// </summary>
        public static string InfosModule_lb {
            get {
                return ResourceManager.GetString("InfosModule_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module_lb {
            get {
                return ResourceManager.GetString("Module_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string ModuleAnnuler_lb {
            get {
                return ResourceManager.GetString("ModuleAnnuler_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code doit être renseigné.
        /// </summary>
        public static string ModuleCode_Error_lb {
            get {
                return ResourceManager.GetString("ModuleCode_Error_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ModuleCode_lb {
            get {
                return ResourceManager.GetString("ModuleCode_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string ModuleEnregistrer_lb {
            get {
                return ResourceManager.GetString("ModuleEnregistrer_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le libellé doit être renseigné.
        /// </summary>
        public static string ModuleLibelle_Error_lb {
            get {
                return ResourceManager.GetString("ModuleLibelle_Error_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string ModuleLibelle_lb {
            get {
                return ResourceManager.GetString("ModuleLibelle_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules_lb {
            get {
                return ResourceManager.GetString("Modules_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le rôle doit être sélectionné.
        /// </summary>
        public static string Role_Error_lb {
            get {
                return ResourceManager.GetString("Role_Error_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonctionnalités....
        /// </summary>
        public static string SearchFonctionnalites_placeholder {
            get {
                return ResourceManager.GetString("SearchFonctionnalites_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules....
        /// </summary>
        public static string SearchModules_placeholder {
            get {
                return ResourceManager.GetString("SearchModules_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration du référentiel des modules et fonctionnalités.
        /// </summary>
        public static string Title_lb {
            get {
                return ResourceManager.GetString("Title_lb", resourceCulture);
            }
        }
    }
}
