//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureEtablissementComptable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureEtablissementComptable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Models.App_LocalResources.FeatureEtablissementComptable", typeof(FeatureEtablissementComptable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un Etablissement Comptable ....
        /// </summary>
        public static string EtablissementComptable_PanelMain_Recherche_Placeholder {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelMain_Recherche_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande.
        /// </summary>
        public static string EtablissementComptable_PanelMain_Table_Commande {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelMain_Table_Commande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string EtablissementComptable_PanelMain_Table_Libelle {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelMain_Table_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string EtablissementComptable_PanelMain_Table_Production {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelMain_Table_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer Etablissements Comptables.
        /// </summary>
        public static string EtablissementComptable_PanelMain_Titre {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelMain_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un Etablissement comptable.
        /// </summary>
        public static string EtablissementComptable_PanelMain_Titre_Ajouter {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelMain_Titre_Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier un Etablissement comptable.
        /// </summary>
        public static string EtablissementComptable_PanelMain_Titre_Modifier {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelMain_Titre_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Adresse {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Adresse_Placeholder {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Adresse_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Code {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 caractères max.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Code_Placeholder {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Code_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string EtablissementComptable_PanelRight_CodePostal {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code postal.
        /// </summary>
        public static string EtablissementComptable_PanelRight_CodePostal_Placeholder {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_CodePostal_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Commande {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Commande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Libelle {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Libelle_Placeholder {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Libelle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Pays {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Pays_Placeholder {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Pays_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Production {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Ville {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ville.
        /// </summary>
        public static string EtablissementComptable_PanelRight_Ville_Placeholder {
            get {
                return ResourceManager.GetString("EtablissementComptable_PanelRight_Ville_Placeholder", resourceCulture);
            }
        }
    }
}
