//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureRapport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureRapport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Models.App_LocalResources.FeatureRapport", typeof(FeatureRapport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un code d&apos;absence.
        /// </summary>
        public static string AjouterCodeAbsence_lb {
            get {
                return ResourceManager.GetString("AjouterCodeAbsence_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un code déplacement.
        /// </summary>
        public static string AjouterCodeDeplacement_lb {
            get {
                return ResourceManager.GetString("AjouterCodeDeplacement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un code majoration.
        /// </summary>
        public static string AjouterCodeMajorartion_lb {
            get {
                return ResourceManager.GetString("AjouterCodeMajorartion_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une ligne.
        /// </summary>
        public static string AjouterLigne_lb {
            get {
                return ResourceManager.GetString("AjouterLigne_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une prime.
        /// </summary>
        public static string AjouterPrime_lb {
            get {
                return ResourceManager.GetString("AjouterPrime_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une tâche.
        /// </summary>
        public static string AjouterTache_lb {
            get {
                return ResourceManager.GetString("AjouterTache_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur Modification.
        /// </summary>
        public static string AuteurModification_lb {
            get {
                return ResourceManager.GetString("AuteurModification_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres.
        /// </summary>
        public static string Autres_lb {
            get {
                return ResourceManager.GetString("Autres_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Btn_Annuler_lb {
            get {
                return ResourceManager.GetString("Btn_Annuler_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non vérrouillé.
        /// </summary>
        public static string Btn_RechercheStatutNonVerrouille_lb {
            get {
                return ResourceManager.GetString("Btn_RechercheStatutNonVerrouille_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validé.
        /// </summary>
        public static string Btn_RechercheStatutValide_lb {
            get {
                return ResourceManager.GetString("Btn_RechercheStatutValide_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérrouillé.
        /// </summary>
        public static string Btn_RechercheStatutVerrouille_lb {
            get {
                return ResourceManager.GetString("Btn_RechercheStatutVerrouille_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les statuts.
        /// </summary>
        public static string Btn_RechercheToutStatut_lb {
            get {
                return ResourceManager.GetString("Btn_RechercheToutStatut_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Btn_Suppression_lb {
            get {
                return ResourceManager.GetString("Btn_Suppression_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer.
        /// </summary>
        public static string Button_Genere_lb {
            get {
                return ResourceManager.GetString("Button_Genere_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déverrouiller.
        /// </summary>
        public static string Button_ToutDeverrouiller_lb {
            get {
                return ResourceManager.GetString("Button_ToutDeverrouiller_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérrouiller.
        /// </summary>
        public static string Button_ToutVerrouiller_lb {
            get {
                return ResourceManager.GetString("Button_ToutVerrouiller_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger le fichier Excel.
        /// </summary>
        public static string ButtonGenerateExcel_lb {
            get {
                return ResourceManager.GetString("ButtonGenerateExcel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour télécharger le fichier PDF.
        /// </summary>
        public static string ButtonGenerateExcel_tip {
            get {
                return ResourceManager.GetString("ButtonGenerateExcel_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Télécharger le PDF.
        /// </summary>
        public static string ButtonGeneratePDF_lb {
            get {
                return ResourceManager.GetString("ButtonGeneratePDF_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour télécharger le fichier PDF.
        /// </summary>
        public static string ButtonGeneratePDF_tip {
            get {
                return ResourceManager.GetString("ButtonGeneratePDF_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ obligatoire.
        /// </summary>
        public static string ChampObligatoire_lb {
            get {
                return ResourceManager.GetString("ChampObligatoire_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs de recherche.
        /// </summary>
        public static string ChampRecherche_lb {
            get {
                return ResourceManager.GetString("ChampRecherche_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout sélectionner.
        /// </summary>
        public static string Chk_ToutSelectionner_lb {
            get {
                return ResourceManager.GetString("Chk_ToutSelectionner_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les pointages anticipés.
        /// </summary>
        public static string Choix_Pointage_Anticipe_lb {
            get {
                return ResourceManager.GetString("Choix_Pointage_Anticipe_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les pointages réels.
        /// </summary>
        public static string Choix_Pointage_Reel_lb {
            get {
                return ResourceManager.GetString("Choix_Pointage_Reel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le CI est obligatoire.
        /// </summary>
        public static string CIObligatoire_warning {
            get {
                return ResourceManager.GetString("CIObligatoire_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence.
        /// </summary>
        public static string Col_Absence_lb {
            get {
                return ResourceManager.GetString("Col_Absence_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout.
        /// </summary>
        public static string Col_AjoutPointage_lb {
            get {
                return ResourceManager.GetString("Col_AjoutPointage_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt.
        /// </summary>
        public static string Col_Arret_lb {
            get {
                return ResourceManager.GetString("Col_Arret_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI.
        /// </summary>
        public static string Col_Ci_lb {
            get {
                return ResourceManager.GetString("Col_Ci_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Col_Code_lb {
            get {
                return ResourceManager.GetString("Col_Code_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Abs.
        /// </summary>
        public static string Col_CodeAbsence_lb {
            get {
                return ResourceManager.GetString("Col_CodeAbsence_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Dep.
        /// </summary>
        public static string Col_CodeDeplacement_lb {
            get {
                return ResourceManager.GetString("Col_CodeDeplacement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Maj.
        /// </summary>
        public static string Col_CodeMajoration_lb {
            get {
                return ResourceManager.GetString("Col_CodeMajoration_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déplacement.
        /// </summary>
        public static string Col_Deplacement_lb {
            get {
                return ResourceManager.GetString("Col_Deplacement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâches.
        /// </summary>
        public static string Col_DeplierListeTache_lb {
            get {
                return ResourceManager.GetString("Col_DeplierListeTache_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entreprise.
        /// </summary>
        public static string Col_Entreprise_lb {
            get {
                return ResourceManager.GetString("Col_Entreprise_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entreprise.
        /// </summary>
        public static string Col_EntrepriseMateriel_lb {
            get {
                return ResourceManager.GetString("Col_EntrepriseMateriel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAbs.
        /// </summary>
        public static string Col_HeureAbsence_lb {
            get {
                return ResourceManager.GetString("Col_HeureAbsence_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMaj.
        /// </summary>
        public static string Col_HeureMajoration_lb {
            get {
                return ResourceManager.GetString("Col_HeureMajoration_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HNorm.
        /// </summary>
        public static string Col_HeureNormale_lb {
            get {
                return ResourceManager.GetString("Col_HeureNormale_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heures.
        /// </summary>
        public static string Col_Heures_lb {
            get {
                return ResourceManager.GetString("Col_Heures_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. norm.
        /// </summary>
        public static string Col_HeuresNormales_lb {
            get {
                return ResourceManager.GetString("Col_HeuresNormales_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. nuit.
        /// </summary>
        public static string Col_HeuresNuit_lb {
            get {
                return ResourceManager.GetString("Col_HeuresNuit_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H. totales travaillées.
        /// </summary>
        public static string Col_HeuresTotalesTravaillees_lb {
            get {
                return ResourceManager.GetString("Col_HeuresTotalesTravaillees_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intemperie.
        /// </summary>
        public static string Col_Intemperie_lb {
            get {
                return ResourceManager.GetString("Col_Intemperie_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVD.
        /// </summary>
        public static string Col_IVD_lb {
            get {
                return ResourceManager.GetString("Col_IVD_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Col_ListePointagesPersonnelsDate_lb {
            get {
                return ResourceManager.GetString("Col_ListePointagesPersonnelsDate_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majoration.
        /// </summary>
        public static string Col_Majoration_lb {
            get {
                return ResourceManager.GetString("Col_Majoration_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majorées.
        /// </summary>
        public static string Col_Majorees_lb {
            get {
                return ResourceManager.GetString("Col_Majorees_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marche.
        /// </summary>
        public static string Col_Marche_lb {
            get {
                return ResourceManager.GetString("Col_Marche_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matériel.
        /// </summary>
        public static string Col_Materiel_lb {
            get {
                return ResourceManager.GetString("Col_Materiel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricule.
        /// </summary>
        public static string Col_Matricule_lb {
            get {
                return ResourceManager.GetString("Col_Matricule_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Col_Nom_lb {
            get {
                return ResourceManager.GetString("Col_Nom_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Col_NomMateriel_lb {
            get {
                return ResourceManager.GetString("Col_NomMateriel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° interne.
        /// </summary>
        public static string Col_NumInterneMateriel_lb {
            get {
                return ResourceManager.GetString("Col_NumInterneMateriel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Sem Int.
        /// </summary>
        public static string Col_NumSemaineIntemperie_lb {
            get {
                return ResourceManager.GetString("Col_NumSemaineIntemperie_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panne.
        /// </summary>
        public static string Col_Panne_lb {
            get {
                return ResourceManager.GetString("Col_Panne_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel.
        /// </summary>
        public static string Col_Personnel_lb {
            get {
                return ResourceManager.GetString("Col_Personnel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primes.
        /// </summary>
        public static string Col_Primes_lb {
            get {
                return ResourceManager.GetString("Col_Primes_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tâches.
        /// </summary>
        public static string Col_Taches_lb {
            get {
                return ResourceManager.GetString("Col_Taches_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Col_Total_lb {
            get {
                return ResourceManager.GetString("Col_Total_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Col_Zone_lb {
            get {
                return ResourceManager.GetString("Col_Zone_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer le rapport : {0}?.
        /// </summary>
        public static string ConfirmationSuppression_lb {
            get {
                return ResourceManager.GetString("ConfirmationSuppression_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention, tout changement de CI va ré-initialiser entièrement ce rapport, voulez-vous continuer ?.
        /// </summary>
        public static string ConfirmDeleteCi_lb {
            get {
                return ResourceManager.GetString("ConfirmDeleteCi_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Contrôle des pointages.
        /// </summary>
        public static string ControlePointageRapport_lb {
            get {
                return ResourceManager.GetString("ControlePointageRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critères de recherche.
        /// </summary>
        public static string CritereRecherche_lb {
            get {
                return ResourceManager.GetString("CritereRecherche_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date comptable.
        /// </summary>
        public static string DateComptable_lb {
            get {
                return ResourceManager.GetString("DateComptable_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de début de duplication.
        /// </summary>
        public static string DateDebutDuplication_lb {
            get {
                return ResourceManager.GetString("DateDebutDuplication_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de fin de duplication.
        /// </summary>
        public static string DateFinDuplication_lb {
            get {
                return ResourceManager.GetString("DateFinDuplication_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date du rapport.
        /// </summary>
        public static string DateRapport_lb {
            get {
                return ResourceManager.GetString("DateRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir le rapport.
        /// </summary>
        public static string Detail_lb {
            get {
                return ResourceManager.GetString("Detail_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les rapports ont été dévérrouillés avec succès.
        /// </summary>
        public static string deverrouillage_success {
            get {
                return ResourceManager.GetString("deverrouillage_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ou les personnes suivantes ont été saisies plusieurs fois : {0}.
        /// </summary>
        public static string DoublonSaisiePersonnel_warning {
            get {
                return ResourceManager.GetString("DoublonSaisiePersonnel_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplication des lignes de pointage.
        /// </summary>
        public static string DuplicationPointages_lb {
            get {
                return ResourceManager.GetString("DuplicationPointages_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ligne(s) de pointage on correctement été générée(s).
        /// </summary>
        public static string DuplicationPointages_success {
            get {
                return ResourceManager.GetString("DuplicationPointages_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplication du rapport effectué avec succès !.
        /// </summary>
        public static string DuplicationRapport_success {
            get {
                return ResourceManager.GetString("DuplicationRapport_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition du contrôle des pointages.
        /// </summary>
        public static string EditionControlePointage_lb {
            get {
                return ResourceManager.GetString("EditionControlePointage_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement du rapport effectué avec succès !.
        /// </summary>
        public static string EnregistrementRapport_success {
            get {
                return ResourceManager.GetString("EnregistrementRapport_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract :.
        /// </summary>
        public static string Extract_lb {
            get {
                return ResourceManager.GetString("Extract_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtré par.
        /// </summary>
        public static string FiltrerPar_lb {
            get {
                return ResourceManager.GetString("FiltrerPar_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de lignes ayant rencontré des erreurs : .
        /// </summary>
        public static string Generation_Ligne_Error_lb {
            get {
                return ResourceManager.GetString("Generation_Ligne_Error_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de ligne non traitées : .
        /// </summary>
        public static string Generation_Ligne_NonTrait_lb {
            get {
                return ResourceManager.GetString("Generation_Ligne_NonTrait_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de lignes traitées : .
        /// </summary>
        public static string Generation_Ligne_Traite_lb {
            get {
                return ResourceManager.GetString("Generation_Ligne_Traite_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les pointages anticipés ont été générés avec succès.
        /// </summary>
        public static string Generation_success {
            get {
                return ResourceManager.GetString("Generation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les heures d&apos;absence ne sont pas paramétrées.
        /// </summary>
        public static string HAbsence0_warning {
            get {
                return ResourceManager.GetString("HAbsence0_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les heures saisies sont invalides.
        /// </summary>
        public static string HeuresInvalides_warning {
            get {
                return ResourceManager.GetString("HeuresInvalides_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les heures majorées ne sont pas paramétrées.
        /// </summary>
        public static string HMajoration0_warning {
            get {
                return ResourceManager.GetString("HMajoration0_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nombre d&apos;heures travaillées ne correspond pas à la somme des heures affectées aux tâches.
        /// </summary>
        public static string HNormAndHMajoNotMatchWithHTaches_warning {
            get {
                return ResourceManager.GetString("HNormAndHMajoNotMatchWithHTaches_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les tranches horaires sont incorrectes.
        /// </summary>
        public static string Horaires_Tranches_error_lb {
            get {
                return ResourceManager.GetString("Horaires_Tranches_error_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé par {0} le {1}.
        /// </summary>
        public static string InformationCreateurRapport_lb {
            get {
                return ResourceManager.GetString("InformationCreateurRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifié par {0} le {1}.
        /// </summary>
        public static string InformationModificateurRapport_lb {
            get {
                return ResourceManager.GetString("InformationModificateurRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journée.
        /// </summary>
        public static string JourneeRapport_lb {
            get {
                return ResourceManager.GetString("JourneeRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ligne.
        /// </summary>
        public static string Ligne_lb {
            get {
                return ResourceManager.GetString("Ligne_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Liste des IGD.
        /// </summary>
        public static string ListeIgdRapport_lb {
            get {
                return ResourceManager.GetString("ListeIgdRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Liste des primes.
        /// </summary>
        public static string ListePrimeRapport_lb {
            get {
                return ResourceManager.GetString("ListePrimeRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricule.
        /// </summary>
        public static string Matricule_lb {
            get {
                return ResourceManager.GetString("Matricule_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nombre d&apos;heures maximales travaillées ({0}h) a été dépassé.
        /// </summary>
        public static string MaxHeuresTravailleesJourDepasse_warning {
            get {
                return ResourceManager.GetString("MaxHeuresTravailleesJourDepasse_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string ModalButtonClose_lb {
            get {
                return ResourceManager.GetString("ModalButtonClose_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour fermer la fenêtre.
        /// </summary>
        public static string ModalButtonClose_title {
            get {
                return ResourceManager.GetString("ModalButtonClose_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquer pour fermer la fenêtre.
        /// </summary>
        public static string ModalTitleCloseHeader_lb {
            get {
                return ResourceManager.GetString("ModalTitleCloseHeader_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon périmetre.
        /// </summary>
        public static string MonPerimetre_lb {
            get {
                return ResourceManager.GetString("MonPerimetre_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre maximum de prime atteint.
        /// </summary>
        public static string NbMaxPrimeAtteint_warning {
            get {
                return ResourceManager.GetString("NbMaxPrimeAtteint_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Nom_lb {
            get {
                return ResourceManager.GetString("Nom_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il est nécessaire de saisir des heures de travail ou d&apos;absence.
        /// </summary>
        public static string NonSaisieHeureTravailleeNiHeureAbsence_warning {
            get {
                return ResourceManager.GetString("NonSaisieHeureTravailleeNiHeureAbsence_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau Rapport.
        /// </summary>
        public static string Nouveau_lb {
            get {
                return ResourceManager.GetString("Nouveau_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport n°.
        /// </summary>
        public static string NumeroRapport_lb {
            get {
                return ResourceManager.GetString("NumeroRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string Organisation_lb {
            get {
                return ResourceManager.GetString("Organisation_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez renseigner une personne.
        /// </summary>
        public static string PasDePersonnel_warning {
            get {
                return ResourceManager.GetString("PasDePersonnel_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rappel non bloquant: la personne suivante a déjà été saisie : {0}.
        /// </summary>
        public static string PersonnelExistant_warning {
            get {
                return ResourceManager.GetString("PersonnelExistant_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointages.
        /// </summary>
        public static string Pointages_lb {
            get {
                return ResourceManager.GetString("Pointages_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Controle des pointages&lt;/b&gt; réels manquants.
        /// </summary>
        public static string PointageTitleExport_lb {
            get {
                return ResourceManager.GetString("PointageTitleExport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle des pointages .
        /// </summary>
        public static string PointageTitleExportPart1_lb {
            get {
                return ResourceManager.GetString("PointageTitleExportPart1_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to réels manquants .
        /// </summary>
        public static string PointageTitleExportPart2_lb {
            get {
                return ResourceManager.GetString("PointageTitleExportPart2_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La prime existe déjà.
        /// </summary>
        public static string PrimeExisteDeja_warning {
            get {
                return ResourceManager.GetString("PrimeExisteDeja_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport journalier du.
        /// </summary>
        public static string RapportJournalierDu_lb {
            get {
                return ResourceManager.GetString("RapportJournalierDu_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des rapports.
        /// </summary>
        public static string RapportListe_lb {
            get {
                return ResourceManager.GetString("RapportListe_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chercher un rapport.
        /// </summary>
        public static string RapportListeRecherche_placeholder {
            get {
                return ResourceManager.GetString("RapportListeRecherche_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un CI.
        /// </summary>
        public static string RechercheCI {
            get {
                return ResourceManager.GetString("RechercheCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code CI.
        /// </summary>
        public static string RechercheCodeCI_lb {
            get {
                return ResourceManager.GetString("RechercheCodeCI_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un code majoration.
        /// </summary>
        public static string RechercheCodeMajoration {
            get {
                return ResourceManager.GetString("RechercheCodeMajoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jusqu&apos;au : .
        /// </summary>
        public static string RechercheDateMax_Lb {
            get {
                return ResourceManager.GetString("RechercheDateMax_Lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partir du : .
        /// </summary>
        public static string RechercheDateMin_Lb {
            get {
                return ResourceManager.GetString("RechercheDateMin_Lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libelle CI.
        /// </summary>
        public static string RechercheLibelleCI_lb {
            get {
                return ResourceManager.GetString("RechercheLibelleCI_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un personnel.
        /// </summary>
        public static string RecherchePersonnel {
            get {
                return ResourceManager.GetString("RecherchePersonnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rédacteur.
        /// </summary>
        public static string RechercheRedacteurCI_lb {
            get {
                return ResourceManager.GetString("RechercheRedacteurCI_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche des rapports.
        /// </summary>
        public static string RechercherRapports_lb {
            get {
                return ResourceManager.GetString("RechercherRapports_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut des rapports : .
        /// </summary>
        public static string RechercheStatut_Lb {
            get {
                return ResourceManager.GetString("RechercheStatut_Lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valideur.
        /// </summary>
        public static string RechercheValideur_lb {
            get {
                return ResourceManager.GetString("RechercheValideur_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rédacteur : .
        /// </summary>
        public static string RedacteurRapport_lb {
            get {
                return ResourceManager.GetString("RedacteurRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de pointage anticipé.
        /// </summary>
        public static string SaisiePointageAnticipe_lb {
            get {
                return ResourceManager.GetString("SaisiePointageAnticipe_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de pointage réel.
        /// </summary>
        public static string SaisiePointageReel_lb {
            get {
                return ResourceManager.GetString("SaisiePointageReel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisie .
        /// </summary>
        public static string SaisieRapport_lb {
            get {
                return ResourceManager.GetString("SaisieRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  par .
        /// </summary>
        public static string SaisieRapportAuteur_lb {
            get {
                return ResourceManager.GetString("SaisieRapportAuteur_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  le .
        /// </summary>
        public static string SaisieRapportDate_lb {
            get {
                return ResourceManager.GetString("SaisieRapportDate_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaine.
        /// </summary>
        public static string SemaineRapport_lb {
            get {
                return ResourceManager.GetString("SemaineRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Statut_lb {
            get {
                return ResourceManager.GetString("Statut_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression du rapport effectuée avec succès !.
        /// </summary>
        public static string SuppressionRapport_success {
            get {
                return ResourceManager.GetString("SuppressionRapport_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression d&apos;un rapport.
        /// </summary>
        public static string SuppressionRapportModal_Tit {
            get {
                return ResourceManager.GetString("SuppressionRapportModal_Tit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tâche existe déjà.
        /// </summary>
        public static string TacheExisteDeja_warning {
            get {
                return ResourceManager.GetString("TacheExisteDeja_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y pas d&apos;heures affectées à la tâche {0}.
        /// </summary>
        public static string TacheSansHeure_warning {
            get {
                return ResourceManager.GetString("TacheSansHeure_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taches de pointage.
        /// </summary>
        public static string TachesPointage_lb {
            get {
                return ResourceManager.GetString("TachesPointage_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tri :.
        /// </summary>
        public static string Tri_lb {
            get {
                return ResourceManager.GetString("Tri_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Organisation.
        /// </summary>
        public static string TypeOrganisation_lb {
            get {
                return ResourceManager.GetString("TypeOrganisation_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il est nécessaire de paramétrer au moins une ligne de pointage.
        /// </summary>
        public static string UneLigneMinimum_warning {
            get {
                return ResourceManager.GetString("UneLigneMinimum_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il est nécessaire de paramétrer au moins une tâche.
        /// </summary>
        public static string UneTacheMinimum_warning {
            get {
                return ResourceManager.GetString("UneTacheMinimum_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les rapports ont été vérrouillés avec succès.
        /// </summary>
        public static string validation_success {
            get {
                return ResourceManager.GetString("validation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune Validation.
        /// </summary>
        public static string ValidationAbsente_lb {
            get {
                return ResourceManager.GetString("ValidationAbsente_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Chef de chantier.
        /// </summary>
        public static string ValidationChefChantier_lb {
            get {
                return ResourceManager.GetString("ValidationChefChantier_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune validation de la part d&apos;un chef de chantier.
        /// </summary>
        public static string ValidationChefChantierAbsente_lb {
            get {
                return ResourceManager.GetString("ValidationChefChantierAbsente_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  par .
        /// </summary>
        public static string ValidationChefChantierAuteur_lb {
            get {
                return ResourceManager.GetString("ValidationChefChantierAuteur_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  le .
        /// </summary>
        public static string ValidationChefChantierDate_lb {
            get {
                return ResourceManager.GetString("ValidationChefChantierDate_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Conducteur de travaux.
        /// </summary>
        public static string ValidationConducteurTravaux_lb {
            get {
                return ResourceManager.GetString("ValidationConducteurTravaux_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune validation de la part d&apos;un conducteur de travaux.
        /// </summary>
        public static string ValidationConducteurTravauxAbsente_lb {
            get {
                return ResourceManager.GetString("ValidationConducteurTravauxAbsente_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  par .
        /// </summary>
        public static string ValidationConducteurTravauxAuteur_lb {
            get {
                return ResourceManager.GetString("ValidationConducteurTravauxAuteur_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  le .
        /// </summary>
        public static string ValidationConducteurTravauxDate_lb {
            get {
                return ResourceManager.GetString("ValidationConducteurTravauxDate_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Directeur de chantier.
        /// </summary>
        public static string ValidationDirecteurChantier_lb {
            get {
                return ResourceManager.GetString("ValidationDirecteurChantier_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune validation de la part d&apos;un directeur de travaux.
        /// </summary>
        public static string ValidationDirecteurChantierAbsente_lb {
            get {
                return ResourceManager.GetString("ValidationDirecteurChantierAbsente_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  par .
        /// </summary>
        public static string ValidationDirecteurChantierAuteur_lb {
            get {
                return ResourceManager.GetString("ValidationDirecteurChantierAuteur_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  le .
        /// </summary>
        public static string ValidationDirecteurChantierDate_lb {
            get {
                return ResourceManager.GetString("ValidationDirecteurChantierDate_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérouillage Gestion de paie.
        /// </summary>
        public static string ValidationGestionnairePaie_lb {
            get {
                return ResourceManager.GetString("ValidationGestionnairePaie_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun vérrouillage de la part d&apos;un gestionnaire de paie.
        /// </summary>
        public static string ValidationGestionnairePaieAbsente_lb {
            get {
                return ResourceManager.GetString("ValidationGestionnairePaieAbsente_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  par .
        /// </summary>
        public static string ValidationGestionnairePaieAuteur_lb {
            get {
                return ResourceManager.GetString("ValidationGestionnairePaieAuteur_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  le .
        /// </summary>
        public static string ValidationGestionnairePaieDate_lb {
            get {
                return ResourceManager.GetString("ValidationGestionnairePaieDate_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation le :.
        /// </summary>
        public static string ValidationRapport_lb {
            get {
                return ResourceManager.GetString("ValidationRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation du rapport effectuée avec succès !.
        /// </summary>
        public static string ValidationRapport_success {
            get {
                return ResourceManager.GetString("ValidationRapport_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valideur : .
        /// </summary>
        public static string ValideurRapport_lb {
            get {
                return ResourceManager.GetString("ValideurRapport_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef de Chantier.
        /// </summary>
        public static string ValitationChefChantier_Title {
            get {
                return ResourceManager.GetString("ValitationChefChantier_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conducteur de travaux.
        /// </summary>
        public static string ValitationConducteurTravaux_Title {
            get {
                return ResourceManager.GetString("ValitationConducteurTravaux_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondant paye.
        /// </summary>
        public static string ValitationCorrespondantPaye_Title {
            get {
                return ResourceManager.GetString("ValitationCorrespondantPaye_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directeur de chantier.
        /// </summary>
        public static string ValitationDirecteurChantier_Title {
            get {
                return ResourceManager.GetString("ValitationDirecteurChantier_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Vérification des temps.
        /// </summary>
        public static string VerifTempsRapport_lb {
            get {
                return ResourceManager.GetString("VerifTempsRapport_lb", resourceCulture);
            }
        }
    }
}
