//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fred.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureIndemniteDeplacement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureIndemniteDeplacement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fred.Models.App_LocalResources.FeatureIndemniteDeplacement", typeof(FeatureIndemniteDeplacement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une indemnité de déplacement.
        /// </summary>
        public static string AjouterIndemniteDeplacement_lb {
            get {
                return ResourceManager.GetString("AjouterIndemniteDeplacement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcul.
        /// </summary>
        public static string Calcul_lb {
            get {
                return ResourceManager.GetString("Calcul_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le calcul n&apos;a retourné aucun résultat, veuillez revoir le paramétrage du Personnel et du CI correspondants..
        /// </summary>
        public static string CalculKmImpossible_lb {
            get {
                return ResourceManager.GetString("CalculKmImpossible_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcul effectué avec succès..
        /// </summary>
        public static string CalculKmSuccess_lb {
            get {
                return ResourceManager.GetString("CalculKmSuccess_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chantier - Rattachement.
        /// </summary>
        public static string ChantierRattachement_lb {
            get {
                return ResourceManager.GetString("ChantierRattachement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI.
        /// </summary>
        public static string CI_lb {
            get {
                return ResourceManager.GetString("CI_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Déplacement.
        /// </summary>
        public static string CodeDeplacement_lb {
            get {
                return ResourceManager.GetString("CodeDeplacement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de créer une indemnité avec les deux Codes Déplacement et Zone Déplacement vides..
        /// </summary>
        public static string CodesVidesError_lb {
            get {
                return ResourceManager.GetString("CodesVidesError_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Zone Déplacement.
        /// </summary>
        public static string CodeZoneDeplacement_lb {
            get {
                return ResourceManager.GetString("CodeZoneDeplacement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs obligatoire.
        /// </summary>
        public static string Data_required {
            get {
                return ResourceManager.GetString("Data_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernier calcul.
        /// </summary>
        public static string DateDernierCalcul_lb {
            get {
                return ResourceManager.GetString("DateDernierCalcul_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicile - Chantier.
        /// </summary>
        public static string DomicileChantier_lb {
            get {
                return ResourceManager.GetString("DomicileChantier_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicile - Rattachement.
        /// </summary>
        public static string DomicileRattachement_lb {
            get {
                return ResourceManager.GetString("DomicileRattachement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Km non valide.
        /// </summary>
        public static string KmInvalid_warning {
            get {
                return ResourceManager.GetString("KmInvalid_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier une indemnité de déplacement.
        /// </summary>
        public static string ModifierIndemniteDeplacement_lb {
            get {
                return ResourceManager.GetString("ModifierIndemniteDeplacement_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de kilomètres routier.
        /// </summary>
        public static string NombreKilometres_lb {
            get {
                return ResourceManager.GetString("NombreKilometres_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de kilomètres VO.
        /// </summary>
        public static string NombreKilometreVO_lb {
            get {
                return ResourceManager.GetString("NombreKilometreVO_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculer.
        /// </summary>
        public static string Recalculer_lb {
            get {
                return ResourceManager.GetString("Recalculer_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une Indemnité de Déplacement ....
        /// </summary>
        public static string Recherche_placeholder {
            get {
                return ResourceManager.GetString("Recherche_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la liste du Personnel.
        /// </summary>
        public static string RetourListePersonnel_lb {
            get {
                return ResourceManager.GetString("RetourListePersonnel_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisie Manuelle.
        /// </summary>
        public static string SaisieManuelle_lb {
            get {
                return ResourceManager.GetString("SaisieManuelle_lb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des indemnités de déplacement.
        /// </summary>
        public static string TitrePage_IndemniteDeplacement_lb {
            get {
                return ResourceManager.GetString("TitrePage_IndemniteDeplacement_lb", resourceCulture);
            }
        }
    }
}
